// Generated by @specodec/typespec-emitter-cpp. DO NOT EDIT.
export module all_types;
import std;
import specodec;

namespace all_types {

export struct Inner {
    std::int32_t x;
    std::int32_t y;
};

export inline void write_inner(specodec::SpecWriter& w, const Inner& obj) {
    w.beginObject(2);
    w.writeField("x"); w.writeInt32(obj.x);;
    w.writeField("y"); w.writeInt32(obj.y);;
    w.endObject();
}

export inline specodec::SpecCodec<Inner> InnerCodec = {
    .encode = [](specodec::SpecWriter& w, const Inner& obj) { write_inner(w, obj); },
    .decode = [](specodec::SpecReader& r) -> Inner {
        std::int32_t fld_x = 0;
        std::int32_t fld_y = 0;
        r.beginObject();
        while (r.hasNextField()) {
            auto field_name = r.readFieldName();
            if (field_name == "x") { fld_x = r.readInt32(); }
            else if (field_name == "y") { fld_y = r.readInt32(); }
            else { r.skip(); }
        }
        r.endObject();
        return Inner{fld_x, fld_y};
    }
};

export struct Coord {
    double lat;
    double lng;
};

export inline void write_coord(specodec::SpecWriter& w, const Coord& obj) {
    w.beginObject(2);
    w.writeField("lat"); w.writeFloat64(obj.lat);;
    w.writeField("lng"); w.writeFloat64(obj.lng);;
    w.endObject();
}

export inline specodec::SpecCodec<Coord> CoordCodec = {
    .encode = [](specodec::SpecWriter& w, const Coord& obj) { write_coord(w, obj); },
    .decode = [](specodec::SpecReader& r) -> Coord {
        double fld_lat = 0.0;
        double fld_lng = 0.0;
        r.beginObject();
        while (r.hasNextField()) {
            auto field_name = r.readFieldName();
            if (field_name == "lat") { fld_lat = r.readFloat64(); }
            else if (field_name == "lng") { fld_lng = r.readFloat64(); }
            else { r.skip(); }
        }
        r.endObject();
        return Coord{fld_lat, fld_lng};
    }
};

export struct IdVal {
    std::string id;
    std::int32_t value;
};

export inline void write_id_val(specodec::SpecWriter& w, const IdVal& obj) {
    w.beginObject(2);
    w.writeField("id"); w.writeString(obj.id);;
    w.writeField("value"); w.writeInt32(obj.value);;
    w.endObject();
}

export inline specodec::SpecCodec<IdVal> IdValCodec = {
    .encode = [](specodec::SpecWriter& w, const IdVal& obj) { write_id_val(w, obj); },
    .decode = [](specodec::SpecReader& r) -> IdVal {
        std::string fld_id = "";
        std::int32_t fld_value = 0;
        r.beginObject();
        while (r.hasNextField()) {
            auto field_name = r.readFieldName();
            if (field_name == "id") { fld_id = r.readString(); }
            else if (field_name == "value") { fld_value = r.readInt32(); }
            else { r.skip(); }
        }
        r.endObject();
        return IdVal{fld_id, fld_value};
    }
};

export struct Label {
    std::string key;
    std::string text;
};

export inline void write_label(specodec::SpecWriter& w, const Label& obj) {
    w.beginObject(2);
    w.writeField("key"); w.writeString(obj.key);;
    w.writeField("text"); w.writeString(obj.text);;
    w.endObject();
}

export inline specodec::SpecCodec<Label> LabelCodec = {
    .encode = [](specodec::SpecWriter& w, const Label& obj) { write_label(w, obj); },
    .decode = [](specodec::SpecReader& r) -> Label {
        std::string fld_key = "";
        std::string fld_text = "";
        r.beginObject();
        while (r.hasNextField()) {
            auto field_name = r.readFieldName();
            if (field_name == "key") { fld_key = r.readString(); }
            else if (field_name == "text") { fld_text = r.readString(); }
            else { r.skip(); }
        }
        r.endObject();
        return Label{fld_key, fld_text};
    }
};

export struct Money {
    std::int64_t amount;
    std::string currency;
};

export inline void write_money(specodec::SpecWriter& w, const Money& obj) {
    w.beginObject(2);
    w.writeField("amount"); w.writeInt64(obj.amount);;
    w.writeField("currency"); w.writeString(obj.currency);;
    w.endObject();
}

export inline specodec::SpecCodec<Money> MoneyCodec = {
    .encode = [](specodec::SpecWriter& w, const Money& obj) { write_money(w, obj); },
    .decode = [](specodec::SpecReader& r) -> Money {
        std::int64_t fld_amount = 0LL;
        std::string fld_currency = "";
        r.beginObject();
        while (r.hasNextField()) {
            auto field_name = r.readFieldName();
            if (field_name == "amount") { fld_amount = r.readInt64(); }
            else if (field_name == "currency") { fld_currency = r.readString(); }
            else { r.skip(); }
        }
        r.endObject();
        return Money{fld_amount, fld_currency};
    }
};

export struct Range32 {
    std::int32_t min;
    std::int32_t max;
};

export inline void write_range32(specodec::SpecWriter& w, const Range32& obj) {
    w.beginObject(2);
    w.writeField("min"); w.writeInt32(obj.min);;
    w.writeField("max"); w.writeInt32(obj.max);;
    w.endObject();
}

export inline specodec::SpecCodec<Range32> Range32Codec = {
    .encode = [](specodec::SpecWriter& w, const Range32& obj) { write_range32(w, obj); },
    .decode = [](specodec::SpecReader& r) -> Range32 {
        std::int32_t fld_min = 0;
        std::int32_t fld_max = 0;
        r.beginObject();
        while (r.hasNextField()) {
            auto field_name = r.readFieldName();
            if (field_name == "min") { fld_min = r.readInt32(); }
            else if (field_name == "max") { fld_max = r.readInt32(); }
            else { r.skip(); }
        }
        r.endObject();
        return Range32{fld_min, fld_max};
    }
};

export struct Addr {
    std::string street;
    std::string city;
    std::string zip;
};

export inline void write_addr(specodec::SpecWriter& w, const Addr& obj) {
    w.beginObject(3);
    w.writeField("street"); w.writeString(obj.street);;
    w.writeField("city"); w.writeString(obj.city);;
    w.writeField("zip"); w.writeString(obj.zip);;
    w.endObject();
}

export inline specodec::SpecCodec<Addr> AddrCodec = {
    .encode = [](specodec::SpecWriter& w, const Addr& obj) { write_addr(w, obj); },
    .decode = [](specodec::SpecReader& r) -> Addr {
        std::string fld_street = "";
        std::string fld_city = "";
        std::string fld_zip = "";
        r.beginObject();
        while (r.hasNextField()) {
            auto field_name = r.readFieldName();
            if (field_name == "street") { fld_street = r.readString(); }
            else if (field_name == "city") { fld_city = r.readString(); }
            else if (field_name == "zip") { fld_zip = r.readString(); }
            else { r.skip(); }
        }
        r.endObject();
        return Addr{fld_street, fld_city, fld_zip};
    }
};

export struct Point3 {
    double x;
    double y;
    double z;
};

export inline void write_point3(specodec::SpecWriter& w, const Point3& obj) {
    w.beginObject(3);
    w.writeField("x"); w.writeFloat64(obj.x);;
    w.writeField("y"); w.writeFloat64(obj.y);;
    w.writeField("z"); w.writeFloat64(obj.z);;
    w.endObject();
}

export inline specodec::SpecCodec<Point3> Point3Codec = {
    .encode = [](specodec::SpecWriter& w, const Point3& obj) { write_point3(w, obj); },
    .decode = [](specodec::SpecReader& r) -> Point3 {
        double fld_x = 0.0;
        double fld_y = 0.0;
        double fld_z = 0.0;
        r.beginObject();
        while (r.hasNextField()) {
            auto field_name = r.readFieldName();
            if (field_name == "x") { fld_x = r.readFloat64(); }
            else if (field_name == "y") { fld_y = r.readFloat64(); }
            else if (field_name == "z") { fld_z = r.readFloat64(); }
            else { r.skip(); }
        }
        r.endObject();
        return Point3{fld_x, fld_y, fld_z};
    }
};

export struct OptInner {
    std::optional<std::string> name;
    std::optional<double> score;
    std::optional<std::string> tag;
};

export inline void write_opt_inner(specodec::SpecWriter& w, const OptInner& obj) {
    int field_count = 0;
    if (obj.name.has_value()) field_count++;
    if (obj.score.has_value()) field_count++;
    if (obj.tag.has_value()) field_count++;
    w.beginObject(field_count);
    if (obj.name.has_value()) { w.writeField("name"); w.writeString(obj.name.value());; }
    if (obj.score.has_value()) { w.writeField("score"); w.writeFloat64(obj.score.value());; }
    if (obj.tag.has_value()) { w.writeField("tag"); w.writeString(obj.tag.value());; }
    w.endObject();
}

export inline specodec::SpecCodec<OptInner> OptInnerCodec = {
    .encode = [](specodec::SpecWriter& w, const OptInner& obj) { write_opt_inner(w, obj); },
    .decode = [](specodec::SpecReader& r) -> OptInner {
        std::optional<std::string> fld_name;
        std::optional<double> fld_score;
        std::optional<std::string> fld_tag;
        r.beginObject();
        while (r.hasNextField()) {
            auto field_name = r.readFieldName();
            if (field_name == "name") { fld_name = std::optional<std::string>{r.readString()}; }
            else if (field_name == "score") { fld_score = std::optional<double>{r.readFloat64()}; }
            else if (field_name == "tag") { fld_tag = std::optional<std::string>{r.readString()}; }
            else { r.skip(); }
        }
        r.endObject();
        return OptInner{fld_name, fld_score, fld_tag};
    }
};

} // namespace all_types