// Generated by @specodec/typespec-emitter-cpp. DO NOT EDIT.
export module all_types_nested_deep;
import std;
import specodec;
import all_types;
using namespace all_types;

namespace all_types_nested_deep {

export struct DeepModel {
    std::vector<std::uint8_t> payload_;
    std::int64_t count_;
};

export inline void write_deep_model(specodec::SpecWriter& w, const DeepModel& obj) {
    w.beginObject(2);
    w.writeField("payload"); w.writeBytes(obj.payload_);;
    w.writeField("count"); w.writeInt64(obj.count_);;
    w.endObject();
}

export inline specodec::SpecCodec<DeepModel> DeepModelCodec = {
    .encode = [](specodec::SpecWriter& w, const DeepModel& obj) { write_deep_model(w, obj); },
    .decode = [](specodec::SpecReader& r) -> DeepModel {
        std::vector<std::uint8_t> fld_payload = {};
        std::int64_t fld_count = 0LL;
        r.beginObject();
        while (r.hasNextField()) {
            auto field_name = r.readFieldName();
            if (field_name == "payload") { fld_payload = r.readBytes(); }
            else if (field_name == "count") { fld_count = r.readInt64(); }
            else { r.skip(); }
        }
        r.endObject();
        return DeepModel{fld_payload, fld_count};
    }
};

} // namespace all_types_nested_deep