// Generated by @specodec/typespec-emitter-cpp. DO NOT EDIT.
export module all_types_enums;
import std;
import specodec;
import all_types;
using namespace all_types;

namespace all_types_enums {

export struct EnumHolder {
    std::string color_;
    std::string priority_;
    std::string status_;
};

export inline void write_enum_holder(specodec::SpecWriter& w, const EnumHolder& obj) {
    w.beginObject(3);
    w.writeField("color"); w.writeString(obj.color_);;
    w.writeField("priority"); w.writeString(obj.priority_);;
    w.writeField("status"); w.writeString(obj.status_);;
    w.endObject();
}

export inline specodec::SpecCodec<EnumHolder> EnumHolderCodec = {
    .encode = [](specodec::SpecWriter& w, const EnumHolder& obj) { write_enum_holder(w, obj); },
    .decode = [](specodec::SpecReader& r) -> EnumHolder {
        std::string fld_color = "";;
        std::string fld_priority = "";;
        std::string fld_status = "";;
        r.beginObject();
        while (r.hasNextField()) {
            auto field_name = r.readFieldName();
            if (field_name == "color") { fld_color = r.readString(); }
            else if (field_name == "priority") { fld_priority = r.readString(); }
            else if (field_name == "status") { fld_status = r.readString(); }
            else { r.skip(); }
        }
        r.endObject();
        return EnumHolder{fld_color, fld_priority, fld_status};
    }
};

export struct OptEnumHolder {
    std::optional<std::string> color_;
    std::optional<std::string> priority_;
};

export inline void write_opt_enum_holder(specodec::SpecWriter& w, const OptEnumHolder& obj) {
    int field_count = 0;
    if (obj.color_.has_value()) field_count++;
    if (obj.priority_.has_value()) field_count++;
    w.beginObject(field_count);
    if (obj.color_.has_value()) { w.writeField("color"); w.writeString(obj.color_.value());; }
    if (obj.priority_.has_value()) { w.writeField("priority"); w.writeString(obj.priority_.value());; }
    w.endObject();
}

export inline specodec::SpecCodec<OptEnumHolder> OptEnumHolderCodec = {
    .encode = [](specodec::SpecWriter& w, const OptEnumHolder& obj) { write_opt_enum_holder(w, obj); },
    .decode = [](specodec::SpecReader& r) -> OptEnumHolder {
        std::optional<std::string> fld_color;
        std::optional<std::string> fld_priority;
        r.beginObject();
        while (r.hasNextField()) {
            auto field_name = r.readFieldName();
            if (field_name == "color") { fld_color = std::optional<std::string>{r.readString()}; }
            else if (field_name == "priority") { fld_priority = std::optional<std::string>{r.readString()}; }
            else { r.skip(); }
        }
        r.endObject();
        return OptEnumHolder{fld_color, fld_priority};
    }
};

export struct EnumArrayHolder {
    std::vector<std::string> colors_;
};

export inline void write_enum_array_holder(specodec::SpecWriter& w, const EnumArrayHolder& obj) {
    w.beginObject(1);
    w.writeField("colors"); 
        w.beginArray(obj.colors_.size());
        for (const auto& elem : obj.colors_) { w.nextElement(); w.writeString(elem); }
        w.endArray();
    w.endObject();
}

export inline specodec::SpecCodec<EnumArrayHolder> EnumArrayHolderCodec = {
    .encode = [](specodec::SpecWriter& w, const EnumArrayHolder& obj) { write_enum_array_holder(w, obj); },
    .decode = [](specodec::SpecReader& r) -> EnumArrayHolder {
        std::vector<std::string> fld_colors = {};
        r.beginObject();
        while (r.hasNextField()) {
            auto field_name = r.readFieldName();
            if (field_name == "colors") { fld_colors = [&]() {
    std::vector<std::string> result;
    r.beginArray();
    while (r.hasNextElement()) { result.push_back(r.readString()); }
    r.endArray();
    return result;
}(); }
            else { r.skip(); }
        }
        r.endObject();
        return EnumArrayHolder{fld_colors};
    }
};

export struct EnumMixedHolder {
    std::string status_;
    std::string name_;
    std::int32_t count_;
    bool active_;
};

export inline void write_enum_mixed_holder(specodec::SpecWriter& w, const EnumMixedHolder& obj) {
    w.beginObject(4);
    w.writeField("status"); w.writeString(obj.status_);;
    w.writeField("name"); w.writeString(obj.name_);;
    w.writeField("count"); w.writeInt32(obj.count_);;
    w.writeField("active"); w.writeBool(obj.active_);;
    w.endObject();
}

export inline specodec::SpecCodec<EnumMixedHolder> EnumMixedHolderCodec = {
    .encode = [](specodec::SpecWriter& w, const EnumMixedHolder& obj) { write_enum_mixed_holder(w, obj); },
    .decode = [](specodec::SpecReader& r) -> EnumMixedHolder {
        std::string fld_status = "";;
        std::string fld_name = "";
        std::int32_t fld_count = 0;
        bool fld_active = false;
        r.beginObject();
        while (r.hasNextField()) {
            auto field_name = r.readFieldName();
            if (field_name == "status") { fld_status = r.readString(); }
            else if (field_name == "name") { fld_name = r.readString(); }
            else if (field_name == "count") { fld_count = r.readInt32(); }
            else if (field_name == "active") { fld_active = r.readBool(); }
            else { r.skip(); }
        }
        r.endObject();
        return EnumMixedHolder{fld_status, fld_name, fld_count, fld_active};
    }
};

} // namespace all_types_enums