// Generated by @specodec/typespec-emitter-cpp. DO NOT EDIT.
export module all_types_unions;
import std;
import specodec;
import all_types;
using namespace all_types;

namespace all_types_unions {

export using Shape = std::variant<Coord, Range32>;

export inline void write_shape(specodec::SpecWriter& w, const Shape& obj) {
    w.beginObject(1);
    std::visit([&w](const auto& val) {
        if constexpr (std::is_same_v<std::decay_t<decltype(val)>, Coord>) { w.writeField("circle"); write_coord(w, val);; }
        else if constexpr (std::is_same_v<std::decay_t<decltype(val)>, Range32>) { w.writeField("rect"); write_range32(w, val);; }
    }, obj);
    w.endObject();
}

export inline specodec::SpecCodec<Shape> ShapeCodec = {
    .encode = [](specodec::SpecWriter& w, const Shape& obj) { write_shape(w, obj); },
    .decode = [](specodec::SpecReader& r) -> Shape {
        r.beginObject();
        if (!r.hasNextField()) { r.endObject(); throw std::runtime_error("empty union Shape"); }
        auto field_name = r.readFieldName();
        Shape result;
        if (field_name == "circle") { result = CoordCodec.decode(r); }
        else if (field_name == "rect") { result = Range32Codec.decode(r); }
        else { throw std::runtime_error("unknown variant for union Shape"); }
        while (r.hasNextField()) { r.readFieldName(); r.skip(); }
        r.endObject();
        return result;
    }
};

export using Ident = std::variant<std::string, std::int32_t>;

export inline void write_ident(specodec::SpecWriter& w, const Ident& obj) {
    w.beginObject(1);
    std::visit([&w](const auto& val) {
        if constexpr (std::is_same_v<std::decay_t<decltype(val)>, std::string>) { w.writeField("name"); w.writeString(val);; }
        else if constexpr (std::is_same_v<std::decay_t<decltype(val)>, std::int32_t>) { w.writeField("number"); w.writeInt32(val);; }
    }, obj);
    w.endObject();
}

export inline specodec::SpecCodec<Ident> IdentCodec = {
    .encode = [](specodec::SpecWriter& w, const Ident& obj) { write_ident(w, obj); },
    .decode = [](specodec::SpecReader& r) -> Ident {
        r.beginObject();
        if (!r.hasNextField()) { r.endObject(); throw std::runtime_error("empty union Ident"); }
        auto field_name = r.readFieldName();
        Ident result;
        if (field_name == "name") { result = r.readString(); }
        else if (field_name == "number") { result = r.readInt32(); }
        else { throw std::runtime_error("unknown variant for union Ident"); }
        while (r.hasNextField()) { r.readFieldName(); r.skip(); }
        r.endObject();
        return result;
    }
};

export using ResultMsg = std::variant<std::string, Label>;

export inline void write_result_msg(specodec::SpecWriter& w, const ResultMsg& obj) {
    w.beginObject(1);
    std::visit([&w](const auto& val) {
        if constexpr (std::is_same_v<std::decay_t<decltype(val)>, std::string>) { w.writeField("ok"); w.writeString(val);; }
        else if constexpr (std::is_same_v<std::decay_t<decltype(val)>, Label>) { w.writeField("err"); write_label(w, val);; }
    }, obj);
    w.endObject();
}

export inline specodec::SpecCodec<ResultMsg> ResultMsgCodec = {
    .encode = [](specodec::SpecWriter& w, const ResultMsg& obj) { write_result_msg(w, obj); },
    .decode = [](specodec::SpecReader& r) -> ResultMsg {
        r.beginObject();
        if (!r.hasNextField()) { r.endObject(); throw std::runtime_error("empty union ResultMsg"); }
        auto field_name = r.readFieldName();
        ResultMsg result;
        if (field_name == "ok") { result = r.readString(); }
        else if (field_name == "err") { result = LabelCodec.decode(r); }
        else { throw std::runtime_error("unknown variant for union ResultMsg"); }
        while (r.hasNextField()) { r.readFieldName(); r.skip(); }
        r.endObject();
        return result;
    }
};

export using Tagged = std::variant<std::string, double, bool>;

export inline void write_tagged(specodec::SpecWriter& w, const Tagged& obj) {
    w.beginObject(1);
    std::visit([&w](const auto& val) {
        if constexpr (std::is_same_v<std::decay_t<decltype(val)>, std::string>) { w.writeField("tag"); w.writeString(val);; }
        else if constexpr (std::is_same_v<std::decay_t<decltype(val)>, double>) { w.writeField("score"); w.writeFloat64(val);; }
        else if constexpr (std::is_same_v<std::decay_t<decltype(val)>, bool>) { w.writeField("active"); w.writeBool(val);; }
    }, obj);
    w.endObject();
}

export inline specodec::SpecCodec<Tagged> TaggedCodec = {
    .encode = [](specodec::SpecWriter& w, const Tagged& obj) { write_tagged(w, obj); },
    .decode = [](specodec::SpecReader& r) -> Tagged {
        r.beginObject();
        if (!r.hasNextField()) { r.endObject(); throw std::runtime_error("empty union Tagged"); }
        auto field_name = r.readFieldName();
        Tagged result;
        if (field_name == "tag") { result = r.readString(); }
        else if (field_name == "score") { result = r.readFloat64(); }
        else if (field_name == "active") { result = r.readBool(); }
        else { throw std::runtime_error("unknown variant for union Tagged"); }
        while (r.hasNextField()) { r.readFieldName(); r.skip(); }
        r.endObject();
        return result;
    }
};

export using OptUnionHolder = std::variant<Shape, Ident>;

export inline void write_opt_union_holder(specodec::SpecWriter& w, const OptUnionHolder& obj) {
    w.beginObject(1);
    std::visit([&w](const auto& val) {
        if constexpr (std::is_same_v<std::decay_t<decltype(val)>, Shape>) { w.writeField("shape"); write_shape(w, val);; }
        else if constexpr (std::is_same_v<std::decay_t<decltype(val)>, Ident>) { w.writeField("id"); write_ident(w, val);; }
    }, obj);
    w.endObject();
}

export inline specodec::SpecCodec<OptUnionHolder> OptUnionHolderCodec = {
    .encode = [](specodec::SpecWriter& w, const OptUnionHolder& obj) { write_opt_union_holder(w, obj); },
    .decode = [](specodec::SpecReader& r) -> OptUnionHolder {
        r.beginObject();
        if (!r.hasNextField()) { r.endObject(); throw std::runtime_error("empty union OptUnionHolder"); }
        auto field_name = r.readFieldName();
        OptUnionHolder result;
        if (field_name == "shape") { result = ShapeCodec.decode(r); }
        else if (field_name == "id") { result = IdentCodec.decode(r); }
        else { throw std::runtime_error("unknown variant for union OptUnionHolder"); }
        while (r.hasNextField()) { r.readFieldName(); r.skip(); }
        r.endObject();
        return result;
    }
};

export using MixedUnion = std::variant<Coord, std::string, std::int32_t>;

export inline void write_mixed_union(specodec::SpecWriter& w, const MixedUnion& obj) {
    w.beginObject(1);
    std::visit([&w](const auto& val) {
        if constexpr (std::is_same_v<std::decay_t<decltype(val)>, Coord>) { w.writeField("point"); write_coord(w, val);; }
        else if constexpr (std::is_same_v<std::decay_t<decltype(val)>, std::string>) { w.writeField("label"); w.writeString(val);; }
        else if constexpr (std::is_same_v<std::decay_t<decltype(val)>, std::int32_t>) { w.writeField("count"); w.writeInt32(val);; }
    }, obj);
    w.endObject();
}

export inline specodec::SpecCodec<MixedUnion> MixedUnionCodec = {
    .encode = [](specodec::SpecWriter& w, const MixedUnion& obj) { write_mixed_union(w, obj); },
    .decode = [](specodec::SpecReader& r) -> MixedUnion {
        r.beginObject();
        if (!r.hasNextField()) { r.endObject(); throw std::runtime_error("empty union MixedUnion"); }
        auto field_name = r.readFieldName();
        MixedUnion result;
        if (field_name == "point") { result = CoordCodec.decode(r); }
        else if (field_name == "label") { result = r.readString(); }
        else if (field_name == "count") { result = r.readInt32(); }
        else { throw std::runtime_error("unknown variant for union MixedUnion"); }
        while (r.hasNextField()) { r.readFieldName(); r.skip(); }
        r.endObject();
        return result;
    }
};

export using NestedUnion = std::variant<ResultMsg, Shape>;

export inline void write_nested_union(specodec::SpecWriter& w, const NestedUnion& obj) {
    w.beginObject(1);
    std::visit([&w](const auto& val) {
        if constexpr (std::is_same_v<std::decay_t<decltype(val)>, ResultMsg>) { w.writeField("result"); write_result_msg(w, val);; }
        else if constexpr (std::is_same_v<std::decay_t<decltype(val)>, Shape>) { w.writeField("shape"); write_shape(w, val);; }
    }, obj);
    w.endObject();
}

export inline specodec::SpecCodec<NestedUnion> NestedUnionCodec = {
    .encode = [](specodec::SpecWriter& w, const NestedUnion& obj) { write_nested_union(w, obj); },
    .decode = [](specodec::SpecReader& r) -> NestedUnion {
        r.beginObject();
        if (!r.hasNextField()) { r.endObject(); throw std::runtime_error("empty union NestedUnion"); }
        auto field_name = r.readFieldName();
        NestedUnion result;
        if (field_name == "result") { result = ResultMsgCodec.decode(r); }
        else if (field_name == "shape") { result = ShapeCodec.decode(r); }
        else { throw std::runtime_error("unknown variant for union NestedUnion"); }
        while (r.hasNextField()) { r.readFieldName(); r.skip(); }
        r.endObject();
        return result;
    }
};

export using ScalarUnion = std::variant<std::string, std::int32_t, double, bool>;

export inline void write_scalar_union(specodec::SpecWriter& w, const ScalarUnion& obj) {
    w.beginObject(1);
    std::visit([&w](const auto& val) {
        if constexpr (std::is_same_v<std::decay_t<decltype(val)>, std::string>) { w.writeField("s"); w.writeString(val);; }
        else if constexpr (std::is_same_v<std::decay_t<decltype(val)>, std::int32_t>) { w.writeField("i"); w.writeInt32(val);; }
        else if constexpr (std::is_same_v<std::decay_t<decltype(val)>, double>) { w.writeField("f"); w.writeFloat64(val);; }
        else if constexpr (std::is_same_v<std::decay_t<decltype(val)>, bool>) { w.writeField("b"); w.writeBool(val);; }
    }, obj);
    w.endObject();
}

export inline specodec::SpecCodec<ScalarUnion> ScalarUnionCodec = {
    .encode = [](specodec::SpecWriter& w, const ScalarUnion& obj) { write_scalar_union(w, obj); },
    .decode = [](specodec::SpecReader& r) -> ScalarUnion {
        r.beginObject();
        if (!r.hasNextField()) { r.endObject(); throw std::runtime_error("empty union ScalarUnion"); }
        auto field_name = r.readFieldName();
        ScalarUnion result;
        if (field_name == "s") { result = r.readString(); }
        else if (field_name == "i") { result = r.readInt32(); }
        else if (field_name == "f") { result = r.readFloat64(); }
        else if (field_name == "b") { result = r.readBool(); }
        else { throw std::runtime_error("unknown variant for union ScalarUnion"); }
        while (r.hasNextField()) { r.readFieldName(); r.skip(); }
        r.endObject();
        return result;
    }
};

} // namespace all_types_unions