// Generated by @specodec/typespec-emitter-cpp. DO NOT EDIT.
export module all_types_scalars;
import std;
import specodec;
import all_types;
using namespace all_types;

namespace all_types_scalars {

export struct SingleString {
    std::string v_;
};

export inline void write_single_string(specodec::SpecWriter& w, const SingleString& obj) {
    w.beginObject(1);
    w.writeField("v"); w.writeString(obj.v_);;
    w.endObject();
}

export inline specodec::SpecCodec<SingleString> SingleStringCodec = {
    .encode = [](specodec::SpecWriter& w, const SingleString& obj) { write_single_string(w, obj); },
    .decode = [](specodec::SpecReader& r) -> SingleString {
        std::string fld_v = "";
        r.beginObject();
        while (r.hasNextField()) {
            auto field_name = r.readFieldName();
            if (field_name == "v") { fld_v = r.readString(); }
            else { r.skip(); }
        }
        r.endObject();
        return SingleString{fld_v};
    }
};

export struct SingleBoolean {
    bool v_;
};

export inline void write_single_boolean(specodec::SpecWriter& w, const SingleBoolean& obj) {
    w.beginObject(1);
    w.writeField("v"); w.writeBool(obj.v_);;
    w.endObject();
}

export inline specodec::SpecCodec<SingleBoolean> SingleBooleanCodec = {
    .encode = [](specodec::SpecWriter& w, const SingleBoolean& obj) { write_single_boolean(w, obj); },
    .decode = [](specodec::SpecReader& r) -> SingleBoolean {
        bool fld_v = false;
        r.beginObject();
        while (r.hasNextField()) {
            auto field_name = r.readFieldName();
            if (field_name == "v") { fld_v = r.readBool(); }
            else { r.skip(); }
        }
        r.endObject();
        return SingleBoolean{fld_v};
    }
};

export struct SingleInt8 {
    std::int8_t v_;
};

export inline void write_single_int8(specodec::SpecWriter& w, const SingleInt8& obj) {
    w.beginObject(1);
    w.writeField("v"); w.writeInt32(static_cast<std::int32_t>(obj.v_));;
    w.endObject();
}

export inline specodec::SpecCodec<SingleInt8> SingleInt8Codec = {
    .encode = [](specodec::SpecWriter& w, const SingleInt8& obj) { write_single_int8(w, obj); },
    .decode = [](specodec::SpecReader& r) -> SingleInt8 {
        std::int8_t fld_v = 0;
        r.beginObject();
        while (r.hasNextField()) {
            auto field_name = r.readFieldName();
            if (field_name == "v") { fld_v = static_cast<std::int8_t>(r.readInt32()); }
            else { r.skip(); }
        }
        r.endObject();
        return SingleInt8{fld_v};
    }
};

export struct SingleInt16 {
    std::int16_t v_;
};

export inline void write_single_int16(specodec::SpecWriter& w, const SingleInt16& obj) {
    w.beginObject(1);
    w.writeField("v"); w.writeInt32(static_cast<std::int32_t>(obj.v_));;
    w.endObject();
}

export inline specodec::SpecCodec<SingleInt16> SingleInt16Codec = {
    .encode = [](specodec::SpecWriter& w, const SingleInt16& obj) { write_single_int16(w, obj); },
    .decode = [](specodec::SpecReader& r) -> SingleInt16 {
        std::int16_t fld_v = 0;
        r.beginObject();
        while (r.hasNextField()) {
            auto field_name = r.readFieldName();
            if (field_name == "v") { fld_v = static_cast<std::int16_t>(r.readInt32()); }
            else { r.skip(); }
        }
        r.endObject();
        return SingleInt16{fld_v};
    }
};

export struct SingleInt32 {
    std::int32_t v_;
};

export inline void write_single_int32(specodec::SpecWriter& w, const SingleInt32& obj) {
    w.beginObject(1);
    w.writeField("v"); w.writeInt32(obj.v_);;
    w.endObject();
}

export inline specodec::SpecCodec<SingleInt32> SingleInt32Codec = {
    .encode = [](specodec::SpecWriter& w, const SingleInt32& obj) { write_single_int32(w, obj); },
    .decode = [](specodec::SpecReader& r) -> SingleInt32 {
        std::int32_t fld_v = 0;
        r.beginObject();
        while (r.hasNextField()) {
            auto field_name = r.readFieldName();
            if (field_name == "v") { fld_v = r.readInt32(); }
            else { r.skip(); }
        }
        r.endObject();
        return SingleInt32{fld_v};
    }
};

export struct SingleInt64 {
    std::int64_t v_;
};

export inline void write_single_int64(specodec::SpecWriter& w, const SingleInt64& obj) {
    w.beginObject(1);
    w.writeField("v"); w.writeInt64(obj.v_);;
    w.endObject();
}

export inline specodec::SpecCodec<SingleInt64> SingleInt64Codec = {
    .encode = [](specodec::SpecWriter& w, const SingleInt64& obj) { write_single_int64(w, obj); },
    .decode = [](specodec::SpecReader& r) -> SingleInt64 {
        std::int64_t fld_v = 0LL;
        r.beginObject();
        while (r.hasNextField()) {
            auto field_name = r.readFieldName();
            if (field_name == "v") { fld_v = r.readInt64(); }
            else { r.skip(); }
        }
        r.endObject();
        return SingleInt64{fld_v};
    }
};

export struct SingleUint8 {
    std::uint8_t v_;
};

export inline void write_single_uint8(specodec::SpecWriter& w, const SingleUint8& obj) {
    w.beginObject(1);
    w.writeField("v"); w.writeUint32(static_cast<std::uint32_t>(obj.v_));;
    w.endObject();
}

export inline specodec::SpecCodec<SingleUint8> SingleUint8Codec = {
    .encode = [](specodec::SpecWriter& w, const SingleUint8& obj) { write_single_uint8(w, obj); },
    .decode = [](specodec::SpecReader& r) -> SingleUint8 {
        std::uint8_t fld_v = 0u;
        r.beginObject();
        while (r.hasNextField()) {
            auto field_name = r.readFieldName();
            if (field_name == "v") { fld_v = static_cast<std::uint8_t>(r.readUint32()); }
            else { r.skip(); }
        }
        r.endObject();
        return SingleUint8{fld_v};
    }
};

export struct SingleUint16 {
    std::uint16_t v_;
};

export inline void write_single_uint16(specodec::SpecWriter& w, const SingleUint16& obj) {
    w.beginObject(1);
    w.writeField("v"); w.writeUint32(static_cast<std::uint32_t>(obj.v_));;
    w.endObject();
}

export inline specodec::SpecCodec<SingleUint16> SingleUint16Codec = {
    .encode = [](specodec::SpecWriter& w, const SingleUint16& obj) { write_single_uint16(w, obj); },
    .decode = [](specodec::SpecReader& r) -> SingleUint16 {
        std::uint16_t fld_v = 0u;
        r.beginObject();
        while (r.hasNextField()) {
            auto field_name = r.readFieldName();
            if (field_name == "v") { fld_v = static_cast<std::uint16_t>(r.readUint32()); }
            else { r.skip(); }
        }
        r.endObject();
        return SingleUint16{fld_v};
    }
};

export struct SingleUint32 {
    std::uint32_t v_;
};

export inline void write_single_uint32(specodec::SpecWriter& w, const SingleUint32& obj) {
    w.beginObject(1);
    w.writeField("v"); w.writeUint32(obj.v_);;
    w.endObject();
}

export inline specodec::SpecCodec<SingleUint32> SingleUint32Codec = {
    .encode = [](specodec::SpecWriter& w, const SingleUint32& obj) { write_single_uint32(w, obj); },
    .decode = [](specodec::SpecReader& r) -> SingleUint32 {
        std::uint32_t fld_v = 0u;
        r.beginObject();
        while (r.hasNextField()) {
            auto field_name = r.readFieldName();
            if (field_name == "v") { fld_v = r.readUint32(); }
            else { r.skip(); }
        }
        r.endObject();
        return SingleUint32{fld_v};
    }
};

export struct SingleUint64 {
    std::uint64_t v_;
};

export inline void write_single_uint64(specodec::SpecWriter& w, const SingleUint64& obj) {
    w.beginObject(1);
    w.writeField("v"); w.writeUint64(obj.v_);;
    w.endObject();
}

export inline specodec::SpecCodec<SingleUint64> SingleUint64Codec = {
    .encode = [](specodec::SpecWriter& w, const SingleUint64& obj) { write_single_uint64(w, obj); },
    .decode = [](specodec::SpecReader& r) -> SingleUint64 {
        std::uint64_t fld_v = 0ULL;
        r.beginObject();
        while (r.hasNextField()) {
            auto field_name = r.readFieldName();
            if (field_name == "v") { fld_v = r.readUint64(); }
            else { r.skip(); }
        }
        r.endObject();
        return SingleUint64{fld_v};
    }
};

export struct SingleFloat32 {
    float v_;
};

export inline void write_single_float32(specodec::SpecWriter& w, const SingleFloat32& obj) {
    w.beginObject(1);
    w.writeField("v"); w.writeFloat32(obj.v_);;
    w.endObject();
}

export inline specodec::SpecCodec<SingleFloat32> SingleFloat32Codec = {
    .encode = [](specodec::SpecWriter& w, const SingleFloat32& obj) { write_single_float32(w, obj); },
    .decode = [](specodec::SpecReader& r) -> SingleFloat32 {
        float fld_v = 0.0f;
        r.beginObject();
        while (r.hasNextField()) {
            auto field_name = r.readFieldName();
            if (field_name == "v") { fld_v = r.readFloat32(); }
            else { r.skip(); }
        }
        r.endObject();
        return SingleFloat32{fld_v};
    }
};

export struct SingleFloat64 {
    double v_;
};

export inline void write_single_float64(specodec::SpecWriter& w, const SingleFloat64& obj) {
    w.beginObject(1);
    w.writeField("v"); w.writeFloat64(obj.v_);;
    w.endObject();
}

export inline specodec::SpecCodec<SingleFloat64> SingleFloat64Codec = {
    .encode = [](specodec::SpecWriter& w, const SingleFloat64& obj) { write_single_float64(w, obj); },
    .decode = [](specodec::SpecReader& r) -> SingleFloat64 {
        double fld_v = 0.0;
        r.beginObject();
        while (r.hasNextField()) {
            auto field_name = r.readFieldName();
            if (field_name == "v") { fld_v = r.readFloat64(); }
            else { r.skip(); }
        }
        r.endObject();
        return SingleFloat64{fld_v};
    }
};

export struct SingleBytes {
    std::vector<std::uint8_t> v_;
};

export inline void write_single_bytes(specodec::SpecWriter& w, const SingleBytes& obj) {
    w.beginObject(1);
    w.writeField("v"); w.writeBytes(obj.v_);;
    w.endObject();
}

export inline specodec::SpecCodec<SingleBytes> SingleBytesCodec = {
    .encode = [](specodec::SpecWriter& w, const SingleBytes& obj) { write_single_bytes(w, obj); },
    .decode = [](specodec::SpecReader& r) -> SingleBytes {
        std::vector<std::uint8_t> fld_v = {};
        r.beginObject();
        while (r.hasNextField()) {
            auto field_name = r.readFieldName();
            if (field_name == "v") { fld_v = r.readBytes(); }
            else { r.skip(); }
        }
        r.endObject();
        return SingleBytes{fld_v};
    }
};

} // namespace all_types_scalars