// Generated by @specodec/typespec-emitter-cpp. DO NOT EDIT.
export module all_types_arrays;
import std;
import specodec;
import all_types;
using namespace all_types;

namespace all_types_arrays {

export struct ArrString {
    std::vector<std::string> items;
};

export inline void write_arr_string(specodec::SpecWriter& w, const ArrString& obj) {
    w.beginObject(1);
    w.writeField("items"); 
        w.beginArray(obj.items.size());
        for (const auto& elem : obj.items) { w.nextElement(); w.writeString(elem); }
        w.endArray();
    w.endObject();
}

export inline specodec::SpecCodec<ArrString> ArrStringCodec = {
    .encode = [](specodec::SpecWriter& w, const ArrString& obj) { write_arr_string(w, obj); },
    .decode = [](specodec::SpecReader& r) -> ArrString {
        std::vector<std::string> fld_items = {};
        r.beginObject();
        while (r.hasNextField()) {
            auto field_name = r.readFieldName();
            if (field_name == "items") { fld_items = [&]() {
    std::vector<std::string> result;
    r.beginArray();
    while (r.hasNextElement()) { result.push_back(r.readString()); }
    r.endArray();
    return result;
}(); }
            else { r.skip(); }
        }
        r.endObject();
        return ArrString{fld_items};
    }
};

export struct ArrInt32 {
    std::vector<std::int32_t> items;
};

export inline void write_arr_int32(specodec::SpecWriter& w, const ArrInt32& obj) {
    w.beginObject(1);
    w.writeField("items"); 
        w.beginArray(obj.items.size());
        for (const auto& elem : obj.items) { w.nextElement(); w.writeInt32(elem); }
        w.endArray();
    w.endObject();
}

export inline specodec::SpecCodec<ArrInt32> ArrInt32Codec = {
    .encode = [](specodec::SpecWriter& w, const ArrInt32& obj) { write_arr_int32(w, obj); },
    .decode = [](specodec::SpecReader& r) -> ArrInt32 {
        std::vector<std::int32_t> fld_items = {};
        r.beginObject();
        while (r.hasNextField()) {
            auto field_name = r.readFieldName();
            if (field_name == "items") { fld_items = [&]() {
    std::vector<std::int32_t> result;
    r.beginArray();
    while (r.hasNextElement()) { result.push_back(r.readInt32()); }
    r.endArray();
    return result;
}(); }
            else { r.skip(); }
        }
        r.endObject();
        return ArrInt32{fld_items};
    }
};

export struct ArrBoolean {
    std::vector<bool> items;
};

export inline void write_arr_boolean(specodec::SpecWriter& w, const ArrBoolean& obj) {
    w.beginObject(1);
    w.writeField("items"); 
        w.beginArray(obj.items.size());
        for (const auto& elem : obj.items) { w.nextElement(); w.writeBool(elem); }
        w.endArray();
    w.endObject();
}

export inline specodec::SpecCodec<ArrBoolean> ArrBooleanCodec = {
    .encode = [](specodec::SpecWriter& w, const ArrBoolean& obj) { write_arr_boolean(w, obj); },
    .decode = [](specodec::SpecReader& r) -> ArrBoolean {
        std::vector<bool> fld_items = {};
        r.beginObject();
        while (r.hasNextField()) {
            auto field_name = r.readFieldName();
            if (field_name == "items") { fld_items = [&]() {
    std::vector<bool> result;
    r.beginArray();
    while (r.hasNextElement()) { result.push_back(r.readBool()); }
    r.endArray();
    return result;
}(); }
            else { r.skip(); }
        }
        r.endObject();
        return ArrBoolean{fld_items};
    }
};

export struct ArrFloat64 {
    std::vector<double> items;
};

export inline void write_arr_float64(specodec::SpecWriter& w, const ArrFloat64& obj) {
    w.beginObject(1);
    w.writeField("items"); 
        w.beginArray(obj.items.size());
        for (const auto& elem : obj.items) { w.nextElement(); w.writeFloat64(elem); }
        w.endArray();
    w.endObject();
}

export inline specodec::SpecCodec<ArrFloat64> ArrFloat64Codec = {
    .encode = [](specodec::SpecWriter& w, const ArrFloat64& obj) { write_arr_float64(w, obj); },
    .decode = [](specodec::SpecReader& r) -> ArrFloat64 {
        std::vector<double> fld_items = {};
        r.beginObject();
        while (r.hasNextField()) {
            auto field_name = r.readFieldName();
            if (field_name == "items") { fld_items = [&]() {
    std::vector<double> result;
    r.beginArray();
    while (r.hasNextElement()) { result.push_back(r.readFloat64()); }
    r.endArray();
    return result;
}(); }
            else { r.skip(); }
        }
        r.endObject();
        return ArrFloat64{fld_items};
    }
};

export struct ArrBytes {
    std::vector<std::vector<std::uint8_t>> items;
};

export inline void write_arr_bytes(specodec::SpecWriter& w, const ArrBytes& obj) {
    w.beginObject(1);
    w.writeField("items"); 
        w.beginArray(obj.items.size());
        for (const auto& elem : obj.items) { w.nextElement(); w.writeBytes(elem); }
        w.endArray();
    w.endObject();
}

export inline specodec::SpecCodec<ArrBytes> ArrBytesCodec = {
    .encode = [](specodec::SpecWriter& w, const ArrBytes& obj) { write_arr_bytes(w, obj); },
    .decode = [](specodec::SpecReader& r) -> ArrBytes {
        std::vector<std::vector<std::uint8_t>> fld_items = {};
        r.beginObject();
        while (r.hasNextField()) {
            auto field_name = r.readFieldName();
            if (field_name == "items") { fld_items = [&]() {
    std::vector<std::vector<std::uint8_t>> result;
    r.beginArray();
    while (r.hasNextElement()) { result.push_back(r.readBytes()); }
    r.endArray();
    return result;
}(); }
            else { r.skip(); }
        }
        r.endObject();
        return ArrBytes{fld_items};
    }
};

export struct ArrInt64 {
    std::vector<std::int64_t> items;
};

export inline void write_arr_int64(specodec::SpecWriter& w, const ArrInt64& obj) {
    w.beginObject(1);
    w.writeField("items"); 
        w.beginArray(obj.items.size());
        for (const auto& elem : obj.items) { w.nextElement(); w.writeInt64(elem); }
        w.endArray();
    w.endObject();
}

export inline specodec::SpecCodec<ArrInt64> ArrInt64Codec = {
    .encode = [](specodec::SpecWriter& w, const ArrInt64& obj) { write_arr_int64(w, obj); },
    .decode = [](specodec::SpecReader& r) -> ArrInt64 {
        std::vector<std::int64_t> fld_items = {};
        r.beginObject();
        while (r.hasNextField()) {
            auto field_name = r.readFieldName();
            if (field_name == "items") { fld_items = [&]() {
    std::vector<std::int64_t> result;
    r.beginArray();
    while (r.hasNextElement()) { result.push_back(r.readInt64()); }
    r.endArray();
    return result;
}(); }
            else { r.skip(); }
        }
        r.endObject();
        return ArrInt64{fld_items};
    }
};

export struct ArrUint64 {
    std::vector<std::uint64_t> items;
};

export inline void write_arr_uint64(specodec::SpecWriter& w, const ArrUint64& obj) {
    w.beginObject(1);
    w.writeField("items"); 
        w.beginArray(obj.items.size());
        for (const auto& elem : obj.items) { w.nextElement(); w.writeUint64(elem); }
        w.endArray();
    w.endObject();
}

export inline specodec::SpecCodec<ArrUint64> ArrUint64Codec = {
    .encode = [](specodec::SpecWriter& w, const ArrUint64& obj) { write_arr_uint64(w, obj); },
    .decode = [](specodec::SpecReader& r) -> ArrUint64 {
        std::vector<std::uint64_t> fld_items = {};
        r.beginObject();
        while (r.hasNextField()) {
            auto field_name = r.readFieldName();
            if (field_name == "items") { fld_items = [&]() {
    std::vector<std::uint64_t> result;
    r.beginArray();
    while (r.hasNextElement()) { result.push_back(r.readUint64()); }
    r.endArray();
    return result;
}(); }
            else { r.skip(); }
        }
        r.endObject();
        return ArrUint64{fld_items};
    }
};

export struct MultiArr1 {
    std::vector<std::string> names;
    std::vector<std::int32_t> scores;
};

export inline void write_multi_arr1(specodec::SpecWriter& w, const MultiArr1& obj) {
    w.beginObject(2);
    w.writeField("names"); 
        w.beginArray(obj.names.size());
        for (const auto& elem : obj.names) { w.nextElement(); w.writeString(elem); }
        w.endArray();
    w.writeField("scores"); 
        w.beginArray(obj.scores.size());
        for (const auto& elem : obj.scores) { w.nextElement(); w.writeInt32(elem); }
        w.endArray();
    w.endObject();
}

export inline specodec::SpecCodec<MultiArr1> MultiArr1Codec = {
    .encode = [](specodec::SpecWriter& w, const MultiArr1& obj) { write_multi_arr1(w, obj); },
    .decode = [](specodec::SpecReader& r) -> MultiArr1 {
        std::vector<std::string> fld_names = {};
        std::vector<std::int32_t> fld_scores = {};
        r.beginObject();
        while (r.hasNextField()) {
            auto field_name = r.readFieldName();
            if (field_name == "names") { fld_names = [&]() {
    std::vector<std::string> result;
    r.beginArray();
    while (r.hasNextElement()) { result.push_back(r.readString()); }
    r.endArray();
    return result;
}(); }
            else if (field_name == "scores") { fld_scores = [&]() {
    std::vector<std::int32_t> result;
    r.beginArray();
    while (r.hasNextElement()) { result.push_back(r.readInt32()); }
    r.endArray();
    return result;
}(); }
            else { r.skip(); }
        }
        r.endObject();
        return MultiArr1{fld_names, fld_scores};
    }
};

export struct MultiArr2 {
    std::vector<bool> flags;
    std::vector<double> values;
    std::vector<std::vector<std::uint8_t>> payload;
};

export inline void write_multi_arr2(specodec::SpecWriter& w, const MultiArr2& obj) {
    w.beginObject(3);
    w.writeField("flags"); 
        w.beginArray(obj.flags.size());
        for (const auto& elem : obj.flags) { w.nextElement(); w.writeBool(elem); }
        w.endArray();
    w.writeField("values"); 
        w.beginArray(obj.values.size());
        for (const auto& elem : obj.values) { w.nextElement(); w.writeFloat64(elem); }
        w.endArray();
    w.writeField("payload"); 
        w.beginArray(obj.payload.size());
        for (const auto& elem : obj.payload) { w.nextElement(); w.writeBytes(elem); }
        w.endArray();
    w.endObject();
}

export inline specodec::SpecCodec<MultiArr2> MultiArr2Codec = {
    .encode = [](specodec::SpecWriter& w, const MultiArr2& obj) { write_multi_arr2(w, obj); },
    .decode = [](specodec::SpecReader& r) -> MultiArr2 {
        std::vector<bool> fld_flags = {};
        std::vector<double> fld_values = {};
        std::vector<std::vector<std::uint8_t>> fld_payload = {};
        r.beginObject();
        while (r.hasNextField()) {
            auto field_name = r.readFieldName();
            if (field_name == "flags") { fld_flags = [&]() {
    std::vector<bool> result;
    r.beginArray();
    while (r.hasNextElement()) { result.push_back(r.readBool()); }
    r.endArray();
    return result;
}(); }
            else if (field_name == "values") { fld_values = [&]() {
    std::vector<double> result;
    r.beginArray();
    while (r.hasNextElement()) { result.push_back(r.readFloat64()); }
    r.endArray();
    return result;
}(); }
            else if (field_name == "payload") { fld_payload = [&]() {
    std::vector<std::vector<std::uint8_t>> result;
    r.beginArray();
    while (r.hasNextElement()) { result.push_back(r.readBytes()); }
    r.endArray();
    return result;
}(); }
            else { r.skip(); }
        }
        r.endObject();
        return MultiArr2{fld_flags, fld_values, fld_payload};
    }
};

export struct MultiArr3 {
    std::vector<std::string> a;
    std::vector<std::int32_t> b;
    std::vector<double> c;
};

export inline void write_multi_arr3(specodec::SpecWriter& w, const MultiArr3& obj) {
    w.beginObject(3);
    w.writeField("a"); 
        w.beginArray(obj.a.size());
        for (const auto& elem : obj.a) { w.nextElement(); w.writeString(elem); }
        w.endArray();
    w.writeField("b"); 
        w.beginArray(obj.b.size());
        for (const auto& elem : obj.b) { w.nextElement(); w.writeInt32(elem); }
        w.endArray();
    w.writeField("c"); 
        w.beginArray(obj.c.size());
        for (const auto& elem : obj.c) { w.nextElement(); w.writeFloat64(elem); }
        w.endArray();
    w.endObject();
}

export inline specodec::SpecCodec<MultiArr3> MultiArr3Codec = {
    .encode = [](specodec::SpecWriter& w, const MultiArr3& obj) { write_multi_arr3(w, obj); },
    .decode = [](specodec::SpecReader& r) -> MultiArr3 {
        std::vector<std::string> fld_a = {};
        std::vector<std::int32_t> fld_b = {};
        std::vector<double> fld_c = {};
        r.beginObject();
        while (r.hasNextField()) {
            auto field_name = r.readFieldName();
            if (field_name == "a") { fld_a = [&]() {
    std::vector<std::string> result;
    r.beginArray();
    while (r.hasNextElement()) { result.push_back(r.readString()); }
    r.endArray();
    return result;
}(); }
            else if (field_name == "b") { fld_b = [&]() {
    std::vector<std::int32_t> result;
    r.beginArray();
    while (r.hasNextElement()) { result.push_back(r.readInt32()); }
    r.endArray();
    return result;
}(); }
            else if (field_name == "c") { fld_c = [&]() {
    std::vector<double> result;
    r.beginArray();
    while (r.hasNextElement()) { result.push_back(r.readFloat64()); }
    r.endArray();
    return result;
}(); }
            else { r.skip(); }
        }
        r.endObject();
        return MultiArr3{fld_a, fld_b, fld_c};
    }
};

export struct MultiArr4 {
    std::vector<std::int64_t> ids;
    std::vector<std::string> tags;
};

export inline void write_multi_arr4(specodec::SpecWriter& w, const MultiArr4& obj) {
    w.beginObject(2);
    w.writeField("ids"); 
        w.beginArray(obj.ids.size());
        for (const auto& elem : obj.ids) { w.nextElement(); w.writeInt64(elem); }
        w.endArray();
    w.writeField("tags"); 
        w.beginArray(obj.tags.size());
        for (const auto& elem : obj.tags) { w.nextElement(); w.writeString(elem); }
        w.endArray();
    w.endObject();
}

export inline specodec::SpecCodec<MultiArr4> MultiArr4Codec = {
    .encode = [](specodec::SpecWriter& w, const MultiArr4& obj) { write_multi_arr4(w, obj); },
    .decode = [](specodec::SpecReader& r) -> MultiArr4 {
        std::vector<std::int64_t> fld_ids = {};
        std::vector<std::string> fld_tags = {};
        r.beginObject();
        while (r.hasNextField()) {
            auto field_name = r.readFieldName();
            if (field_name == "ids") { fld_ids = [&]() {
    std::vector<std::int64_t> result;
    r.beginArray();
    while (r.hasNextElement()) { result.push_back(r.readInt64()); }
    r.endArray();
    return result;
}(); }
            else if (field_name == "tags") { fld_tags = [&]() {
    std::vector<std::string> result;
    r.beginArray();
    while (r.hasNextElement()) { result.push_back(r.readString()); }
    r.endArray();
    return result;
}(); }
            else { r.skip(); }
        }
        r.endObject();
        return MultiArr4{fld_ids, fld_tags};
    }
};

export struct MultiArr5 {
    std::vector<std::uint64_t> xs;
    std::vector<float> ys;
    std::vector<bool> zs;
};

export inline void write_multi_arr5(specodec::SpecWriter& w, const MultiArr5& obj) {
    w.beginObject(3);
    w.writeField("xs"); 
        w.beginArray(obj.xs.size());
        for (const auto& elem : obj.xs) { w.nextElement(); w.writeUint64(elem); }
        w.endArray();
    w.writeField("ys"); 
        w.beginArray(obj.ys.size());
        for (const auto& elem : obj.ys) { w.nextElement(); w.writeFloat32(elem); }
        w.endArray();
    w.writeField("zs"); 
        w.beginArray(obj.zs.size());
        for (const auto& elem : obj.zs) { w.nextElement(); w.writeBool(elem); }
        w.endArray();
    w.endObject();
}

export inline specodec::SpecCodec<MultiArr5> MultiArr5Codec = {
    .encode = [](specodec::SpecWriter& w, const MultiArr5& obj) { write_multi_arr5(w, obj); },
    .decode = [](specodec::SpecReader& r) -> MultiArr5 {
        std::vector<std::uint64_t> fld_xs = {};
        std::vector<float> fld_ys = {};
        std::vector<bool> fld_zs = {};
        r.beginObject();
        while (r.hasNextField()) {
            auto field_name = r.readFieldName();
            if (field_name == "xs") { fld_xs = [&]() {
    std::vector<std::uint64_t> result;
    r.beginArray();
    while (r.hasNextElement()) { result.push_back(r.readUint64()); }
    r.endArray();
    return result;
}(); }
            else if (field_name == "ys") { fld_ys = [&]() {
    std::vector<float> result;
    r.beginArray();
    while (r.hasNextElement()) { result.push_back(r.readFloat32()); }
    r.endArray();
    return result;
}(); }
            else if (field_name == "zs") { fld_zs = [&]() {
    std::vector<bool> result;
    r.beginArray();
    while (r.hasNextElement()) { result.push_back(r.readBool()); }
    r.endArray();
    return result;
}(); }
            else { r.skip(); }
        }
        r.endObject();
        return MultiArr5{fld_xs, fld_ys, fld_zs};
    }
};

export struct OptCombo1 {
    std::string req;
    std::optional<std::int32_t> opt_a;
};

export inline void write_opt_combo1(specodec::SpecWriter& w, const OptCombo1& obj) {
    int field_count = 1;
    if (obj.opt_a.has_value()) field_count++;
    w.beginObject(field_count);
    w.writeField("req"); w.writeString(obj.req);;
    if (obj.opt_a.has_value()) { w.writeField("opt_a"); w.writeInt32(obj.opt_a.value());; }
    w.endObject();
}

export inline specodec::SpecCodec<OptCombo1> OptCombo1Codec = {
    .encode = [](specodec::SpecWriter& w, const OptCombo1& obj) { write_opt_combo1(w, obj); },
    .decode = [](specodec::SpecReader& r) -> OptCombo1 {
        std::string fld_req = "";
        std::optional<std::int32_t> fld_opt_a;
        r.beginObject();
        while (r.hasNextField()) {
            auto field_name = r.readFieldName();
            if (field_name == "req") { fld_req = r.readString(); }
            else if (field_name == "opt_a") { fld_opt_a = std::optional<std::int32_t>{r.readInt32()}; }
            else { r.skip(); }
        }
        r.endObject();
        return OptCombo1{fld_req, fld_opt_a};
    }
};

export struct OptCombo2 {
    std::string req;
    std::optional<std::int32_t> opt_a;
    std::optional<bool> opt_b;
};

export inline void write_opt_combo2(specodec::SpecWriter& w, const OptCombo2& obj) {
    int field_count = 1;
    if (obj.opt_a.has_value()) field_count++;
    if (obj.opt_b.has_value()) field_count++;
    w.beginObject(field_count);
    w.writeField("req"); w.writeString(obj.req);;
    if (obj.opt_a.has_value()) { w.writeField("opt_a"); w.writeInt32(obj.opt_a.value());; }
    if (obj.opt_b.has_value()) { w.writeField("opt_b"); w.writeBool(obj.opt_b.value());; }
    w.endObject();
}

export inline specodec::SpecCodec<OptCombo2> OptCombo2Codec = {
    .encode = [](specodec::SpecWriter& w, const OptCombo2& obj) { write_opt_combo2(w, obj); },
    .decode = [](specodec::SpecReader& r) -> OptCombo2 {
        std::string fld_req = "";
        std::optional<std::int32_t> fld_opt_a;
        std::optional<bool> fld_opt_b;
        r.beginObject();
        while (r.hasNextField()) {
            auto field_name = r.readFieldName();
            if (field_name == "req") { fld_req = r.readString(); }
            else if (field_name == "opt_a") { fld_opt_a = std::optional<std::int32_t>{r.readInt32()}; }
            else if (field_name == "opt_b") { fld_opt_b = std::optional<bool>{r.readBool()}; }
            else { r.skip(); }
        }
        r.endObject();
        return OptCombo2{fld_req, fld_opt_a, fld_opt_b};
    }
};

export struct OptCombo3 {
    std::string req;
    std::optional<std::int32_t> opt_a;
    std::optional<bool> opt_b;
    std::optional<double> opt_c;
};

export inline void write_opt_combo3(specodec::SpecWriter& w, const OptCombo3& obj) {
    int field_count = 1;
    if (obj.opt_a.has_value()) field_count++;
    if (obj.opt_b.has_value()) field_count++;
    if (obj.opt_c.has_value()) field_count++;
    w.beginObject(field_count);
    w.writeField("req"); w.writeString(obj.req);;
    if (obj.opt_a.has_value()) { w.writeField("opt_a"); w.writeInt32(obj.opt_a.value());; }
    if (obj.opt_b.has_value()) { w.writeField("opt_b"); w.writeBool(obj.opt_b.value());; }
    if (obj.opt_c.has_value()) { w.writeField("opt_c"); w.writeFloat64(obj.opt_c.value());; }
    w.endObject();
}

export inline specodec::SpecCodec<OptCombo3> OptCombo3Codec = {
    .encode = [](specodec::SpecWriter& w, const OptCombo3& obj) { write_opt_combo3(w, obj); },
    .decode = [](specodec::SpecReader& r) -> OptCombo3 {
        std::string fld_req = "";
        std::optional<std::int32_t> fld_opt_a;
        std::optional<bool> fld_opt_b;
        std::optional<double> fld_opt_c;
        r.beginObject();
        while (r.hasNextField()) {
            auto field_name = r.readFieldName();
            if (field_name == "req") { fld_req = r.readString(); }
            else if (field_name == "opt_a") { fld_opt_a = std::optional<std::int32_t>{r.readInt32()}; }
            else if (field_name == "opt_b") { fld_opt_b = std::optional<bool>{r.readBool()}; }
            else if (field_name == "opt_c") { fld_opt_c = std::optional<double>{r.readFloat64()}; }
            else { r.skip(); }
        }
        r.endObject();
        return OptCombo3{fld_req, fld_opt_a, fld_opt_b, fld_opt_c};
    }
};

export struct OptCombo4 {
    std::int32_t req;
    std::optional<std::string> opt_a;
    std::optional<std::vector<std::uint8_t>> opt_b;
};

export inline void write_opt_combo4(specodec::SpecWriter& w, const OptCombo4& obj) {
    int field_count = 1;
    if (obj.opt_a.has_value()) field_count++;
    if (obj.opt_b.has_value()) field_count++;
    w.beginObject(field_count);
    w.writeField("req"); w.writeInt32(obj.req);;
    if (obj.opt_a.has_value()) { w.writeField("opt_a"); w.writeString(obj.opt_a.value());; }
    if (obj.opt_b.has_value()) { w.writeField("opt_b"); w.writeBytes(obj.opt_b.value());; }
    w.endObject();
}

export inline specodec::SpecCodec<OptCombo4> OptCombo4Codec = {
    .encode = [](specodec::SpecWriter& w, const OptCombo4& obj) { write_opt_combo4(w, obj); },
    .decode = [](specodec::SpecReader& r) -> OptCombo4 {
        std::int32_t fld_req = 0;
        std::optional<std::string> fld_opt_a;
        std::optional<std::vector<std::uint8_t>> fld_opt_b;
        r.beginObject();
        while (r.hasNextField()) {
            auto field_name = r.readFieldName();
            if (field_name == "req") { fld_req = r.readInt32(); }
            else if (field_name == "opt_a") { fld_opt_a = std::optional<std::string>{r.readString()}; }
            else if (field_name == "opt_b") { fld_opt_b = std::optional<std::vector<std::uint8_t>>{r.readBytes()}; }
            else { r.skip(); }
        }
        r.endObject();
        return OptCombo4{fld_req, fld_opt_a, fld_opt_b};
    }
};

export struct OptCombo5 {
    std::string req1;
    std::int32_t req2;
    std::optional<bool> opt_a;
    std::optional<double> opt_b;
};

export inline void write_opt_combo5(specodec::SpecWriter& w, const OptCombo5& obj) {
    int field_count = 2;
    if (obj.opt_a.has_value()) field_count++;
    if (obj.opt_b.has_value()) field_count++;
    w.beginObject(field_count);
    w.writeField("req1"); w.writeString(obj.req1);;
    w.writeField("req2"); w.writeInt32(obj.req2);;
    if (obj.opt_a.has_value()) { w.writeField("opt_a"); w.writeBool(obj.opt_a.value());; }
    if (obj.opt_b.has_value()) { w.writeField("opt_b"); w.writeFloat64(obj.opt_b.value());; }
    w.endObject();
}

export inline specodec::SpecCodec<OptCombo5> OptCombo5Codec = {
    .encode = [](specodec::SpecWriter& w, const OptCombo5& obj) { write_opt_combo5(w, obj); },
    .decode = [](specodec::SpecReader& r) -> OptCombo5 {
        std::string fld_req1 = "";
        std::int32_t fld_req2 = 0;
        std::optional<bool> fld_opt_a;
        std::optional<double> fld_opt_b;
        r.beginObject();
        while (r.hasNextField()) {
            auto field_name = r.readFieldName();
            if (field_name == "req1") { fld_req1 = r.readString(); }
            else if (field_name == "req2") { fld_req2 = r.readInt32(); }
            else if (field_name == "opt_a") { fld_opt_a = std::optional<bool>{r.readBool()}; }
            else if (field_name == "opt_b") { fld_opt_b = std::optional<double>{r.readFloat64()}; }
            else { r.skip(); }
        }
        r.endObject();
        return OptCombo5{fld_req1, fld_req2, fld_opt_a, fld_opt_b};
    }
};

export struct OptCombo6 {
    std::string req;
    std::optional<std::string> opt_s;
    std::optional<std::int32_t> opt_i;
    std::optional<double> opt_f;
    std::optional<std::vector<std::uint8_t>> opt_b;
};

export inline void write_opt_combo6(specodec::SpecWriter& w, const OptCombo6& obj) {
    int field_count = 1;
    if (obj.opt_s.has_value()) field_count++;
    if (obj.opt_i.has_value()) field_count++;
    if (obj.opt_f.has_value()) field_count++;
    if (obj.opt_b.has_value()) field_count++;
    w.beginObject(field_count);
    w.writeField("req"); w.writeString(obj.req);;
    if (obj.opt_s.has_value()) { w.writeField("opt_s"); w.writeString(obj.opt_s.value());; }
    if (obj.opt_i.has_value()) { w.writeField("opt_i"); w.writeInt32(obj.opt_i.value());; }
    if (obj.opt_f.has_value()) { w.writeField("opt_f"); w.writeFloat64(obj.opt_f.value());; }
    if (obj.opt_b.has_value()) { w.writeField("opt_b"); w.writeBytes(obj.opt_b.value());; }
    w.endObject();
}

export inline specodec::SpecCodec<OptCombo6> OptCombo6Codec = {
    .encode = [](specodec::SpecWriter& w, const OptCombo6& obj) { write_opt_combo6(w, obj); },
    .decode = [](specodec::SpecReader& r) -> OptCombo6 {
        std::string fld_req = "";
        std::optional<std::string> fld_opt_s;
        std::optional<std::int32_t> fld_opt_i;
        std::optional<double> fld_opt_f;
        std::optional<std::vector<std::uint8_t>> fld_opt_b;
        r.beginObject();
        while (r.hasNextField()) {
            auto field_name = r.readFieldName();
            if (field_name == "req") { fld_req = r.readString(); }
            else if (field_name == "opt_s") { fld_opt_s = std::optional<std::string>{r.readString()}; }
            else if (field_name == "opt_i") { fld_opt_i = std::optional<std::int32_t>{r.readInt32()}; }
            else if (field_name == "opt_f") { fld_opt_f = std::optional<double>{r.readFloat64()}; }
            else if (field_name == "opt_b") { fld_opt_b = std::optional<std::vector<std::uint8_t>>{r.readBytes()}; }
            else { r.skip(); }
        }
        r.endObject();
        return OptCombo6{fld_req, fld_opt_s, fld_opt_i, fld_opt_f, fld_opt_b};
    }
};

export struct OptCombo7 {
    std::int64_t req;
    std::optional<std::uint64_t> opt_u64;
    std::optional<std::string> opt_str;
};

export inline void write_opt_combo7(specodec::SpecWriter& w, const OptCombo7& obj) {
    int field_count = 1;
    if (obj.opt_u64.has_value()) field_count++;
    if (obj.opt_str.has_value()) field_count++;
    w.beginObject(field_count);
    w.writeField("req"); w.writeInt64(obj.req);;
    if (obj.opt_u64.has_value()) { w.writeField("opt_u64"); w.writeUint64(obj.opt_u64.value());; }
    if (obj.opt_str.has_value()) { w.writeField("opt_str"); w.writeString(obj.opt_str.value());; }
    w.endObject();
}

export inline specodec::SpecCodec<OptCombo7> OptCombo7Codec = {
    .encode = [](specodec::SpecWriter& w, const OptCombo7& obj) { write_opt_combo7(w, obj); },
    .decode = [](specodec::SpecReader& r) -> OptCombo7 {
        std::int64_t fld_req = 0LL;
        std::optional<std::uint64_t> fld_opt_u64;
        std::optional<std::string> fld_opt_str;
        r.beginObject();
        while (r.hasNextField()) {
            auto field_name = r.readFieldName();
            if (field_name == "req") { fld_req = r.readInt64(); }
            else if (field_name == "opt_u64") { fld_opt_u64 = std::optional<std::uint64_t>{r.readUint64()}; }
            else if (field_name == "opt_str") { fld_opt_str = std::optional<std::string>{r.readString()}; }
            else { r.skip(); }
        }
        r.endObject();
        return OptCombo7{fld_req, fld_opt_u64, fld_opt_str};
    }
};

export struct OptCombo8 {
    std::string a;
    std::optional<std::int32_t> b;
    std::optional<double> c;
    std::optional<bool> d;
    std::optional<std::vector<std::uint8_t>> e;
    std::optional<std::int64_t> f;
};

export inline void write_opt_combo8(specodec::SpecWriter& w, const OptCombo8& obj) {
    int field_count = 1;
    if (obj.b.has_value()) field_count++;
    if (obj.c.has_value()) field_count++;
    if (obj.d.has_value()) field_count++;
    if (obj.e.has_value()) field_count++;
    if (obj.f.has_value()) field_count++;
    w.beginObject(field_count);
    w.writeField("a"); w.writeString(obj.a);;
    if (obj.b.has_value()) { w.writeField("b"); w.writeInt32(obj.b.value());; }
    if (obj.c.has_value()) { w.writeField("c"); w.writeFloat64(obj.c.value());; }
    if (obj.d.has_value()) { w.writeField("d"); w.writeBool(obj.d.value());; }
    if (obj.e.has_value()) { w.writeField("e"); w.writeBytes(obj.e.value());; }
    if (obj.f.has_value()) { w.writeField("f"); w.writeInt64(obj.f.value());; }
    w.endObject();
}

export inline specodec::SpecCodec<OptCombo8> OptCombo8Codec = {
    .encode = [](specodec::SpecWriter& w, const OptCombo8& obj) { write_opt_combo8(w, obj); },
    .decode = [](specodec::SpecReader& r) -> OptCombo8 {
        std::string fld_a = "";
        std::optional<std::int32_t> fld_b;
        std::optional<double> fld_c;
        std::optional<bool> fld_d;
        std::optional<std::vector<std::uint8_t>> fld_e;
        std::optional<std::int64_t> fld_f;
        r.beginObject();
        while (r.hasNextField()) {
            auto field_name = r.readFieldName();
            if (field_name == "a") { fld_a = r.readString(); }
            else if (field_name == "b") { fld_b = std::optional<std::int32_t>{r.readInt32()}; }
            else if (field_name == "c") { fld_c = std::optional<double>{r.readFloat64()}; }
            else if (field_name == "d") { fld_d = std::optional<bool>{r.readBool()}; }
            else if (field_name == "e") { fld_e = std::optional<std::vector<std::uint8_t>>{r.readBytes()}; }
            else if (field_name == "f") { fld_f = std::optional<std::int64_t>{r.readInt64()}; }
            else { r.skip(); }
        }
        r.endObject();
        return OptCombo8{fld_a, fld_b, fld_c, fld_d, fld_e, fld_f};
    }
};

export struct OptCombo9 {
    std::string id;
    std::optional<std::string> name;
    std::optional<std::int32_t> age;
    std::optional<double> score;
};

export inline void write_opt_combo9(specodec::SpecWriter& w, const OptCombo9& obj) {
    int field_count = 1;
    if (obj.name.has_value()) field_count++;
    if (obj.age.has_value()) field_count++;
    if (obj.score.has_value()) field_count++;
    w.beginObject(field_count);
    w.writeField("id"); w.writeString(obj.id);;
    if (obj.name.has_value()) { w.writeField("name"); w.writeString(obj.name.value());; }
    if (obj.age.has_value()) { w.writeField("age"); w.writeInt32(obj.age.value());; }
    if (obj.score.has_value()) { w.writeField("score"); w.writeFloat64(obj.score.value());; }
    w.endObject();
}

export inline specodec::SpecCodec<OptCombo9> OptCombo9Codec = {
    .encode = [](specodec::SpecWriter& w, const OptCombo9& obj) { write_opt_combo9(w, obj); },
    .decode = [](specodec::SpecReader& r) -> OptCombo9 {
        std::string fld_id = "";
        std::optional<std::string> fld_name;
        std::optional<std::int32_t> fld_age;
        std::optional<double> fld_score;
        r.beginObject();
        while (r.hasNextField()) {
            auto field_name = r.readFieldName();
            if (field_name == "id") { fld_id = r.readString(); }
            else if (field_name == "name") { fld_name = std::optional<std::string>{r.readString()}; }
            else if (field_name == "age") { fld_age = std::optional<std::int32_t>{r.readInt32()}; }
            else if (field_name == "score") { fld_score = std::optional<double>{r.readFloat64()}; }
            else { r.skip(); }
        }
        r.endObject();
        return OptCombo9{fld_id, fld_name, fld_age, fld_score};
    }
};

export struct OptCombo10 {
    std::int32_t code;
    std::optional<std::string> msg;
    std::optional<std::string> detail;
    std::optional<bool> retry;
};

export inline void write_opt_combo10(specodec::SpecWriter& w, const OptCombo10& obj) {
    int field_count = 1;
    if (obj.msg.has_value()) field_count++;
    if (obj.detail.has_value()) field_count++;
    if (obj.retry.has_value()) field_count++;
    w.beginObject(field_count);
    w.writeField("code"); w.writeInt32(obj.code);;
    if (obj.msg.has_value()) { w.writeField("msg"); w.writeString(obj.msg.value());; }
    if (obj.detail.has_value()) { w.writeField("detail"); w.writeString(obj.detail.value());; }
    if (obj.retry.has_value()) { w.writeField("retry"); w.writeBool(obj.retry.value());; }
    w.endObject();
}

export inline specodec::SpecCodec<OptCombo10> OptCombo10Codec = {
    .encode = [](specodec::SpecWriter& w, const OptCombo10& obj) { write_opt_combo10(w, obj); },
    .decode = [](specodec::SpecReader& r) -> OptCombo10 {
        std::int32_t fld_code = 0;
        std::optional<std::string> fld_msg;
        std::optional<std::string> fld_detail;
        std::optional<bool> fld_retry;
        r.beginObject();
        while (r.hasNextField()) {
            auto field_name = r.readFieldName();
            if (field_name == "code") { fld_code = r.readInt32(); }
            else if (field_name == "msg") { fld_msg = std::optional<std::string>{r.readString()}; }
            else if (field_name == "detail") { fld_detail = std::optional<std::string>{r.readString()}; }
            else if (field_name == "retry") { fld_retry = std::optional<bool>{r.readBool()}; }
            else { r.skip(); }
        }
        r.endObject();
        return OptCombo10{fld_code, fld_msg, fld_detail, fld_retry};
    }
};

} // namespace all_types_arrays