// Generated by @specodec/typespec-emitter-cpp. DO NOT EDIT.
export module all_types_wide;
import std;
import specodec;
import all_types;
using namespace all_types;

namespace all_types_wide {

export struct Wide20 {
    std::string f1;
    bool f2;
    std::int8_t f3;
    std::int16_t f4;
    std::int32_t f5;
    std::int64_t f6;
    std::uint8_t f7;
    std::uint16_t f8;
    std::uint32_t f9;
    std::uint64_t f10;
    float f11;
    double f12;
    std::vector<std::uint8_t> f13;
    std::string f14;
    bool f15;
    std::int8_t f16;
    std::int16_t f17;
    std::int32_t f18;
    std::int64_t f19;
    std::uint8_t f20;
};

export inline void write_wide20(specodec::SpecWriter& w, const Wide20& obj) {
    w.beginObject(20);
    w.writeField("f1"); w.writeString(obj.f1);;
    w.writeField("f2"); w.writeBool(obj.f2);;
    w.writeField("f3"); w.writeInt32(static_cast<std::int32_t>(obj.f3));;
    w.writeField("f4"); w.writeInt32(static_cast<std::int32_t>(obj.f4));;
    w.writeField("f5"); w.writeInt32(obj.f5);;
    w.writeField("f6"); w.writeInt64(obj.f6);;
    w.writeField("f7"); w.writeUint32(static_cast<std::uint32_t>(obj.f7));;
    w.writeField("f8"); w.writeUint32(static_cast<std::uint32_t>(obj.f8));;
    w.writeField("f9"); w.writeUint32(obj.f9);;
    w.writeField("f10"); w.writeUint64(obj.f10);;
    w.writeField("f11"); w.writeFloat32(obj.f11);;
    w.writeField("f12"); w.writeFloat64(obj.f12);;
    w.writeField("f13"); w.writeBytes(obj.f13);;
    w.writeField("f14"); w.writeString(obj.f14);;
    w.writeField("f15"); w.writeBool(obj.f15);;
    w.writeField("f16"); w.writeInt32(static_cast<std::int32_t>(obj.f16));;
    w.writeField("f17"); w.writeInt32(static_cast<std::int32_t>(obj.f17));;
    w.writeField("f18"); w.writeInt32(obj.f18);;
    w.writeField("f19"); w.writeInt64(obj.f19);;
    w.writeField("f20"); w.writeUint32(static_cast<std::uint32_t>(obj.f20));;
    w.endObject();
}

export inline specodec::SpecCodec<Wide20> Wide20Codec = {
    .encode = [](specodec::SpecWriter& w, const Wide20& obj) { write_wide20(w, obj); },
    .decode = [](specodec::SpecReader& r) -> Wide20 {
        std::string fld_f1 = "";
        bool fld_f2 = false;
        std::int8_t fld_f3 = 0;
        std::int16_t fld_f4 = 0;
        std::int32_t fld_f5 = 0;
        std::int64_t fld_f6 = 0LL;
        std::uint8_t fld_f7 = 0u;
        std::uint16_t fld_f8 = 0u;
        std::uint32_t fld_f9 = 0u;
        std::uint64_t fld_f10 = 0ULL;
        float fld_f11 = 0.0f;
        double fld_f12 = 0.0;
        std::vector<std::uint8_t> fld_f13 = {};
        std::string fld_f14 = "";
        bool fld_f15 = false;
        std::int8_t fld_f16 = 0;
        std::int16_t fld_f17 = 0;
        std::int32_t fld_f18 = 0;
        std::int64_t fld_f19 = 0LL;
        std::uint8_t fld_f20 = 0u;
        r.beginObject();
        while (r.hasNextField()) {
            auto field_name = r.readFieldName();
            if (field_name == "f1") { fld_f1 = r.readString(); }
            else if (field_name == "f2") { fld_f2 = r.readBool(); }
            else if (field_name == "f3") { fld_f3 = static_cast<std::int8_t>(r.readInt32()); }
            else if (field_name == "f4") { fld_f4 = static_cast<std::int16_t>(r.readInt32()); }
            else if (field_name == "f5") { fld_f5 = r.readInt32(); }
            else if (field_name == "f6") { fld_f6 = r.readInt64(); }
            else if (field_name == "f7") { fld_f7 = static_cast<std::uint8_t>(r.readUint32()); }
            else if (field_name == "f8") { fld_f8 = static_cast<std::uint16_t>(r.readUint32()); }
            else if (field_name == "f9") { fld_f9 = r.readUint32(); }
            else if (field_name == "f10") { fld_f10 = r.readUint64(); }
            else if (field_name == "f11") { fld_f11 = r.readFloat32(); }
            else if (field_name == "f12") { fld_f12 = r.readFloat64(); }
            else if (field_name == "f13") { fld_f13 = r.readBytes(); }
            else if (field_name == "f14") { fld_f14 = r.readString(); }
            else if (field_name == "f15") { fld_f15 = r.readBool(); }
            else if (field_name == "f16") { fld_f16 = static_cast<std::int8_t>(r.readInt32()); }
            else if (field_name == "f17") { fld_f17 = static_cast<std::int16_t>(r.readInt32()); }
            else if (field_name == "f18") { fld_f18 = r.readInt32(); }
            else if (field_name == "f19") { fld_f19 = r.readInt64(); }
            else if (field_name == "f20") { fld_f20 = static_cast<std::uint8_t>(r.readUint32()); }
            else { r.skip(); }
        }
        r.endObject();
        return Wide20{fld_f1, fld_f2, fld_f3, fld_f4, fld_f5, fld_f6, fld_f7, fld_f8, fld_f9, fld_f10, fld_f11, fld_f12, fld_f13, fld_f14, fld_f15, fld_f16, fld_f17, fld_f18, fld_f19, fld_f20};
    }
};

export struct Wide25 {
    std::uint16_t f1;
    std::uint32_t f2;
    std::uint64_t f3;
    float f4;
    double f5;
    std::vector<std::uint8_t> f6;
    std::string f7;
    bool f8;
    std::int8_t f9;
    std::int16_t f10;
    std::int32_t f11;
    std::int64_t f12;
    std::uint8_t f13;
    std::uint16_t f14;
    std::uint32_t f15;
    std::uint64_t f16;
    float f17;
    double f18;
    std::vector<std::uint8_t> f19;
    std::string f20;
    bool f21;
    std::int8_t f22;
    std::int16_t f23;
    std::int32_t f24;
    std::int64_t f25;
};

export inline void write_wide25(specodec::SpecWriter& w, const Wide25& obj) {
    w.beginObject(25);
    w.writeField("f1"); w.writeUint32(static_cast<std::uint32_t>(obj.f1));;
    w.writeField("f2"); w.writeUint32(obj.f2);;
    w.writeField("f3"); w.writeUint64(obj.f3);;
    w.writeField("f4"); w.writeFloat32(obj.f4);;
    w.writeField("f5"); w.writeFloat64(obj.f5);;
    w.writeField("f6"); w.writeBytes(obj.f6);;
    w.writeField("f7"); w.writeString(obj.f7);;
    w.writeField("f8"); w.writeBool(obj.f8);;
    w.writeField("f9"); w.writeInt32(static_cast<std::int32_t>(obj.f9));;
    w.writeField("f10"); w.writeInt32(static_cast<std::int32_t>(obj.f10));;
    w.writeField("f11"); w.writeInt32(obj.f11);;
    w.writeField("f12"); w.writeInt64(obj.f12);;
    w.writeField("f13"); w.writeUint32(static_cast<std::uint32_t>(obj.f13));;
    w.writeField("f14"); w.writeUint32(static_cast<std::uint32_t>(obj.f14));;
    w.writeField("f15"); w.writeUint32(obj.f15);;
    w.writeField("f16"); w.writeUint64(obj.f16);;
    w.writeField("f17"); w.writeFloat32(obj.f17);;
    w.writeField("f18"); w.writeFloat64(obj.f18);;
    w.writeField("f19"); w.writeBytes(obj.f19);;
    w.writeField("f20"); w.writeString(obj.f20);;
    w.writeField("f21"); w.writeBool(obj.f21);;
    w.writeField("f22"); w.writeInt32(static_cast<std::int32_t>(obj.f22));;
    w.writeField("f23"); w.writeInt32(static_cast<std::int32_t>(obj.f23));;
    w.writeField("f24"); w.writeInt32(obj.f24);;
    w.writeField("f25"); w.writeInt64(obj.f25);;
    w.endObject();
}

export inline specodec::SpecCodec<Wide25> Wide25Codec = {
    .encode = [](specodec::SpecWriter& w, const Wide25& obj) { write_wide25(w, obj); },
    .decode = [](specodec::SpecReader& r) -> Wide25 {
        std::uint16_t fld_f1 = 0u;
        std::uint32_t fld_f2 = 0u;
        std::uint64_t fld_f3 = 0ULL;
        float fld_f4 = 0.0f;
        double fld_f5 = 0.0;
        std::vector<std::uint8_t> fld_f6 = {};
        std::string fld_f7 = "";
        bool fld_f8 = false;
        std::int8_t fld_f9 = 0;
        std::int16_t fld_f10 = 0;
        std::int32_t fld_f11 = 0;
        std::int64_t fld_f12 = 0LL;
        std::uint8_t fld_f13 = 0u;
        std::uint16_t fld_f14 = 0u;
        std::uint32_t fld_f15 = 0u;
        std::uint64_t fld_f16 = 0ULL;
        float fld_f17 = 0.0f;
        double fld_f18 = 0.0;
        std::vector<std::uint8_t> fld_f19 = {};
        std::string fld_f20 = "";
        bool fld_f21 = false;
        std::int8_t fld_f22 = 0;
        std::int16_t fld_f23 = 0;
        std::int32_t fld_f24 = 0;
        std::int64_t fld_f25 = 0LL;
        r.beginObject();
        while (r.hasNextField()) {
            auto field_name = r.readFieldName();
            if (field_name == "f1") { fld_f1 = static_cast<std::uint16_t>(r.readUint32()); }
            else if (field_name == "f2") { fld_f2 = r.readUint32(); }
            else if (field_name == "f3") { fld_f3 = r.readUint64(); }
            else if (field_name == "f4") { fld_f4 = r.readFloat32(); }
            else if (field_name == "f5") { fld_f5 = r.readFloat64(); }
            else if (field_name == "f6") { fld_f6 = r.readBytes(); }
            else if (field_name == "f7") { fld_f7 = r.readString(); }
            else if (field_name == "f8") { fld_f8 = r.readBool(); }
            else if (field_name == "f9") { fld_f9 = static_cast<std::int8_t>(r.readInt32()); }
            else if (field_name == "f10") { fld_f10 = static_cast<std::int16_t>(r.readInt32()); }
            else if (field_name == "f11") { fld_f11 = r.readInt32(); }
            else if (field_name == "f12") { fld_f12 = r.readInt64(); }
            else if (field_name == "f13") { fld_f13 = static_cast<std::uint8_t>(r.readUint32()); }
            else if (field_name == "f14") { fld_f14 = static_cast<std::uint16_t>(r.readUint32()); }
            else if (field_name == "f15") { fld_f15 = r.readUint32(); }
            else if (field_name == "f16") { fld_f16 = r.readUint64(); }
            else if (field_name == "f17") { fld_f17 = r.readFloat32(); }
            else if (field_name == "f18") { fld_f18 = r.readFloat64(); }
            else if (field_name == "f19") { fld_f19 = r.readBytes(); }
            else if (field_name == "f20") { fld_f20 = r.readString(); }
            else if (field_name == "f21") { fld_f21 = r.readBool(); }
            else if (field_name == "f22") { fld_f22 = static_cast<std::int8_t>(r.readInt32()); }
            else if (field_name == "f23") { fld_f23 = static_cast<std::int16_t>(r.readInt32()); }
            else if (field_name == "f24") { fld_f24 = r.readInt32(); }
            else if (field_name == "f25") { fld_f25 = r.readInt64(); }
            else { r.skip(); }
        }
        r.endObject();
        return Wide25{fld_f1, fld_f2, fld_f3, fld_f4, fld_f5, fld_f6, fld_f7, fld_f8, fld_f9, fld_f10, fld_f11, fld_f12, fld_f13, fld_f14, fld_f15, fld_f16, fld_f17, fld_f18, fld_f19, fld_f20, fld_f21, fld_f22, fld_f23, fld_f24, fld_f25};
    }
};

export struct Wide30 {
    bool f1;
    std::int8_t f2;
    std::int16_t f3;
    std::int32_t f4;
    std::int64_t f5;
    std::uint8_t f6;
    std::uint16_t f7;
    std::uint32_t f8;
    std::uint64_t f9;
    float f10;
    double f11;
    std::vector<std::uint8_t> f12;
    std::string f13;
    bool f14;
    std::int8_t f15;
    std::int16_t f16;
    std::int32_t f17;
    std::int64_t f18;
    std::uint8_t f19;
    std::uint16_t f20;
    std::uint32_t f21;
    std::uint64_t f22;
    float f23;
    double f24;
    std::vector<std::uint8_t> f25;
    std::string f26;
    bool f27;
    std::int8_t f28;
    std::int16_t f29;
    std::int32_t f30;
};

export inline void write_wide30(specodec::SpecWriter& w, const Wide30& obj) {
    w.beginObject(30);
    w.writeField("f1"); w.writeBool(obj.f1);;
    w.writeField("f2"); w.writeInt32(static_cast<std::int32_t>(obj.f2));;
    w.writeField("f3"); w.writeInt32(static_cast<std::int32_t>(obj.f3));;
    w.writeField("f4"); w.writeInt32(obj.f4);;
    w.writeField("f5"); w.writeInt64(obj.f5);;
    w.writeField("f6"); w.writeUint32(static_cast<std::uint32_t>(obj.f6));;
    w.writeField("f7"); w.writeUint32(static_cast<std::uint32_t>(obj.f7));;
    w.writeField("f8"); w.writeUint32(obj.f8);;
    w.writeField("f9"); w.writeUint64(obj.f9);;
    w.writeField("f10"); w.writeFloat32(obj.f10);;
    w.writeField("f11"); w.writeFloat64(obj.f11);;
    w.writeField("f12"); w.writeBytes(obj.f12);;
    w.writeField("f13"); w.writeString(obj.f13);;
    w.writeField("f14"); w.writeBool(obj.f14);;
    w.writeField("f15"); w.writeInt32(static_cast<std::int32_t>(obj.f15));;
    w.writeField("f16"); w.writeInt32(static_cast<std::int32_t>(obj.f16));;
    w.writeField("f17"); w.writeInt32(obj.f17);;
    w.writeField("f18"); w.writeInt64(obj.f18);;
    w.writeField("f19"); w.writeUint32(static_cast<std::uint32_t>(obj.f19));;
    w.writeField("f20"); w.writeUint32(static_cast<std::uint32_t>(obj.f20));;
    w.writeField("f21"); w.writeUint32(obj.f21);;
    w.writeField("f22"); w.writeUint64(obj.f22);;
    w.writeField("f23"); w.writeFloat32(obj.f23);;
    w.writeField("f24"); w.writeFloat64(obj.f24);;
    w.writeField("f25"); w.writeBytes(obj.f25);;
    w.writeField("f26"); w.writeString(obj.f26);;
    w.writeField("f27"); w.writeBool(obj.f27);;
    w.writeField("f28"); w.writeInt32(static_cast<std::int32_t>(obj.f28));;
    w.writeField("f29"); w.writeInt32(static_cast<std::int32_t>(obj.f29));;
    w.writeField("f30"); w.writeInt32(obj.f30);;
    w.endObject();
}

export inline specodec::SpecCodec<Wide30> Wide30Codec = {
    .encode = [](specodec::SpecWriter& w, const Wide30& obj) { write_wide30(w, obj); },
    .decode = [](specodec::SpecReader& r) -> Wide30 {
        bool fld_f1 = false;
        std::int8_t fld_f2 = 0;
        std::int16_t fld_f3 = 0;
        std::int32_t fld_f4 = 0;
        std::int64_t fld_f5 = 0LL;
        std::uint8_t fld_f6 = 0u;
        std::uint16_t fld_f7 = 0u;
        std::uint32_t fld_f8 = 0u;
        std::uint64_t fld_f9 = 0ULL;
        float fld_f10 = 0.0f;
        double fld_f11 = 0.0;
        std::vector<std::uint8_t> fld_f12 = {};
        std::string fld_f13 = "";
        bool fld_f14 = false;
        std::int8_t fld_f15 = 0;
        std::int16_t fld_f16 = 0;
        std::int32_t fld_f17 = 0;
        std::int64_t fld_f18 = 0LL;
        std::uint8_t fld_f19 = 0u;
        std::uint16_t fld_f20 = 0u;
        std::uint32_t fld_f21 = 0u;
        std::uint64_t fld_f22 = 0ULL;
        float fld_f23 = 0.0f;
        double fld_f24 = 0.0;
        std::vector<std::uint8_t> fld_f25 = {};
        std::string fld_f26 = "";
        bool fld_f27 = false;
        std::int8_t fld_f28 = 0;
        std::int16_t fld_f29 = 0;
        std::int32_t fld_f30 = 0;
        r.beginObject();
        while (r.hasNextField()) {
            auto field_name = r.readFieldName();
            if (field_name == "f1") { fld_f1 = r.readBool(); }
            else if (field_name == "f2") { fld_f2 = static_cast<std::int8_t>(r.readInt32()); }
            else if (field_name == "f3") { fld_f3 = static_cast<std::int16_t>(r.readInt32()); }
            else if (field_name == "f4") { fld_f4 = r.readInt32(); }
            else if (field_name == "f5") { fld_f5 = r.readInt64(); }
            else if (field_name == "f6") { fld_f6 = static_cast<std::uint8_t>(r.readUint32()); }
            else if (field_name == "f7") { fld_f7 = static_cast<std::uint16_t>(r.readUint32()); }
            else if (field_name == "f8") { fld_f8 = r.readUint32(); }
            else if (field_name == "f9") { fld_f9 = r.readUint64(); }
            else if (field_name == "f10") { fld_f10 = r.readFloat32(); }
            else if (field_name == "f11") { fld_f11 = r.readFloat64(); }
            else if (field_name == "f12") { fld_f12 = r.readBytes(); }
            else if (field_name == "f13") { fld_f13 = r.readString(); }
            else if (field_name == "f14") { fld_f14 = r.readBool(); }
            else if (field_name == "f15") { fld_f15 = static_cast<std::int8_t>(r.readInt32()); }
            else if (field_name == "f16") { fld_f16 = static_cast<std::int16_t>(r.readInt32()); }
            else if (field_name == "f17") { fld_f17 = r.readInt32(); }
            else if (field_name == "f18") { fld_f18 = r.readInt64(); }
            else if (field_name == "f19") { fld_f19 = static_cast<std::uint8_t>(r.readUint32()); }
            else if (field_name == "f20") { fld_f20 = static_cast<std::uint16_t>(r.readUint32()); }
            else if (field_name == "f21") { fld_f21 = r.readUint32(); }
            else if (field_name == "f22") { fld_f22 = r.readUint64(); }
            else if (field_name == "f23") { fld_f23 = r.readFloat32(); }
            else if (field_name == "f24") { fld_f24 = r.readFloat64(); }
            else if (field_name == "f25") { fld_f25 = r.readBytes(); }
            else if (field_name == "f26") { fld_f26 = r.readString(); }
            else if (field_name == "f27") { fld_f27 = r.readBool(); }
            else if (field_name == "f28") { fld_f28 = static_cast<std::int8_t>(r.readInt32()); }
            else if (field_name == "f29") { fld_f29 = static_cast<std::int16_t>(r.readInt32()); }
            else if (field_name == "f30") { fld_f30 = r.readInt32(); }
            else { r.skip(); }
        }
        r.endObject();
        return Wide30{fld_f1, fld_f2, fld_f3, fld_f4, fld_f5, fld_f6, fld_f7, fld_f8, fld_f9, fld_f10, fld_f11, fld_f12, fld_f13, fld_f14, fld_f15, fld_f16, fld_f17, fld_f18, fld_f19, fld_f20, fld_f21, fld_f22, fld_f23, fld_f24, fld_f25, fld_f26, fld_f27, fld_f28, fld_f29, fld_f30};
    }
};

export struct Wide35 {
    std::uint32_t f1;
    std::uint64_t f2;
    float f3;
    double f4;
    std::vector<std::uint8_t> f5;
    std::string f6;
    bool f7;
    std::int8_t f8;
    std::int16_t f9;
    std::int32_t f10;
    std::int64_t f11;
    std::uint8_t f12;
    std::uint16_t f13;
    std::uint32_t f14;
    std::uint64_t f15;
    float f16;
    double f17;
    std::vector<std::uint8_t> f18;
    std::string f19;
    bool f20;
    std::int8_t f21;
    std::int16_t f22;
    std::int32_t f23;
    std::int64_t f24;
    std::uint8_t f25;
    std::uint16_t f26;
    std::uint32_t f27;
    std::uint64_t f28;
    float f29;
    double f30;
    std::vector<std::uint8_t> f31;
    std::string f32;
    bool f33;
    std::int8_t f34;
    std::int16_t f35;
};

export inline void write_wide35(specodec::SpecWriter& w, const Wide35& obj) {
    w.beginObject(35);
    w.writeField("f1"); w.writeUint32(obj.f1);;
    w.writeField("f2"); w.writeUint64(obj.f2);;
    w.writeField("f3"); w.writeFloat32(obj.f3);;
    w.writeField("f4"); w.writeFloat64(obj.f4);;
    w.writeField("f5"); w.writeBytes(obj.f5);;
    w.writeField("f6"); w.writeString(obj.f6);;
    w.writeField("f7"); w.writeBool(obj.f7);;
    w.writeField("f8"); w.writeInt32(static_cast<std::int32_t>(obj.f8));;
    w.writeField("f9"); w.writeInt32(static_cast<std::int32_t>(obj.f9));;
    w.writeField("f10"); w.writeInt32(obj.f10);;
    w.writeField("f11"); w.writeInt64(obj.f11);;
    w.writeField("f12"); w.writeUint32(static_cast<std::uint32_t>(obj.f12));;
    w.writeField("f13"); w.writeUint32(static_cast<std::uint32_t>(obj.f13));;
    w.writeField("f14"); w.writeUint32(obj.f14);;
    w.writeField("f15"); w.writeUint64(obj.f15);;
    w.writeField("f16"); w.writeFloat32(obj.f16);;
    w.writeField("f17"); w.writeFloat64(obj.f17);;
    w.writeField("f18"); w.writeBytes(obj.f18);;
    w.writeField("f19"); w.writeString(obj.f19);;
    w.writeField("f20"); w.writeBool(obj.f20);;
    w.writeField("f21"); w.writeInt32(static_cast<std::int32_t>(obj.f21));;
    w.writeField("f22"); w.writeInt32(static_cast<std::int32_t>(obj.f22));;
    w.writeField("f23"); w.writeInt32(obj.f23);;
    w.writeField("f24"); w.writeInt64(obj.f24);;
    w.writeField("f25"); w.writeUint32(static_cast<std::uint32_t>(obj.f25));;
    w.writeField("f26"); w.writeUint32(static_cast<std::uint32_t>(obj.f26));;
    w.writeField("f27"); w.writeUint32(obj.f27);;
    w.writeField("f28"); w.writeUint64(obj.f28);;
    w.writeField("f29"); w.writeFloat32(obj.f29);;
    w.writeField("f30"); w.writeFloat64(obj.f30);;
    w.writeField("f31"); w.writeBytes(obj.f31);;
    w.writeField("f32"); w.writeString(obj.f32);;
    w.writeField("f33"); w.writeBool(obj.f33);;
    w.writeField("f34"); w.writeInt32(static_cast<std::int32_t>(obj.f34));;
    w.writeField("f35"); w.writeInt32(static_cast<std::int32_t>(obj.f35));;
    w.endObject();
}

export inline specodec::SpecCodec<Wide35> Wide35Codec = {
    .encode = [](specodec::SpecWriter& w, const Wide35& obj) { write_wide35(w, obj); },
    .decode = [](specodec::SpecReader& r) -> Wide35 {
        std::uint32_t fld_f1 = 0u;
        std::uint64_t fld_f2 = 0ULL;
        float fld_f3 = 0.0f;
        double fld_f4 = 0.0;
        std::vector<std::uint8_t> fld_f5 = {};
        std::string fld_f6 = "";
        bool fld_f7 = false;
        std::int8_t fld_f8 = 0;
        std::int16_t fld_f9 = 0;
        std::int32_t fld_f10 = 0;
        std::int64_t fld_f11 = 0LL;
        std::uint8_t fld_f12 = 0u;
        std::uint16_t fld_f13 = 0u;
        std::uint32_t fld_f14 = 0u;
        std::uint64_t fld_f15 = 0ULL;
        float fld_f16 = 0.0f;
        double fld_f17 = 0.0;
        std::vector<std::uint8_t> fld_f18 = {};
        std::string fld_f19 = "";
        bool fld_f20 = false;
        std::int8_t fld_f21 = 0;
        std::int16_t fld_f22 = 0;
        std::int32_t fld_f23 = 0;
        std::int64_t fld_f24 = 0LL;
        std::uint8_t fld_f25 = 0u;
        std::uint16_t fld_f26 = 0u;
        std::uint32_t fld_f27 = 0u;
        std::uint64_t fld_f28 = 0ULL;
        float fld_f29 = 0.0f;
        double fld_f30 = 0.0;
        std::vector<std::uint8_t> fld_f31 = {};
        std::string fld_f32 = "";
        bool fld_f33 = false;
        std::int8_t fld_f34 = 0;
        std::int16_t fld_f35 = 0;
        r.beginObject();
        while (r.hasNextField()) {
            auto field_name = r.readFieldName();
            if (field_name == "f1") { fld_f1 = r.readUint32(); }
            else if (field_name == "f2") { fld_f2 = r.readUint64(); }
            else if (field_name == "f3") { fld_f3 = r.readFloat32(); }
            else if (field_name == "f4") { fld_f4 = r.readFloat64(); }
            else if (field_name == "f5") { fld_f5 = r.readBytes(); }
            else if (field_name == "f6") { fld_f6 = r.readString(); }
            else if (field_name == "f7") { fld_f7 = r.readBool(); }
            else if (field_name == "f8") { fld_f8 = static_cast<std::int8_t>(r.readInt32()); }
            else if (field_name == "f9") { fld_f9 = static_cast<std::int16_t>(r.readInt32()); }
            else if (field_name == "f10") { fld_f10 = r.readInt32(); }
            else if (field_name == "f11") { fld_f11 = r.readInt64(); }
            else if (field_name == "f12") { fld_f12 = static_cast<std::uint8_t>(r.readUint32()); }
            else if (field_name == "f13") { fld_f13 = static_cast<std::uint16_t>(r.readUint32()); }
            else if (field_name == "f14") { fld_f14 = r.readUint32(); }
            else if (field_name == "f15") { fld_f15 = r.readUint64(); }
            else if (field_name == "f16") { fld_f16 = r.readFloat32(); }
            else if (field_name == "f17") { fld_f17 = r.readFloat64(); }
            else if (field_name == "f18") { fld_f18 = r.readBytes(); }
            else if (field_name == "f19") { fld_f19 = r.readString(); }
            else if (field_name == "f20") { fld_f20 = r.readBool(); }
            else if (field_name == "f21") { fld_f21 = static_cast<std::int8_t>(r.readInt32()); }
            else if (field_name == "f22") { fld_f22 = static_cast<std::int16_t>(r.readInt32()); }
            else if (field_name == "f23") { fld_f23 = r.readInt32(); }
            else if (field_name == "f24") { fld_f24 = r.readInt64(); }
            else if (field_name == "f25") { fld_f25 = static_cast<std::uint8_t>(r.readUint32()); }
            else if (field_name == "f26") { fld_f26 = static_cast<std::uint16_t>(r.readUint32()); }
            else if (field_name == "f27") { fld_f27 = r.readUint32(); }
            else if (field_name == "f28") { fld_f28 = r.readUint64(); }
            else if (field_name == "f29") { fld_f29 = r.readFloat32(); }
            else if (field_name == "f30") { fld_f30 = r.readFloat64(); }
            else if (field_name == "f31") { fld_f31 = r.readBytes(); }
            else if (field_name == "f32") { fld_f32 = r.readString(); }
            else if (field_name == "f33") { fld_f33 = r.readBool(); }
            else if (field_name == "f34") { fld_f34 = static_cast<std::int8_t>(r.readInt32()); }
            else if (field_name == "f35") { fld_f35 = static_cast<std::int16_t>(r.readInt32()); }
            else { r.skip(); }
        }
        r.endObject();
        return Wide35{fld_f1, fld_f2, fld_f3, fld_f4, fld_f5, fld_f6, fld_f7, fld_f8, fld_f9, fld_f10, fld_f11, fld_f12, fld_f13, fld_f14, fld_f15, fld_f16, fld_f17, fld_f18, fld_f19, fld_f20, fld_f21, fld_f22, fld_f23, fld_f24, fld_f25, fld_f26, fld_f27, fld_f28, fld_f29, fld_f30, fld_f31, fld_f32, fld_f33, fld_f34, fld_f35};
    }
};

export struct Wide40 {
    std::int8_t f1;
    std::int16_t f2;
    std::int32_t f3;
    std::int64_t f4;
    std::uint8_t f5;
    std::uint16_t f6;
    std::uint32_t f7;
    std::uint64_t f8;
    float f9;
    double f10;
    std::vector<std::uint8_t> f11;
    std::string f12;
    bool f13;
    std::int8_t f14;
    std::int16_t f15;
    std::int32_t f16;
    std::int64_t f17;
    std::uint8_t f18;
    std::uint16_t f19;
    std::uint32_t f20;
    std::uint64_t f21;
    float f22;
    double f23;
    std::vector<std::uint8_t> f24;
    std::string f25;
    bool f26;
    std::int8_t f27;
    std::int16_t f28;
    std::int32_t f29;
    std::int64_t f30;
    std::uint8_t f31;
    std::uint16_t f32;
    std::uint32_t f33;
    std::uint64_t f34;
    float f35;
    double f36;
    std::vector<std::uint8_t> f37;
    std::string f38;
    bool f39;
    std::int8_t f40;
};

export inline void write_wide40(specodec::SpecWriter& w, const Wide40& obj) {
    w.beginObject(40);
    w.writeField("f1"); w.writeInt32(static_cast<std::int32_t>(obj.f1));;
    w.writeField("f2"); w.writeInt32(static_cast<std::int32_t>(obj.f2));;
    w.writeField("f3"); w.writeInt32(obj.f3);;
    w.writeField("f4"); w.writeInt64(obj.f4);;
    w.writeField("f5"); w.writeUint32(static_cast<std::uint32_t>(obj.f5));;
    w.writeField("f6"); w.writeUint32(static_cast<std::uint32_t>(obj.f6));;
    w.writeField("f7"); w.writeUint32(obj.f7);;
    w.writeField("f8"); w.writeUint64(obj.f8);;
    w.writeField("f9"); w.writeFloat32(obj.f9);;
    w.writeField("f10"); w.writeFloat64(obj.f10);;
    w.writeField("f11"); w.writeBytes(obj.f11);;
    w.writeField("f12"); w.writeString(obj.f12);;
    w.writeField("f13"); w.writeBool(obj.f13);;
    w.writeField("f14"); w.writeInt32(static_cast<std::int32_t>(obj.f14));;
    w.writeField("f15"); w.writeInt32(static_cast<std::int32_t>(obj.f15));;
    w.writeField("f16"); w.writeInt32(obj.f16);;
    w.writeField("f17"); w.writeInt64(obj.f17);;
    w.writeField("f18"); w.writeUint32(static_cast<std::uint32_t>(obj.f18));;
    w.writeField("f19"); w.writeUint32(static_cast<std::uint32_t>(obj.f19));;
    w.writeField("f20"); w.writeUint32(obj.f20);;
    w.writeField("f21"); w.writeUint64(obj.f21);;
    w.writeField("f22"); w.writeFloat32(obj.f22);;
    w.writeField("f23"); w.writeFloat64(obj.f23);;
    w.writeField("f24"); w.writeBytes(obj.f24);;
    w.writeField("f25"); w.writeString(obj.f25);;
    w.writeField("f26"); w.writeBool(obj.f26);;
    w.writeField("f27"); w.writeInt32(static_cast<std::int32_t>(obj.f27));;
    w.writeField("f28"); w.writeInt32(static_cast<std::int32_t>(obj.f28));;
    w.writeField("f29"); w.writeInt32(obj.f29);;
    w.writeField("f30"); w.writeInt64(obj.f30);;
    w.writeField("f31"); w.writeUint32(static_cast<std::uint32_t>(obj.f31));;
    w.writeField("f32"); w.writeUint32(static_cast<std::uint32_t>(obj.f32));;
    w.writeField("f33"); w.writeUint32(obj.f33);;
    w.writeField("f34"); w.writeUint64(obj.f34);;
    w.writeField("f35"); w.writeFloat32(obj.f35);;
    w.writeField("f36"); w.writeFloat64(obj.f36);;
    w.writeField("f37"); w.writeBytes(obj.f37);;
    w.writeField("f38"); w.writeString(obj.f38);;
    w.writeField("f39"); w.writeBool(obj.f39);;
    w.writeField("f40"); w.writeInt32(static_cast<std::int32_t>(obj.f40));;
    w.endObject();
}

export inline specodec::SpecCodec<Wide40> Wide40Codec = {
    .encode = [](specodec::SpecWriter& w, const Wide40& obj) { write_wide40(w, obj); },
    .decode = [](specodec::SpecReader& r) -> Wide40 {
        std::int8_t fld_f1 = 0;
        std::int16_t fld_f2 = 0;
        std::int32_t fld_f3 = 0;
        std::int64_t fld_f4 = 0LL;
        std::uint8_t fld_f5 = 0u;
        std::uint16_t fld_f6 = 0u;
        std::uint32_t fld_f7 = 0u;
        std::uint64_t fld_f8 = 0ULL;
        float fld_f9 = 0.0f;
        double fld_f10 = 0.0;
        std::vector<std::uint8_t> fld_f11 = {};
        std::string fld_f12 = "";
        bool fld_f13 = false;
        std::int8_t fld_f14 = 0;
        std::int16_t fld_f15 = 0;
        std::int32_t fld_f16 = 0;
        std::int64_t fld_f17 = 0LL;
        std::uint8_t fld_f18 = 0u;
        std::uint16_t fld_f19 = 0u;
        std::uint32_t fld_f20 = 0u;
        std::uint64_t fld_f21 = 0ULL;
        float fld_f22 = 0.0f;
        double fld_f23 = 0.0;
        std::vector<std::uint8_t> fld_f24 = {};
        std::string fld_f25 = "";
        bool fld_f26 = false;
        std::int8_t fld_f27 = 0;
        std::int16_t fld_f28 = 0;
        std::int32_t fld_f29 = 0;
        std::int64_t fld_f30 = 0LL;
        std::uint8_t fld_f31 = 0u;
        std::uint16_t fld_f32 = 0u;
        std::uint32_t fld_f33 = 0u;
        std::uint64_t fld_f34 = 0ULL;
        float fld_f35 = 0.0f;
        double fld_f36 = 0.0;
        std::vector<std::uint8_t> fld_f37 = {};
        std::string fld_f38 = "";
        bool fld_f39 = false;
        std::int8_t fld_f40 = 0;
        r.beginObject();
        while (r.hasNextField()) {
            auto field_name = r.readFieldName();
            if (field_name == "f1") { fld_f1 = static_cast<std::int8_t>(r.readInt32()); }
            else if (field_name == "f2") { fld_f2 = static_cast<std::int16_t>(r.readInt32()); }
            else if (field_name == "f3") { fld_f3 = r.readInt32(); }
            else if (field_name == "f4") { fld_f4 = r.readInt64(); }
            else if (field_name == "f5") { fld_f5 = static_cast<std::uint8_t>(r.readUint32()); }
            else if (field_name == "f6") { fld_f6 = static_cast<std::uint16_t>(r.readUint32()); }
            else if (field_name == "f7") { fld_f7 = r.readUint32(); }
            else if (field_name == "f8") { fld_f8 = r.readUint64(); }
            else if (field_name == "f9") { fld_f9 = r.readFloat32(); }
            else if (field_name == "f10") { fld_f10 = r.readFloat64(); }
            else if (field_name == "f11") { fld_f11 = r.readBytes(); }
            else if (field_name == "f12") { fld_f12 = r.readString(); }
            else if (field_name == "f13") { fld_f13 = r.readBool(); }
            else if (field_name == "f14") { fld_f14 = static_cast<std::int8_t>(r.readInt32()); }
            else if (field_name == "f15") { fld_f15 = static_cast<std::int16_t>(r.readInt32()); }
            else if (field_name == "f16") { fld_f16 = r.readInt32(); }
            else if (field_name == "f17") { fld_f17 = r.readInt64(); }
            else if (field_name == "f18") { fld_f18 = static_cast<std::uint8_t>(r.readUint32()); }
            else if (field_name == "f19") { fld_f19 = static_cast<std::uint16_t>(r.readUint32()); }
            else if (field_name == "f20") { fld_f20 = r.readUint32(); }
            else if (field_name == "f21") { fld_f21 = r.readUint64(); }
            else if (field_name == "f22") { fld_f22 = r.readFloat32(); }
            else if (field_name == "f23") { fld_f23 = r.readFloat64(); }
            else if (field_name == "f24") { fld_f24 = r.readBytes(); }
            else if (field_name == "f25") { fld_f25 = r.readString(); }
            else if (field_name == "f26") { fld_f26 = r.readBool(); }
            else if (field_name == "f27") { fld_f27 = static_cast<std::int8_t>(r.readInt32()); }
            else if (field_name == "f28") { fld_f28 = static_cast<std::int16_t>(r.readInt32()); }
            else if (field_name == "f29") { fld_f29 = r.readInt32(); }
            else if (field_name == "f30") { fld_f30 = r.readInt64(); }
            else if (field_name == "f31") { fld_f31 = static_cast<std::uint8_t>(r.readUint32()); }
            else if (field_name == "f32") { fld_f32 = static_cast<std::uint16_t>(r.readUint32()); }
            else if (field_name == "f33") { fld_f33 = r.readUint32(); }
            else if (field_name == "f34") { fld_f34 = r.readUint64(); }
            else if (field_name == "f35") { fld_f35 = r.readFloat32(); }
            else if (field_name == "f36") { fld_f36 = r.readFloat64(); }
            else if (field_name == "f37") { fld_f37 = r.readBytes(); }
            else if (field_name == "f38") { fld_f38 = r.readString(); }
            else if (field_name == "f39") { fld_f39 = r.readBool(); }
            else if (field_name == "f40") { fld_f40 = static_cast<std::int8_t>(r.readInt32()); }
            else { r.skip(); }
        }
        r.endObject();
        return Wide40{fld_f1, fld_f2, fld_f3, fld_f4, fld_f5, fld_f6, fld_f7, fld_f8, fld_f9, fld_f10, fld_f11, fld_f12, fld_f13, fld_f14, fld_f15, fld_f16, fld_f17, fld_f18, fld_f19, fld_f20, fld_f21, fld_f22, fld_f23, fld_f24, fld_f25, fld_f26, fld_f27, fld_f28, fld_f29, fld_f30, fld_f31, fld_f32, fld_f33, fld_f34, fld_f35, fld_f36, fld_f37, fld_f38, fld_f39, fld_f40};
    }
};

} // namespace all_types_wide