// Generated by @specodec/typespec-emitter-cpp. DO NOT EDIT.
export module all_types_nested;
import std;
import specodec;
import all_types;
using namespace all_types;

namespace all_types_nested {

export struct NestedSimple {
    std::string name;
    std::int32_t value;
};

export inline void write_nested_simple(specodec::SpecWriter& w, const NestedSimple& obj) {
    w.beginObject(2);
    w.writeField("name"); w.writeString(obj.name);;
    w.writeField("value"); w.writeInt32(obj.value);;
    w.endObject();
}

export inline specodec::SpecCodec<NestedSimple> NestedSimpleCodec = {
    .encode = [](specodec::SpecWriter& w, const NestedSimple& obj) { write_nested_simple(w, obj); },
    .decode = [](specodec::SpecReader& r) -> NestedSimple {
        std::string fld_name = "";
        std::int32_t fld_value = 0;
        r.beginObject();
        while (r.hasNextField()) {
            auto field_name = r.readFieldName();
            if (field_name == "name") { fld_name = r.readString(); }
            else if (field_name == "value") { fld_value = r.readInt32(); }
            else { r.skip(); }
        }
        r.endObject();
        return NestedSimple{fld_name, fld_value};
    }
};

} // namespace all_types_nested