// Generated by @specodec/typespec-emitter-cpp. DO NOT EDIT.
export module all_types_wide;
import std;
import specodec;
import all_types;
using namespace all_types;

namespace all_types_wide {

export struct Wide20 {
    std::string f1_;
    bool f2_;
    std::int8_t f3_;
    std::int16_t f4_;
    std::int32_t f5_;
    std::int64_t f6_;
    std::uint8_t f7_;
    std::uint16_t f8_;
    std::uint32_t f9_;
    std::uint64_t f10_;
    float f11_;
    double f12_;
    std::vector<std::uint8_t> f13_;
    std::string f14_;
    bool f15_;
    std::int8_t f16_;
    std::int16_t f17_;
    std::int32_t f18_;
    std::int64_t f19_;
    std::uint8_t f20_;
};

export inline void write_wide20(specodec::SpecWriter& w, const Wide20& obj) {
    w.beginObject(20);
    w.writeField("f1"); w.writeString(obj.f1_);;
    w.writeField("f2"); w.writeBool(obj.f2_);;
    w.writeField("f3"); w.writeInt32(static_cast<std::int32_t>(obj.f3_));;
    w.writeField("f4"); w.writeInt32(static_cast<std::int32_t>(obj.f4_));;
    w.writeField("f5"); w.writeInt32(obj.f5_);;
    w.writeField("f6"); w.writeInt64(obj.f6_);;
    w.writeField("f7"); w.writeUint32(static_cast<std::uint32_t>(obj.f7_));;
    w.writeField("f8"); w.writeUint32(static_cast<std::uint32_t>(obj.f8_));;
    w.writeField("f9"); w.writeUint32(obj.f9_);;
    w.writeField("f10"); w.writeUint64(obj.f10_);;
    w.writeField("f11"); w.writeFloat32(obj.f11_);;
    w.writeField("f12"); w.writeFloat64(obj.f12_);;
    w.writeField("f13"); w.writeBytes(obj.f13_);;
    w.writeField("f14"); w.writeString(obj.f14_);;
    w.writeField("f15"); w.writeBool(obj.f15_);;
    w.writeField("f16"); w.writeInt32(static_cast<std::int32_t>(obj.f16_));;
    w.writeField("f17"); w.writeInt32(static_cast<std::int32_t>(obj.f17_));;
    w.writeField("f18"); w.writeInt32(obj.f18_);;
    w.writeField("f19"); w.writeInt64(obj.f19_);;
    w.writeField("f20"); w.writeUint32(static_cast<std::uint32_t>(obj.f20_));;
    w.endObject();
}

export inline specodec::SpecCodec<Wide20> Wide20Codec = {
    .encode = [](specodec::SpecWriter& w, const Wide20& obj) { write_wide20(w, obj); },
    .decode = [](specodec::SpecReader& r) -> Wide20 {
        std::string fld_f1 = "";
        bool fld_f2 = false;
        std::int8_t fld_f3 = 0;
        std::int16_t fld_f4 = 0;
        std::int32_t fld_f5 = 0;
        std::int64_t fld_f6 = 0LL;
        std::uint8_t fld_f7 = 0u;
        std::uint16_t fld_f8 = 0u;
        std::uint32_t fld_f9 = 0u;
        std::uint64_t fld_f10 = 0ULL;
        float fld_f11 = 0.0f;
        double fld_f12 = 0.0;
        std::vector<std::uint8_t> fld_f13 = {};
        std::string fld_f14 = "";
        bool fld_f15 = false;
        std::int8_t fld_f16 = 0;
        std::int16_t fld_f17 = 0;
        std::int32_t fld_f18 = 0;
        std::int64_t fld_f19 = 0LL;
        std::uint8_t fld_f20 = 0u;
        r.beginObject();
        while (r.hasNextField()) {
            auto field_name = r.readFieldName();
            if (field_name == "f1") { fld_f1 = r.readString(); }
            else if (field_name == "f2") { fld_f2 = r.readBool(); }
            else if (field_name == "f3") { fld_f3 = static_cast<std::int8_t>(r.readInt32()); }
            else if (field_name == "f4") { fld_f4 = static_cast<std::int16_t>(r.readInt32()); }
            else if (field_name == "f5") { fld_f5 = r.readInt32(); }
            else if (field_name == "f6") { fld_f6 = r.readInt64(); }
            else if (field_name == "f7") { fld_f7 = static_cast<std::uint8_t>(r.readUint32()); }
            else if (field_name == "f8") { fld_f8 = static_cast<std::uint16_t>(r.readUint32()); }
            else if (field_name == "f9") { fld_f9 = r.readUint32(); }
            else if (field_name == "f10") { fld_f10 = r.readUint64(); }
            else if (field_name == "f11") { fld_f11 = r.readFloat32(); }
            else if (field_name == "f12") { fld_f12 = r.readFloat64(); }
            else if (field_name == "f13") { fld_f13 = r.readBytes(); }
            else if (field_name == "f14") { fld_f14 = r.readString(); }
            else if (field_name == "f15") { fld_f15 = r.readBool(); }
            else if (field_name == "f16") { fld_f16 = static_cast<std::int8_t>(r.readInt32()); }
            else if (field_name == "f17") { fld_f17 = static_cast<std::int16_t>(r.readInt32()); }
            else if (field_name == "f18") { fld_f18 = r.readInt32(); }
            else if (field_name == "f19") { fld_f19 = r.readInt64(); }
            else if (field_name == "f20") { fld_f20 = static_cast<std::uint8_t>(r.readUint32()); }
            else { r.skip(); }
        }
        r.endObject();
        return Wide20{fld_f1, fld_f2, fld_f3, fld_f4, fld_f5, fld_f6, fld_f7, fld_f8, fld_f9, fld_f10, fld_f11, fld_f12, fld_f13, fld_f14, fld_f15, fld_f16, fld_f17, fld_f18, fld_f19, fld_f20};
    }
};

export struct Wide25 {
    std::uint16_t f1_;
    std::uint32_t f2_;
    std::uint64_t f3_;
    float f4_;
    double f5_;
    std::vector<std::uint8_t> f6_;
    std::string f7_;
    bool f8_;
    std::int8_t f9_;
    std::int16_t f10_;
    std::int32_t f11_;
    std::int64_t f12_;
    std::uint8_t f13_;
    std::uint16_t f14_;
    std::uint32_t f15_;
    std::uint64_t f16_;
    float f17_;
    double f18_;
    std::vector<std::uint8_t> f19_;
    std::string f20_;
    bool f21_;
    std::int8_t f22_;
    std::int16_t f23_;
    std::int32_t f24_;
    std::int64_t f25_;
};

export inline void write_wide25(specodec::SpecWriter& w, const Wide25& obj) {
    w.beginObject(25);
    w.writeField("f1"); w.writeUint32(static_cast<std::uint32_t>(obj.f1_));;
    w.writeField("f2"); w.writeUint32(obj.f2_);;
    w.writeField("f3"); w.writeUint64(obj.f3_);;
    w.writeField("f4"); w.writeFloat32(obj.f4_);;
    w.writeField("f5"); w.writeFloat64(obj.f5_);;
    w.writeField("f6"); w.writeBytes(obj.f6_);;
    w.writeField("f7"); w.writeString(obj.f7_);;
    w.writeField("f8"); w.writeBool(obj.f8_);;
    w.writeField("f9"); w.writeInt32(static_cast<std::int32_t>(obj.f9_));;
    w.writeField("f10"); w.writeInt32(static_cast<std::int32_t>(obj.f10_));;
    w.writeField("f11"); w.writeInt32(obj.f11_);;
    w.writeField("f12"); w.writeInt64(obj.f12_);;
    w.writeField("f13"); w.writeUint32(static_cast<std::uint32_t>(obj.f13_));;
    w.writeField("f14"); w.writeUint32(static_cast<std::uint32_t>(obj.f14_));;
    w.writeField("f15"); w.writeUint32(obj.f15_);;
    w.writeField("f16"); w.writeUint64(obj.f16_);;
    w.writeField("f17"); w.writeFloat32(obj.f17_);;
    w.writeField("f18"); w.writeFloat64(obj.f18_);;
    w.writeField("f19"); w.writeBytes(obj.f19_);;
    w.writeField("f20"); w.writeString(obj.f20_);;
    w.writeField("f21"); w.writeBool(obj.f21_);;
    w.writeField("f22"); w.writeInt32(static_cast<std::int32_t>(obj.f22_));;
    w.writeField("f23"); w.writeInt32(static_cast<std::int32_t>(obj.f23_));;
    w.writeField("f24"); w.writeInt32(obj.f24_);;
    w.writeField("f25"); w.writeInt64(obj.f25_);;
    w.endObject();
}

export inline specodec::SpecCodec<Wide25> Wide25Codec = {
    .encode = [](specodec::SpecWriter& w, const Wide25& obj) { write_wide25(w, obj); },
    .decode = [](specodec::SpecReader& r) -> Wide25 {
        std::uint16_t fld_f1 = 0u;
        std::uint32_t fld_f2 = 0u;
        std::uint64_t fld_f3 = 0ULL;
        float fld_f4 = 0.0f;
        double fld_f5 = 0.0;
        std::vector<std::uint8_t> fld_f6 = {};
        std::string fld_f7 = "";
        bool fld_f8 = false;
        std::int8_t fld_f9 = 0;
        std::int16_t fld_f10 = 0;
        std::int32_t fld_f11 = 0;
        std::int64_t fld_f12 = 0LL;
        std::uint8_t fld_f13 = 0u;
        std::uint16_t fld_f14 = 0u;
        std::uint32_t fld_f15 = 0u;
        std::uint64_t fld_f16 = 0ULL;
        float fld_f17 = 0.0f;
        double fld_f18 = 0.0;
        std::vector<std::uint8_t> fld_f19 = {};
        std::string fld_f20 = "";
        bool fld_f21 = false;
        std::int8_t fld_f22 = 0;
        std::int16_t fld_f23 = 0;
        std::int32_t fld_f24 = 0;
        std::int64_t fld_f25 = 0LL;
        r.beginObject();
        while (r.hasNextField()) {
            auto field_name = r.readFieldName();
            if (field_name == "f1") { fld_f1 = static_cast<std::uint16_t>(r.readUint32()); }
            else if (field_name == "f2") { fld_f2 = r.readUint32(); }
            else if (field_name == "f3") { fld_f3 = r.readUint64(); }
            else if (field_name == "f4") { fld_f4 = r.readFloat32(); }
            else if (field_name == "f5") { fld_f5 = r.readFloat64(); }
            else if (field_name == "f6") { fld_f6 = r.readBytes(); }
            else if (field_name == "f7") { fld_f7 = r.readString(); }
            else if (field_name == "f8") { fld_f8 = r.readBool(); }
            else if (field_name == "f9") { fld_f9 = static_cast<std::int8_t>(r.readInt32()); }
            else if (field_name == "f10") { fld_f10 = static_cast<std::int16_t>(r.readInt32()); }
            else if (field_name == "f11") { fld_f11 = r.readInt32(); }
            else if (field_name == "f12") { fld_f12 = r.readInt64(); }
            else if (field_name == "f13") { fld_f13 = static_cast<std::uint8_t>(r.readUint32()); }
            else if (field_name == "f14") { fld_f14 = static_cast<std::uint16_t>(r.readUint32()); }
            else if (field_name == "f15") { fld_f15 = r.readUint32(); }
            else if (field_name == "f16") { fld_f16 = r.readUint64(); }
            else if (field_name == "f17") { fld_f17 = r.readFloat32(); }
            else if (field_name == "f18") { fld_f18 = r.readFloat64(); }
            else if (field_name == "f19") { fld_f19 = r.readBytes(); }
            else if (field_name == "f20") { fld_f20 = r.readString(); }
            else if (field_name == "f21") { fld_f21 = r.readBool(); }
            else if (field_name == "f22") { fld_f22 = static_cast<std::int8_t>(r.readInt32()); }
            else if (field_name == "f23") { fld_f23 = static_cast<std::int16_t>(r.readInt32()); }
            else if (field_name == "f24") { fld_f24 = r.readInt32(); }
            else if (field_name == "f25") { fld_f25 = r.readInt64(); }
            else { r.skip(); }
        }
        r.endObject();
        return Wide25{fld_f1, fld_f2, fld_f3, fld_f4, fld_f5, fld_f6, fld_f7, fld_f8, fld_f9, fld_f10, fld_f11, fld_f12, fld_f13, fld_f14, fld_f15, fld_f16, fld_f17, fld_f18, fld_f19, fld_f20, fld_f21, fld_f22, fld_f23, fld_f24, fld_f25};
    }
};

export struct Wide30 {
    bool f1_;
    std::int8_t f2_;
    std::int16_t f3_;
    std::int32_t f4_;
    std::int64_t f5_;
    std::uint8_t f6_;
    std::uint16_t f7_;
    std::uint32_t f8_;
    std::uint64_t f9_;
    float f10_;
    double f11_;
    std::vector<std::uint8_t> f12_;
    std::string f13_;
    bool f14_;
    std::int8_t f15_;
    std::int16_t f16_;
    std::int32_t f17_;
    std::int64_t f18_;
    std::uint8_t f19_;
    std::uint16_t f20_;
    std::uint32_t f21_;
    std::uint64_t f22_;
    float f23_;
    double f24_;
    std::vector<std::uint8_t> f25_;
    std::string f26_;
    bool f27_;
    std::int8_t f28_;
    std::int16_t f29_;
    std::int32_t f30_;
};

export inline void write_wide30(specodec::SpecWriter& w, const Wide30& obj) {
    w.beginObject(30);
    w.writeField("f1"); w.writeBool(obj.f1_);;
    w.writeField("f2"); w.writeInt32(static_cast<std::int32_t>(obj.f2_));;
    w.writeField("f3"); w.writeInt32(static_cast<std::int32_t>(obj.f3_));;
    w.writeField("f4"); w.writeInt32(obj.f4_);;
    w.writeField("f5"); w.writeInt64(obj.f5_);;
    w.writeField("f6"); w.writeUint32(static_cast<std::uint32_t>(obj.f6_));;
    w.writeField("f7"); w.writeUint32(static_cast<std::uint32_t>(obj.f7_));;
    w.writeField("f8"); w.writeUint32(obj.f8_);;
    w.writeField("f9"); w.writeUint64(obj.f9_);;
    w.writeField("f10"); w.writeFloat32(obj.f10_);;
    w.writeField("f11"); w.writeFloat64(obj.f11_);;
    w.writeField("f12"); w.writeBytes(obj.f12_);;
    w.writeField("f13"); w.writeString(obj.f13_);;
    w.writeField("f14"); w.writeBool(obj.f14_);;
    w.writeField("f15"); w.writeInt32(static_cast<std::int32_t>(obj.f15_));;
    w.writeField("f16"); w.writeInt32(static_cast<std::int32_t>(obj.f16_));;
    w.writeField("f17"); w.writeInt32(obj.f17_);;
    w.writeField("f18"); w.writeInt64(obj.f18_);;
    w.writeField("f19"); w.writeUint32(static_cast<std::uint32_t>(obj.f19_));;
    w.writeField("f20"); w.writeUint32(static_cast<std::uint32_t>(obj.f20_));;
    w.writeField("f21"); w.writeUint32(obj.f21_);;
    w.writeField("f22"); w.writeUint64(obj.f22_);;
    w.writeField("f23"); w.writeFloat32(obj.f23_);;
    w.writeField("f24"); w.writeFloat64(obj.f24_);;
    w.writeField("f25"); w.writeBytes(obj.f25_);;
    w.writeField("f26"); w.writeString(obj.f26_);;
    w.writeField("f27"); w.writeBool(obj.f27_);;
    w.writeField("f28"); w.writeInt32(static_cast<std::int32_t>(obj.f28_));;
    w.writeField("f29"); w.writeInt32(static_cast<std::int32_t>(obj.f29_));;
    w.writeField("f30"); w.writeInt32(obj.f30_);;
    w.endObject();
}

export inline specodec::SpecCodec<Wide30> Wide30Codec = {
    .encode = [](specodec::SpecWriter& w, const Wide30& obj) { write_wide30(w, obj); },
    .decode = [](specodec::SpecReader& r) -> Wide30 {
        bool fld_f1 = false;
        std::int8_t fld_f2 = 0;
        std::int16_t fld_f3 = 0;
        std::int32_t fld_f4 = 0;
        std::int64_t fld_f5 = 0LL;
        std::uint8_t fld_f6 = 0u;
        std::uint16_t fld_f7 = 0u;
        std::uint32_t fld_f8 = 0u;
        std::uint64_t fld_f9 = 0ULL;
        float fld_f10 = 0.0f;
        double fld_f11 = 0.0;
        std::vector<std::uint8_t> fld_f12 = {};
        std::string fld_f13 = "";
        bool fld_f14 = false;
        std::int8_t fld_f15 = 0;
        std::int16_t fld_f16 = 0;
        std::int32_t fld_f17 = 0;
        std::int64_t fld_f18 = 0LL;
        std::uint8_t fld_f19 = 0u;
        std::uint16_t fld_f20 = 0u;
        std::uint32_t fld_f21 = 0u;
        std::uint64_t fld_f22 = 0ULL;
        float fld_f23 = 0.0f;
        double fld_f24 = 0.0;
        std::vector<std::uint8_t> fld_f25 = {};
        std::string fld_f26 = "";
        bool fld_f27 = false;
        std::int8_t fld_f28 = 0;
        std::int16_t fld_f29 = 0;
        std::int32_t fld_f30 = 0;
        r.beginObject();
        while (r.hasNextField()) {
            auto field_name = r.readFieldName();
            if (field_name == "f1") { fld_f1 = r.readBool(); }
            else if (field_name == "f2") { fld_f2 = static_cast<std::int8_t>(r.readInt32()); }
            else if (field_name == "f3") { fld_f3 = static_cast<std::int16_t>(r.readInt32()); }
            else if (field_name == "f4") { fld_f4 = r.readInt32(); }
            else if (field_name == "f5") { fld_f5 = r.readInt64(); }
            else if (field_name == "f6") { fld_f6 = static_cast<std::uint8_t>(r.readUint32()); }
            else if (field_name == "f7") { fld_f7 = static_cast<std::uint16_t>(r.readUint32()); }
            else if (field_name == "f8") { fld_f8 = r.readUint32(); }
            else if (field_name == "f9") { fld_f9 = r.readUint64(); }
            else if (field_name == "f10") { fld_f10 = r.readFloat32(); }
            else if (field_name == "f11") { fld_f11 = r.readFloat64(); }
            else if (field_name == "f12") { fld_f12 = r.readBytes(); }
            else if (field_name == "f13") { fld_f13 = r.readString(); }
            else if (field_name == "f14") { fld_f14 = r.readBool(); }
            else if (field_name == "f15") { fld_f15 = static_cast<std::int8_t>(r.readInt32()); }
            else if (field_name == "f16") { fld_f16 = static_cast<std::int16_t>(r.readInt32()); }
            else if (field_name == "f17") { fld_f17 = r.readInt32(); }
            else if (field_name == "f18") { fld_f18 = r.readInt64(); }
            else if (field_name == "f19") { fld_f19 = static_cast<std::uint8_t>(r.readUint32()); }
            else if (field_name == "f20") { fld_f20 = static_cast<std::uint16_t>(r.readUint32()); }
            else if (field_name == "f21") { fld_f21 = r.readUint32(); }
            else if (field_name == "f22") { fld_f22 = r.readUint64(); }
            else if (field_name == "f23") { fld_f23 = r.readFloat32(); }
            else if (field_name == "f24") { fld_f24 = r.readFloat64(); }
            else if (field_name == "f25") { fld_f25 = r.readBytes(); }
            else if (field_name == "f26") { fld_f26 = r.readString(); }
            else if (field_name == "f27") { fld_f27 = r.readBool(); }
            else if (field_name == "f28") { fld_f28 = static_cast<std::int8_t>(r.readInt32()); }
            else if (field_name == "f29") { fld_f29 = static_cast<std::int16_t>(r.readInt32()); }
            else if (field_name == "f30") { fld_f30 = r.readInt32(); }
            else { r.skip(); }
        }
        r.endObject();
        return Wide30{fld_f1, fld_f2, fld_f3, fld_f4, fld_f5, fld_f6, fld_f7, fld_f8, fld_f9, fld_f10, fld_f11, fld_f12, fld_f13, fld_f14, fld_f15, fld_f16, fld_f17, fld_f18, fld_f19, fld_f20, fld_f21, fld_f22, fld_f23, fld_f24, fld_f25, fld_f26, fld_f27, fld_f28, fld_f29, fld_f30};
    }
};

export struct Wide35 {
    std::uint32_t f1_;
    std::uint64_t f2_;
    float f3_;
    double f4_;
    std::vector<std::uint8_t> f5_;
    std::string f6_;
    bool f7_;
    std::int8_t f8_;
    std::int16_t f9_;
    std::int32_t f10_;
    std::int64_t f11_;
    std::uint8_t f12_;
    std::uint16_t f13_;
    std::uint32_t f14_;
    std::uint64_t f15_;
    float f16_;
    double f17_;
    std::vector<std::uint8_t> f18_;
    std::string f19_;
    bool f20_;
    std::int8_t f21_;
    std::int16_t f22_;
    std::int32_t f23_;
    std::int64_t f24_;
    std::uint8_t f25_;
    std::uint16_t f26_;
    std::uint32_t f27_;
    std::uint64_t f28_;
    float f29_;
    double f30_;
    std::vector<std::uint8_t> f31_;
    std::string f32_;
    bool f33_;
    std::int8_t f34_;
    std::int16_t f35_;
};

export inline void write_wide35(specodec::SpecWriter& w, const Wide35& obj) {
    w.beginObject(35);
    w.writeField("f1"); w.writeUint32(obj.f1_);;
    w.writeField("f2"); w.writeUint64(obj.f2_);;
    w.writeField("f3"); w.writeFloat32(obj.f3_);;
    w.writeField("f4"); w.writeFloat64(obj.f4_);;
    w.writeField("f5"); w.writeBytes(obj.f5_);;
    w.writeField("f6"); w.writeString(obj.f6_);;
    w.writeField("f7"); w.writeBool(obj.f7_);;
    w.writeField("f8"); w.writeInt32(static_cast<std::int32_t>(obj.f8_));;
    w.writeField("f9"); w.writeInt32(static_cast<std::int32_t>(obj.f9_));;
    w.writeField("f10"); w.writeInt32(obj.f10_);;
    w.writeField("f11"); w.writeInt64(obj.f11_);;
    w.writeField("f12"); w.writeUint32(static_cast<std::uint32_t>(obj.f12_));;
    w.writeField("f13"); w.writeUint32(static_cast<std::uint32_t>(obj.f13_));;
    w.writeField("f14"); w.writeUint32(obj.f14_);;
    w.writeField("f15"); w.writeUint64(obj.f15_);;
    w.writeField("f16"); w.writeFloat32(obj.f16_);;
    w.writeField("f17"); w.writeFloat64(obj.f17_);;
    w.writeField("f18"); w.writeBytes(obj.f18_);;
    w.writeField("f19"); w.writeString(obj.f19_);;
    w.writeField("f20"); w.writeBool(obj.f20_);;
    w.writeField("f21"); w.writeInt32(static_cast<std::int32_t>(obj.f21_));;
    w.writeField("f22"); w.writeInt32(static_cast<std::int32_t>(obj.f22_));;
    w.writeField("f23"); w.writeInt32(obj.f23_);;
    w.writeField("f24"); w.writeInt64(obj.f24_);;
    w.writeField("f25"); w.writeUint32(static_cast<std::uint32_t>(obj.f25_));;
    w.writeField("f26"); w.writeUint32(static_cast<std::uint32_t>(obj.f26_));;
    w.writeField("f27"); w.writeUint32(obj.f27_);;
    w.writeField("f28"); w.writeUint64(obj.f28_);;
    w.writeField("f29"); w.writeFloat32(obj.f29_);;
    w.writeField("f30"); w.writeFloat64(obj.f30_);;
    w.writeField("f31"); w.writeBytes(obj.f31_);;
    w.writeField("f32"); w.writeString(obj.f32_);;
    w.writeField("f33"); w.writeBool(obj.f33_);;
    w.writeField("f34"); w.writeInt32(static_cast<std::int32_t>(obj.f34_));;
    w.writeField("f35"); w.writeInt32(static_cast<std::int32_t>(obj.f35_));;
    w.endObject();
}

export inline specodec::SpecCodec<Wide35> Wide35Codec = {
    .encode = [](specodec::SpecWriter& w, const Wide35& obj) { write_wide35(w, obj); },
    .decode = [](specodec::SpecReader& r) -> Wide35 {
        std::uint32_t fld_f1 = 0u;
        std::uint64_t fld_f2 = 0ULL;
        float fld_f3 = 0.0f;
        double fld_f4 = 0.0;
        std::vector<std::uint8_t> fld_f5 = {};
        std::string fld_f6 = "";
        bool fld_f7 = false;
        std::int8_t fld_f8 = 0;
        std::int16_t fld_f9 = 0;
        std::int32_t fld_f10 = 0;
        std::int64_t fld_f11 = 0LL;
        std::uint8_t fld_f12 = 0u;
        std::uint16_t fld_f13 = 0u;
        std::uint32_t fld_f14 = 0u;
        std::uint64_t fld_f15 = 0ULL;
        float fld_f16 = 0.0f;
        double fld_f17 = 0.0;
        std::vector<std::uint8_t> fld_f18 = {};
        std::string fld_f19 = "";
        bool fld_f20 = false;
        std::int8_t fld_f21 = 0;
        std::int16_t fld_f22 = 0;
        std::int32_t fld_f23 = 0;
        std::int64_t fld_f24 = 0LL;
        std::uint8_t fld_f25 = 0u;
        std::uint16_t fld_f26 = 0u;
        std::uint32_t fld_f27 = 0u;
        std::uint64_t fld_f28 = 0ULL;
        float fld_f29 = 0.0f;
        double fld_f30 = 0.0;
        std::vector<std::uint8_t> fld_f31 = {};
        std::string fld_f32 = "";
        bool fld_f33 = false;
        std::int8_t fld_f34 = 0;
        std::int16_t fld_f35 = 0;
        r.beginObject();
        while (r.hasNextField()) {
            auto field_name = r.readFieldName();
            if (field_name == "f1") { fld_f1 = r.readUint32(); }
            else if (field_name == "f2") { fld_f2 = r.readUint64(); }
            else if (field_name == "f3") { fld_f3 = r.readFloat32(); }
            else if (field_name == "f4") { fld_f4 = r.readFloat64(); }
            else if (field_name == "f5") { fld_f5 = r.readBytes(); }
            else if (field_name == "f6") { fld_f6 = r.readString(); }
            else if (field_name == "f7") { fld_f7 = r.readBool(); }
            else if (field_name == "f8") { fld_f8 = static_cast<std::int8_t>(r.readInt32()); }
            else if (field_name == "f9") { fld_f9 = static_cast<std::int16_t>(r.readInt32()); }
            else if (field_name == "f10") { fld_f10 = r.readInt32(); }
            else if (field_name == "f11") { fld_f11 = r.readInt64(); }
            else if (field_name == "f12") { fld_f12 = static_cast<std::uint8_t>(r.readUint32()); }
            else if (field_name == "f13") { fld_f13 = static_cast<std::uint16_t>(r.readUint32()); }
            else if (field_name == "f14") { fld_f14 = r.readUint32(); }
            else if (field_name == "f15") { fld_f15 = r.readUint64(); }
            else if (field_name == "f16") { fld_f16 = r.readFloat32(); }
            else if (field_name == "f17") { fld_f17 = r.readFloat64(); }
            else if (field_name == "f18") { fld_f18 = r.readBytes(); }
            else if (field_name == "f19") { fld_f19 = r.readString(); }
            else if (field_name == "f20") { fld_f20 = r.readBool(); }
            else if (field_name == "f21") { fld_f21 = static_cast<std::int8_t>(r.readInt32()); }
            else if (field_name == "f22") { fld_f22 = static_cast<std::int16_t>(r.readInt32()); }
            else if (field_name == "f23") { fld_f23 = r.readInt32(); }
            else if (field_name == "f24") { fld_f24 = r.readInt64(); }
            else if (field_name == "f25") { fld_f25 = static_cast<std::uint8_t>(r.readUint32()); }
            else if (field_name == "f26") { fld_f26 = static_cast<std::uint16_t>(r.readUint32()); }
            else if (field_name == "f27") { fld_f27 = r.readUint32(); }
            else if (field_name == "f28") { fld_f28 = r.readUint64(); }
            else if (field_name == "f29") { fld_f29 = r.readFloat32(); }
            else if (field_name == "f30") { fld_f30 = r.readFloat64(); }
            else if (field_name == "f31") { fld_f31 = r.readBytes(); }
            else if (field_name == "f32") { fld_f32 = r.readString(); }
            else if (field_name == "f33") { fld_f33 = r.readBool(); }
            else if (field_name == "f34") { fld_f34 = static_cast<std::int8_t>(r.readInt32()); }
            else if (field_name == "f35") { fld_f35 = static_cast<std::int16_t>(r.readInt32()); }
            else { r.skip(); }
        }
        r.endObject();
        return Wide35{fld_f1, fld_f2, fld_f3, fld_f4, fld_f5, fld_f6, fld_f7, fld_f8, fld_f9, fld_f10, fld_f11, fld_f12, fld_f13, fld_f14, fld_f15, fld_f16, fld_f17, fld_f18, fld_f19, fld_f20, fld_f21, fld_f22, fld_f23, fld_f24, fld_f25, fld_f26, fld_f27, fld_f28, fld_f29, fld_f30, fld_f31, fld_f32, fld_f33, fld_f34, fld_f35};
    }
};

export struct Wide40 {
    std::int8_t f1_;
    std::int16_t f2_;
    std::int32_t f3_;
    std::int64_t f4_;
    std::uint8_t f5_;
    std::uint16_t f6_;
    std::uint32_t f7_;
    std::uint64_t f8_;
    float f9_;
    double f10_;
    std::vector<std::uint8_t> f11_;
    std::string f12_;
    bool f13_;
    std::int8_t f14_;
    std::int16_t f15_;
    std::int32_t f16_;
    std::int64_t f17_;
    std::uint8_t f18_;
    std::uint16_t f19_;
    std::uint32_t f20_;
    std::uint64_t f21_;
    float f22_;
    double f23_;
    std::vector<std::uint8_t> f24_;
    std::string f25_;
    bool f26_;
    std::int8_t f27_;
    std::int16_t f28_;
    std::int32_t f29_;
    std::int64_t f30_;
    std::uint8_t f31_;
    std::uint16_t f32_;
    std::uint32_t f33_;
    std::uint64_t f34_;
    float f35_;
    double f36_;
    std::vector<std::uint8_t> f37_;
    std::string f38_;
    bool f39_;
    std::int8_t f40_;
};

export inline void write_wide40(specodec::SpecWriter& w, const Wide40& obj) {
    w.beginObject(40);
    w.writeField("f1"); w.writeInt32(static_cast<std::int32_t>(obj.f1_));;
    w.writeField("f2"); w.writeInt32(static_cast<std::int32_t>(obj.f2_));;
    w.writeField("f3"); w.writeInt32(obj.f3_);;
    w.writeField("f4"); w.writeInt64(obj.f4_);;
    w.writeField("f5"); w.writeUint32(static_cast<std::uint32_t>(obj.f5_));;
    w.writeField("f6"); w.writeUint32(static_cast<std::uint32_t>(obj.f6_));;
    w.writeField("f7"); w.writeUint32(obj.f7_);;
    w.writeField("f8"); w.writeUint64(obj.f8_);;
    w.writeField("f9"); w.writeFloat32(obj.f9_);;
    w.writeField("f10"); w.writeFloat64(obj.f10_);;
    w.writeField("f11"); w.writeBytes(obj.f11_);;
    w.writeField("f12"); w.writeString(obj.f12_);;
    w.writeField("f13"); w.writeBool(obj.f13_);;
    w.writeField("f14"); w.writeInt32(static_cast<std::int32_t>(obj.f14_));;
    w.writeField("f15"); w.writeInt32(static_cast<std::int32_t>(obj.f15_));;
    w.writeField("f16"); w.writeInt32(obj.f16_);;
    w.writeField("f17"); w.writeInt64(obj.f17_);;
    w.writeField("f18"); w.writeUint32(static_cast<std::uint32_t>(obj.f18_));;
    w.writeField("f19"); w.writeUint32(static_cast<std::uint32_t>(obj.f19_));;
    w.writeField("f20"); w.writeUint32(obj.f20_);;
    w.writeField("f21"); w.writeUint64(obj.f21_);;
    w.writeField("f22"); w.writeFloat32(obj.f22_);;
    w.writeField("f23"); w.writeFloat64(obj.f23_);;
    w.writeField("f24"); w.writeBytes(obj.f24_);;
    w.writeField("f25"); w.writeString(obj.f25_);;
    w.writeField("f26"); w.writeBool(obj.f26_);;
    w.writeField("f27"); w.writeInt32(static_cast<std::int32_t>(obj.f27_));;
    w.writeField("f28"); w.writeInt32(static_cast<std::int32_t>(obj.f28_));;
    w.writeField("f29"); w.writeInt32(obj.f29_);;
    w.writeField("f30"); w.writeInt64(obj.f30_);;
    w.writeField("f31"); w.writeUint32(static_cast<std::uint32_t>(obj.f31_));;
    w.writeField("f32"); w.writeUint32(static_cast<std::uint32_t>(obj.f32_));;
    w.writeField("f33"); w.writeUint32(obj.f33_);;
    w.writeField("f34"); w.writeUint64(obj.f34_);;
    w.writeField("f35"); w.writeFloat32(obj.f35_);;
    w.writeField("f36"); w.writeFloat64(obj.f36_);;
    w.writeField("f37"); w.writeBytes(obj.f37_);;
    w.writeField("f38"); w.writeString(obj.f38_);;
    w.writeField("f39"); w.writeBool(obj.f39_);;
    w.writeField("f40"); w.writeInt32(static_cast<std::int32_t>(obj.f40_));;
    w.endObject();
}

export inline specodec::SpecCodec<Wide40> Wide40Codec = {
    .encode = [](specodec::SpecWriter& w, const Wide40& obj) { write_wide40(w, obj); },
    .decode = [](specodec::SpecReader& r) -> Wide40 {
        std::int8_t fld_f1 = 0;
        std::int16_t fld_f2 = 0;
        std::int32_t fld_f3 = 0;
        std::int64_t fld_f4 = 0LL;
        std::uint8_t fld_f5 = 0u;
        std::uint16_t fld_f6 = 0u;
        std::uint32_t fld_f7 = 0u;
        std::uint64_t fld_f8 = 0ULL;
        float fld_f9 = 0.0f;
        double fld_f10 = 0.0;
        std::vector<std::uint8_t> fld_f11 = {};
        std::string fld_f12 = "";
        bool fld_f13 = false;
        std::int8_t fld_f14 = 0;
        std::int16_t fld_f15 = 0;
        std::int32_t fld_f16 = 0;
        std::int64_t fld_f17 = 0LL;
        std::uint8_t fld_f18 = 0u;
        std::uint16_t fld_f19 = 0u;
        std::uint32_t fld_f20 = 0u;
        std::uint64_t fld_f21 = 0ULL;
        float fld_f22 = 0.0f;
        double fld_f23 = 0.0;
        std::vector<std::uint8_t> fld_f24 = {};
        std::string fld_f25 = "";
        bool fld_f26 = false;
        std::int8_t fld_f27 = 0;
        std::int16_t fld_f28 = 0;
        std::int32_t fld_f29 = 0;
        std::int64_t fld_f30 = 0LL;
        std::uint8_t fld_f31 = 0u;
        std::uint16_t fld_f32 = 0u;
        std::uint32_t fld_f33 = 0u;
        std::uint64_t fld_f34 = 0ULL;
        float fld_f35 = 0.0f;
        double fld_f36 = 0.0;
        std::vector<std::uint8_t> fld_f37 = {};
        std::string fld_f38 = "";
        bool fld_f39 = false;
        std::int8_t fld_f40 = 0;
        r.beginObject();
        while (r.hasNextField()) {
            auto field_name = r.readFieldName();
            if (field_name == "f1") { fld_f1 = static_cast<std::int8_t>(r.readInt32()); }
            else if (field_name == "f2") { fld_f2 = static_cast<std::int16_t>(r.readInt32()); }
            else if (field_name == "f3") { fld_f3 = r.readInt32(); }
            else if (field_name == "f4") { fld_f4 = r.readInt64(); }
            else if (field_name == "f5") { fld_f5 = static_cast<std::uint8_t>(r.readUint32()); }
            else if (field_name == "f6") { fld_f6 = static_cast<std::uint16_t>(r.readUint32()); }
            else if (field_name == "f7") { fld_f7 = r.readUint32(); }
            else if (field_name == "f8") { fld_f8 = r.readUint64(); }
            else if (field_name == "f9") { fld_f9 = r.readFloat32(); }
            else if (field_name == "f10") { fld_f10 = r.readFloat64(); }
            else if (field_name == "f11") { fld_f11 = r.readBytes(); }
            else if (field_name == "f12") { fld_f12 = r.readString(); }
            else if (field_name == "f13") { fld_f13 = r.readBool(); }
            else if (field_name == "f14") { fld_f14 = static_cast<std::int8_t>(r.readInt32()); }
            else if (field_name == "f15") { fld_f15 = static_cast<std::int16_t>(r.readInt32()); }
            else if (field_name == "f16") { fld_f16 = r.readInt32(); }
            else if (field_name == "f17") { fld_f17 = r.readInt64(); }
            else if (field_name == "f18") { fld_f18 = static_cast<std::uint8_t>(r.readUint32()); }
            else if (field_name == "f19") { fld_f19 = static_cast<std::uint16_t>(r.readUint32()); }
            else if (field_name == "f20") { fld_f20 = r.readUint32(); }
            else if (field_name == "f21") { fld_f21 = r.readUint64(); }
            else if (field_name == "f22") { fld_f22 = r.readFloat32(); }
            else if (field_name == "f23") { fld_f23 = r.readFloat64(); }
            else if (field_name == "f24") { fld_f24 = r.readBytes(); }
            else if (field_name == "f25") { fld_f25 = r.readString(); }
            else if (field_name == "f26") { fld_f26 = r.readBool(); }
            else if (field_name == "f27") { fld_f27 = static_cast<std::int8_t>(r.readInt32()); }
            else if (field_name == "f28") { fld_f28 = static_cast<std::int16_t>(r.readInt32()); }
            else if (field_name == "f29") { fld_f29 = r.readInt32(); }
            else if (field_name == "f30") { fld_f30 = r.readInt64(); }
            else if (field_name == "f31") { fld_f31 = static_cast<std::uint8_t>(r.readUint32()); }
            else if (field_name == "f32") { fld_f32 = static_cast<std::uint16_t>(r.readUint32()); }
            else if (field_name == "f33") { fld_f33 = r.readUint32(); }
            else if (field_name == "f34") { fld_f34 = r.readUint64(); }
            else if (field_name == "f35") { fld_f35 = r.readFloat32(); }
            else if (field_name == "f36") { fld_f36 = r.readFloat64(); }
            else if (field_name == "f37") { fld_f37 = r.readBytes(); }
            else if (field_name == "f38") { fld_f38 = r.readString(); }
            else if (field_name == "f39") { fld_f39 = r.readBool(); }
            else if (field_name == "f40") { fld_f40 = static_cast<std::int8_t>(r.readInt32()); }
            else { r.skip(); }
        }
        r.endObject();
        return Wide40{fld_f1, fld_f2, fld_f3, fld_f4, fld_f5, fld_f6, fld_f7, fld_f8, fld_f9, fld_f10, fld_f11, fld_f12, fld_f13, fld_f14, fld_f15, fld_f16, fld_f17, fld_f18, fld_f19, fld_f20, fld_f21, fld_f22, fld_f23, fld_f24, fld_f25, fld_f26, fld_f27, fld_f28, fld_f29, fld_f30, fld_f31, fld_f32, fld_f33, fld_f34, fld_f35, fld_f36, fld_f37, fld_f38, fld_f39, fld_f40};
    }
};

} // namespace all_types_wide