// Generated by @specodec/typespec-emitter-cpp. DO NOT EDIT.
export module all_types_mixed;
import std;
import specodec;
import all_types;
using namespace all_types;

namespace all_types_mixed {

export struct ModelArr1 {
    std::vector<Inner> points_;
};

export inline void write_model_arr1(specodec::SpecWriter& w, const ModelArr1& obj) {
    w.beginObject(1);
    w.writeField("points"); 
        w.beginArray(obj.points_.size());
        for (const auto& elem : obj.points_) { w.nextElement(); write_inner(w, elem); }
        w.endArray();
    w.endObject();
}

export inline specodec::SpecCodec<ModelArr1> ModelArr1Codec = {
    .encode = [](specodec::SpecWriter& w, const ModelArr1& obj) { write_model_arr1(w, obj); },
    .decode = [](specodec::SpecReader& r) -> ModelArr1 {
        std::vector<Inner> fld_points = {};
        r.beginObject();
        while (r.hasNextField()) {
            auto field_name = r.readFieldName();
            if (field_name == "points") { fld_points = [&]() {
    std::vector<Inner> result;
    r.beginArray();
    while (r.hasNextElement()) { result.push_back(InnerCodec.decode(r)); }
    r.endArray();
    return result;
}(); }
            else { r.skip(); }
        }
        r.endObject();
        return ModelArr1{fld_points};
    }
};

export struct ModelArr2 {
    std::vector<Coord> coords_;
};

export inline void write_model_arr2(specodec::SpecWriter& w, const ModelArr2& obj) {
    w.beginObject(1);
    w.writeField("coords"); 
        w.beginArray(obj.coords_.size());
        for (const auto& elem : obj.coords_) { w.nextElement(); write_coord(w, elem); }
        w.endArray();
    w.endObject();
}

export inline specodec::SpecCodec<ModelArr2> ModelArr2Codec = {
    .encode = [](specodec::SpecWriter& w, const ModelArr2& obj) { write_model_arr2(w, obj); },
    .decode = [](specodec::SpecReader& r) -> ModelArr2 {
        std::vector<Coord> fld_coords = {};
        r.beginObject();
        while (r.hasNextField()) {
            auto field_name = r.readFieldName();
            if (field_name == "coords") { fld_coords = [&]() {
    std::vector<Coord> result;
    r.beginArray();
    while (r.hasNextElement()) { result.push_back(CoordCodec.decode(r)); }
    r.endArray();
    return result;
}(); }
            else { r.skip(); }
        }
        r.endObject();
        return ModelArr2{fld_coords};
    }
};

export struct ModelArr3 {
    std::vector<IdVal> items_;
    std::string tag_;
};

export inline void write_model_arr3(specodec::SpecWriter& w, const ModelArr3& obj) {
    w.beginObject(2);
    w.writeField("items"); 
        w.beginArray(obj.items_.size());
        for (const auto& elem : obj.items_) { w.nextElement(); write_id_val(w, elem); }
        w.endArray();
    w.writeField("tag"); w.writeString(obj.tag_);;
    w.endObject();
}

export inline specodec::SpecCodec<ModelArr3> ModelArr3Codec = {
    .encode = [](specodec::SpecWriter& w, const ModelArr3& obj) { write_model_arr3(w, obj); },
    .decode = [](specodec::SpecReader& r) -> ModelArr3 {
        std::vector<IdVal> fld_items = {};
        std::string fld_tag = "";
        r.beginObject();
        while (r.hasNextField()) {
            auto field_name = r.readFieldName();
            if (field_name == "items") { fld_items = [&]() {
    std::vector<IdVal> result;
    r.beginArray();
    while (r.hasNextElement()) { result.push_back(IdValCodec.decode(r)); }
    r.endArray();
    return result;
}(); }
            else if (field_name == "tag") { fld_tag = r.readString(); }
            else { r.skip(); }
        }
        r.endObject();
        return ModelArr3{fld_items, fld_tag};
    }
};

export struct ModelArr4 {
    std::vector<Label> labels_;
    std::int32_t count_;
};

export inline void write_model_arr4(specodec::SpecWriter& w, const ModelArr4& obj) {
    w.beginObject(2);
    w.writeField("labels"); 
        w.beginArray(obj.labels_.size());
        for (const auto& elem : obj.labels_) { w.nextElement(); write_label(w, elem); }
        w.endArray();
    w.writeField("count"); w.writeInt32(obj.count_);;
    w.endObject();
}

export inline specodec::SpecCodec<ModelArr4> ModelArr4Codec = {
    .encode = [](specodec::SpecWriter& w, const ModelArr4& obj) { write_model_arr4(w, obj); },
    .decode = [](specodec::SpecReader& r) -> ModelArr4 {
        std::vector<Label> fld_labels = {};
        std::int32_t fld_count = 0;
        r.beginObject();
        while (r.hasNextField()) {
            auto field_name = r.readFieldName();
            if (field_name == "labels") { fld_labels = [&]() {
    std::vector<Label> result;
    r.beginArray();
    while (r.hasNextElement()) { result.push_back(LabelCodec.decode(r)); }
    r.endArray();
    return result;
}(); }
            else if (field_name == "count") { fld_count = r.readInt32(); }
            else { r.skip(); }
        }
        r.endObject();
        return ModelArr4{fld_labels, fld_count};
    }
};

export struct ModelArr5 {
    std::vector<Money> arr_;
    std::vector<Addr> bs_;
};

export inline void write_model_arr5(specodec::SpecWriter& w, const ModelArr5& obj) {
    w.beginObject(2);
    w.writeField("arr"); 
        w.beginArray(obj.arr_.size());
        for (const auto& elem : obj.arr_) { w.nextElement(); write_money(w, elem); }
        w.endArray();
    w.writeField("bs"); 
        w.beginArray(obj.bs_.size());
        for (const auto& elem : obj.bs_) { w.nextElement(); write_addr(w, elem); }
        w.endArray();
    w.endObject();
}

export inline specodec::SpecCodec<ModelArr5> ModelArr5Codec = {
    .encode = [](specodec::SpecWriter& w, const ModelArr5& obj) { write_model_arr5(w, obj); },
    .decode = [](specodec::SpecReader& r) -> ModelArr5 {
        std::vector<Money> fld_arr = {};
        std::vector<Addr> fld_bs = {};
        r.beginObject();
        while (r.hasNextField()) {
            auto field_name = r.readFieldName();
            if (field_name == "arr") { fld_arr = [&]() {
    std::vector<Money> result;
    r.beginArray();
    while (r.hasNextElement()) { result.push_back(MoneyCodec.decode(r)); }
    r.endArray();
    return result;
}(); }
            else if (field_name == "bs") { fld_bs = [&]() {
    std::vector<Addr> result;
    r.beginArray();
    while (r.hasNextElement()) { result.push_back(AddrCodec.decode(r)); }
    r.endArray();
    return result;
}(); }
            else { r.skip(); }
        }
        r.endObject();
        return ModelArr5{fld_arr, fld_bs};
    }
};

export struct Mix01 {
    std::string name_;
    std::int32_t value_;
    Inner point_;
};

export inline void write_mix01(specodec::SpecWriter& w, const Mix01& obj) {
    w.beginObject(3);
    w.writeField("name"); w.writeString(obj.name_);;
    w.writeField("value"); w.writeInt32(obj.value_);;
    w.writeField("point"); write_inner(w, obj.point_);;
    w.endObject();
}

export inline specodec::SpecCodec<Mix01> Mix01Codec = {
    .encode = [](specodec::SpecWriter& w, const Mix01& obj) { write_mix01(w, obj); },
    .decode = [](specodec::SpecReader& r) -> Mix01 {
        std::string fld_name = "";
        std::int32_t fld_value = 0;
        Inner fld_point = {};
        r.beginObject();
        while (r.hasNextField()) {
            auto field_name = r.readFieldName();
            if (field_name == "name") { fld_name = r.readString(); }
            else if (field_name == "value") { fld_value = r.readInt32(); }
            else if (field_name == "point") { fld_point = InnerCodec.decode(r); }
            else { r.skip(); }
        }
        r.endObject();
        return Mix01{fld_name, fld_value, fld_point};
    }
};

export struct Mix02 {
    std::string id_;
    Coord loc_;
    std::vector<std::string> tags_;
};

export inline void write_mix02(specodec::SpecWriter& w, const Mix02& obj) {
    w.beginObject(3);
    w.writeField("id"); w.writeString(obj.id_);;
    w.writeField("loc"); write_coord(w, obj.loc_);;
    w.writeField("tags"); 
        w.beginArray(obj.tags_.size());
        for (const auto& elem : obj.tags_) { w.nextElement(); w.writeString(elem); }
        w.endArray();
    w.endObject();
}

export inline specodec::SpecCodec<Mix02> Mix02Codec = {
    .encode = [](specodec::SpecWriter& w, const Mix02& obj) { write_mix02(w, obj); },
    .decode = [](specodec::SpecReader& r) -> Mix02 {
        std::string fld_id = "";
        Coord fld_loc = {};
        std::vector<std::string> fld_tags = {};
        r.beginObject();
        while (r.hasNextField()) {
            auto field_name = r.readFieldName();
            if (field_name == "id") { fld_id = r.readString(); }
            else if (field_name == "loc") { fld_loc = CoordCodec.decode(r); }
            else if (field_name == "tags") { fld_tags = [&]() {
    std::vector<std::string> result;
    r.beginArray();
    while (r.hasNextElement()) { result.push_back(r.readString()); }
    r.endArray();
    return result;
}(); }
            else { r.skip(); }
        }
        r.endObject();
        return Mix02{fld_id, fld_loc, fld_tags};
    }
};

export struct Mix03 {
    std::string label_;
    Range32 value_range_;
    bool active_;
};

export inline void write_mix03(specodec::SpecWriter& w, const Mix03& obj) {
    w.beginObject(3);
    w.writeField("label"); w.writeString(obj.label_);;
    w.writeField("value_range"); write_range32(w, obj.value_range_);;
    w.writeField("active"); w.writeBool(obj.active_);;
    w.endObject();
}

export inline specodec::SpecCodec<Mix03> Mix03Codec = {
    .encode = [](specodec::SpecWriter& w, const Mix03& obj) { write_mix03(w, obj); },
    .decode = [](specodec::SpecReader& r) -> Mix03 {
        std::string fld_label = "";
        Range32 fld_value_range = {};
        bool fld_active = false;
        r.beginObject();
        while (r.hasNextField()) {
            auto field_name = r.readFieldName();
            if (field_name == "label") { fld_label = r.readString(); }
            else if (field_name == "value_range") { fld_value_range = Range32Codec.decode(r); }
            else if (field_name == "active") { fld_active = r.readBool(); }
            else { r.skip(); }
        }
        r.endObject();
        return Mix03{fld_label, fld_value_range, fld_active};
    }
};

export struct Mix04 {
    std::string title_;
    Money price_;
    bool in_stock_;
    double rating_;
};

export inline void write_mix04(specodec::SpecWriter& w, const Mix04& obj) {
    w.beginObject(4);
    w.writeField("title"); w.writeString(obj.title_);;
    w.writeField("price"); write_money(w, obj.price_);;
    w.writeField("inStock"); w.writeBool(obj.in_stock_);;
    w.writeField("rating"); w.writeFloat64(obj.rating_);;
    w.endObject();
}

export inline specodec::SpecCodec<Mix04> Mix04Codec = {
    .encode = [](specodec::SpecWriter& w, const Mix04& obj) { write_mix04(w, obj); },
    .decode = [](specodec::SpecReader& r) -> Mix04 {
        std::string fld_title = "";
        Money fld_price = {};
        bool fld_in_stock = false;
        double fld_rating = 0.0;
        r.beginObject();
        while (r.hasNextField()) {
            auto field_name = r.readFieldName();
            if (field_name == "title") { fld_title = r.readString(); }
            else if (field_name == "price") { fld_price = MoneyCodec.decode(r); }
            else if (field_name == "inStock") { fld_in_stock = r.readBool(); }
            else if (field_name == "rating") { fld_rating = r.readFloat64(); }
            else { r.skip(); }
        }
        r.endObject();
        return Mix04{fld_title, fld_price, fld_in_stock, fld_rating};
    }
};

export struct Mix05 {
    Addr addr_;
    std::vector<Coord> coords_;
};

export inline void write_mix05(specodec::SpecWriter& w, const Mix05& obj) {
    w.beginObject(2);
    w.writeField("addr"); write_addr(w, obj.addr_);;
    w.writeField("coords"); 
        w.beginArray(obj.coords_.size());
        for (const auto& elem : obj.coords_) { w.nextElement(); write_coord(w, elem); }
        w.endArray();
    w.endObject();
}

export inline specodec::SpecCodec<Mix05> Mix05Codec = {
    .encode = [](specodec::SpecWriter& w, const Mix05& obj) { write_mix05(w, obj); },
    .decode = [](specodec::SpecReader& r) -> Mix05 {
        Addr fld_addr = {};
        std::vector<Coord> fld_coords = {};
        r.beginObject();
        while (r.hasNextField()) {
            auto field_name = r.readFieldName();
            if (field_name == "addr") { fld_addr = AddrCodec.decode(r); }
            else if (field_name == "coords") { fld_coords = [&]() {
    std::vector<Coord> result;
    r.beginArray();
    while (r.hasNextElement()) { result.push_back(CoordCodec.decode(r)); }
    r.endArray();
    return result;
}(); }
            else { r.skip(); }
        }
        r.endObject();
        return Mix05{fld_addr, fld_coords};
    }
};

export struct Mix06 {
    std::string name_;
    std::int32_t age_;
    std::optional<Addr> address_;
    std::optional<std::string> email_;
};

export inline void write_mix06(specodec::SpecWriter& w, const Mix06& obj) {
    int field_count = 2;
    if (obj.address_.has_value()) field_count++;
    if (obj.email_.has_value()) field_count++;
    w.beginObject(field_count);
    w.writeField("name"); w.writeString(obj.name_);;
    w.writeField("age"); w.writeInt32(obj.age_);;
    if (obj.address_.has_value()) { w.writeField("address"); write_addr(w, obj.address_.value());; }
    if (obj.email_.has_value()) { w.writeField("email"); w.writeString(obj.email_.value());; }
    w.endObject();
}

export inline specodec::SpecCodec<Mix06> Mix06Codec = {
    .encode = [](specodec::SpecWriter& w, const Mix06& obj) { write_mix06(w, obj); },
    .decode = [](specodec::SpecReader& r) -> Mix06 {
        std::string fld_name = "";
        std::int32_t fld_age = 0;
        std::optional<Addr> fld_address;
        std::optional<std::string> fld_email;
        r.beginObject();
        while (r.hasNextField()) {
            auto field_name = r.readFieldName();
            if (field_name == "name") { fld_name = r.readString(); }
            else if (field_name == "age") { fld_age = r.readInt32(); }
            else if (field_name == "address") { fld_address = std::optional<Addr>{(r.isNull() ? (r.readNull(), std::optional<Addr>{std::nullopt}) : std::optional<Addr>{AddrCodec.decode(r)})}; }
            else if (field_name == "email") { fld_email = std::optional<std::string>{r.readString()}; }
            else { r.skip(); }
        }
        r.endObject();
        return Mix06{fld_name, fld_age, fld_address, fld_email};
    }
};

export struct Mix07 {
    Point3 origin_;
    Point3 dest_;
    double distance_;
};

export inline void write_mix07(specodec::SpecWriter& w, const Mix07& obj) {
    w.beginObject(3);
    w.writeField("origin"); write_point3(w, obj.origin_);;
    w.writeField("dest"); write_point3(w, obj.dest_);;
    w.writeField("distance"); w.writeFloat64(obj.distance_);;
    w.endObject();
}

export inline specodec::SpecCodec<Mix07> Mix07Codec = {
    .encode = [](specodec::SpecWriter& w, const Mix07& obj) { write_mix07(w, obj); },
    .decode = [](specodec::SpecReader& r) -> Mix07 {
        Point3 fld_origin = {};
        Point3 fld_dest = {};
        double fld_distance = 0.0;
        r.beginObject();
        while (r.hasNextField()) {
            auto field_name = r.readFieldName();
            if (field_name == "origin") { fld_origin = Point3Codec.decode(r); }
            else if (field_name == "dest") { fld_dest = Point3Codec.decode(r); }
            else if (field_name == "distance") { fld_distance = r.readFloat64(); }
            else { r.skip(); }
        }
        r.endObject();
        return Mix07{fld_origin, fld_dest, fld_distance};
    }
};

export struct Mix08 {
    std::vector<std::string> keys_;
    std::vector<std::int32_t> values_;
    std::optional<Label> meta_;
};

export inline void write_mix08(specodec::SpecWriter& w, const Mix08& obj) {
    int field_count = 2;
    if (obj.meta_.has_value()) field_count++;
    w.beginObject(field_count);
    w.writeField("keys"); 
        w.beginArray(obj.keys_.size());
        for (const auto& elem : obj.keys_) { w.nextElement(); w.writeString(elem); }
        w.endArray();
    w.writeField("values"); 
        w.beginArray(obj.values_.size());
        for (const auto& elem : obj.values_) { w.nextElement(); w.writeInt32(elem); }
        w.endArray();
    if (obj.meta_.has_value()) { w.writeField("meta"); write_label(w, obj.meta_.value());; }
    w.endObject();
}

export inline specodec::SpecCodec<Mix08> Mix08Codec = {
    .encode = [](specodec::SpecWriter& w, const Mix08& obj) { write_mix08(w, obj); },
    .decode = [](specodec::SpecReader& r) -> Mix08 {
        std::vector<std::string> fld_keys = {};
        std::vector<std::int32_t> fld_values = {};
        std::optional<Label> fld_meta;
        r.beginObject();
        while (r.hasNextField()) {
            auto field_name = r.readFieldName();
            if (field_name == "keys") { fld_keys = [&]() {
    std::vector<std::string> result;
    r.beginArray();
    while (r.hasNextElement()) { result.push_back(r.readString()); }
    r.endArray();
    return result;
}(); }
            else if (field_name == "values") { fld_values = [&]() {
    std::vector<std::int32_t> result;
    r.beginArray();
    while (r.hasNextElement()) { result.push_back(r.readInt32()); }
    r.endArray();
    return result;
}(); }
            else if (field_name == "meta") { fld_meta = std::optional<Label>{(r.isNull() ? (r.readNull(), std::optional<Label>{std::nullopt}) : std::optional<Label>{LabelCodec.decode(r)})}; }
            else { r.skip(); }
        }
        r.endObject();
        return Mix08{fld_keys, fld_values, fld_meta};
    }
};

export struct Mix09 {
    std::int64_t id_;
    std::vector<std::uint8_t> payload_;
    std::uint32_t checksum_;
    std::optional<IdVal> prev_;
};

export inline void write_mix09(specodec::SpecWriter& w, const Mix09& obj) {
    int field_count = 3;
    if (obj.prev_.has_value()) field_count++;
    w.beginObject(field_count);
    w.writeField("id"); w.writeInt64(obj.id_);;
    w.writeField("payload"); w.writeBytes(obj.payload_);;
    w.writeField("checksum"); w.writeUint32(obj.checksum_);;
    if (obj.prev_.has_value()) { w.writeField("prev"); write_id_val(w, obj.prev_.value());; }
    w.endObject();
}

export inline specodec::SpecCodec<Mix09> Mix09Codec = {
    .encode = [](specodec::SpecWriter& w, const Mix09& obj) { write_mix09(w, obj); },
    .decode = [](specodec::SpecReader& r) -> Mix09 {
        std::int64_t fld_id = 0LL;
        std::vector<std::uint8_t> fld_payload = {};
        std::uint32_t fld_checksum = 0u;
        std::optional<IdVal> fld_prev;
        r.beginObject();
        while (r.hasNextField()) {
            auto field_name = r.readFieldName();
            if (field_name == "id") { fld_id = r.readInt64(); }
            else if (field_name == "payload") { fld_payload = r.readBytes(); }
            else if (field_name == "checksum") { fld_checksum = r.readUint32(); }
            else if (field_name == "prev") { fld_prev = std::optional<IdVal>{(r.isNull() ? (r.readNull(), std::optional<IdVal>{std::nullopt}) : std::optional<IdVal>{IdValCodec.decode(r)})}; }
            else { r.skip(); }
        }
        r.endObject();
        return Mix09{fld_id, fld_payload, fld_checksum, fld_prev};
    }
};

export struct Mix10 {
    std::vector<std::string> items_;
    std::int32_t total_;
    double avg_;
    Range32 value_range_;
};

export inline void write_mix10(specodec::SpecWriter& w, const Mix10& obj) {
    w.beginObject(4);
    w.writeField("items"); 
        w.beginArray(obj.items_.size());
        for (const auto& elem : obj.items_) { w.nextElement(); w.writeString(elem); }
        w.endArray();
    w.writeField("total"); w.writeInt32(obj.total_);;
    w.writeField("avg"); w.writeFloat64(obj.avg_);;
    w.writeField("value_range"); write_range32(w, obj.value_range_);;
    w.endObject();
}

export inline specodec::SpecCodec<Mix10> Mix10Codec = {
    .encode = [](specodec::SpecWriter& w, const Mix10& obj) { write_mix10(w, obj); },
    .decode = [](specodec::SpecReader& r) -> Mix10 {
        std::vector<std::string> fld_items = {};
        std::int32_t fld_total = 0;
        double fld_avg = 0.0;
        Range32 fld_value_range = {};
        r.beginObject();
        while (r.hasNextField()) {
            auto field_name = r.readFieldName();
            if (field_name == "items") { fld_items = [&]() {
    std::vector<std::string> result;
    r.beginArray();
    while (r.hasNextElement()) { result.push_back(r.readString()); }
    r.endArray();
    return result;
}(); }
            else if (field_name == "total") { fld_total = r.readInt32(); }
            else if (field_name == "avg") { fld_avg = r.readFloat64(); }
            else if (field_name == "value_range") { fld_value_range = Range32Codec.decode(r); }
            else { r.skip(); }
        }
        r.endObject();
        return Mix10{fld_items, fld_total, fld_avg, fld_value_range};
    }
};

export struct Mix11 {
    std::string name_;
    std::vector<double> values_;
    std::optional<Inner> nested_;
    std::optional<bool> flag_;
};

export inline void write_mix11(specodec::SpecWriter& w, const Mix11& obj) {
    int field_count = 2;
    if (obj.nested_.has_value()) field_count++;
    if (obj.flag_.has_value()) field_count++;
    w.beginObject(field_count);
    w.writeField("name"); w.writeString(obj.name_);;
    w.writeField("values"); 
        w.beginArray(obj.values_.size());
        for (const auto& elem : obj.values_) { w.nextElement(); w.writeFloat64(elem); }
        w.endArray();
    if (obj.nested_.has_value()) { w.writeField("nested"); write_inner(w, obj.nested_.value());; }
    if (obj.flag_.has_value()) { w.writeField("flag"); w.writeBool(obj.flag_.value());; }
    w.endObject();
}

export inline specodec::SpecCodec<Mix11> Mix11Codec = {
    .encode = [](specodec::SpecWriter& w, const Mix11& obj) { write_mix11(w, obj); },
    .decode = [](specodec::SpecReader& r) -> Mix11 {
        std::string fld_name = "";
        std::vector<double> fld_values = {};
        std::optional<Inner> fld_nested;
        std::optional<bool> fld_flag;
        r.beginObject();
        while (r.hasNextField()) {
            auto field_name = r.readFieldName();
            if (field_name == "name") { fld_name = r.readString(); }
            else if (field_name == "values") { fld_values = [&]() {
    std::vector<double> result;
    r.beginArray();
    while (r.hasNextElement()) { result.push_back(r.readFloat64()); }
    r.endArray();
    return result;
}(); }
            else if (field_name == "nested") { fld_nested = std::optional<Inner>{(r.isNull() ? (r.readNull(), std::optional<Inner>{std::nullopt}) : std::optional<Inner>{InnerCodec.decode(r)})}; }
            else if (field_name == "flag") { fld_flag = std::optional<bool>{r.readBool()}; }
            else { r.skip(); }
        }
        r.endObject();
        return Mix11{fld_name, fld_values, fld_nested, fld_flag};
    }
};

export struct Mix12 {
    std::string header_;
    std::vector<IdVal> entries_;
    std::optional<std::string> footer_;
};

export inline void write_mix12(specodec::SpecWriter& w, const Mix12& obj) {
    int field_count = 2;
    if (obj.footer_.has_value()) field_count++;
    w.beginObject(field_count);
    w.writeField("header"); w.writeString(obj.header_);;
    w.writeField("entries"); 
        w.beginArray(obj.entries_.size());
        for (const auto& elem : obj.entries_) { w.nextElement(); write_id_val(w, elem); }
        w.endArray();
    if (obj.footer_.has_value()) { w.writeField("footer"); w.writeString(obj.footer_.value());; }
    w.endObject();
}

export inline specodec::SpecCodec<Mix12> Mix12Codec = {
    .encode = [](specodec::SpecWriter& w, const Mix12& obj) { write_mix12(w, obj); },
    .decode = [](specodec::SpecReader& r) -> Mix12 {
        std::string fld_header = "";
        std::vector<IdVal> fld_entries = {};
        std::optional<std::string> fld_footer;
        r.beginObject();
        while (r.hasNextField()) {
            auto field_name = r.readFieldName();
            if (field_name == "header") { fld_header = r.readString(); }
            else if (field_name == "entries") { fld_entries = [&]() {
    std::vector<IdVal> result;
    r.beginArray();
    while (r.hasNextElement()) { result.push_back(IdValCodec.decode(r)); }
    r.endArray();
    return result;
}(); }
            else if (field_name == "footer") { fld_footer = std::optional<std::string>{r.readString()}; }
            else { r.skip(); }
        }
        r.endObject();
        return Mix12{fld_header, fld_entries, fld_footer};
    }
};

export struct Mix13 {
    std::int32_t a_;
    double b_;
    std::string c_;
    bool d_;
    std::vector<std::uint8_t> e_;
    Inner nested_;
};

export inline void write_mix13(specodec::SpecWriter& w, const Mix13& obj) {
    w.beginObject(6);
    w.writeField("a"); w.writeInt32(obj.a_);;
    w.writeField("b"); w.writeFloat64(obj.b_);;
    w.writeField("c"); w.writeString(obj.c_);;
    w.writeField("d"); w.writeBool(obj.d_);;
    w.writeField("e"); w.writeBytes(obj.e_);;
    w.writeField("nested"); write_inner(w, obj.nested_);;
    w.endObject();
}

export inline specodec::SpecCodec<Mix13> Mix13Codec = {
    .encode = [](specodec::SpecWriter& w, const Mix13& obj) { write_mix13(w, obj); },
    .decode = [](specodec::SpecReader& r) -> Mix13 {
        std::int32_t fld_a = 0;
        double fld_b = 0.0;
        std::string fld_c = "";
        bool fld_d = false;
        std::vector<std::uint8_t> fld_e = {};
        Inner fld_nested = {};
        r.beginObject();
        while (r.hasNextField()) {
            auto field_name = r.readFieldName();
            if (field_name == "a") { fld_a = r.readInt32(); }
            else if (field_name == "b") { fld_b = r.readFloat64(); }
            else if (field_name == "c") { fld_c = r.readString(); }
            else if (field_name == "d") { fld_d = r.readBool(); }
            else if (field_name == "e") { fld_e = r.readBytes(); }
            else if (field_name == "nested") { fld_nested = InnerCodec.decode(r); }
            else { r.skip(); }
        }
        r.endObject();
        return Mix13{fld_a, fld_b, fld_c, fld_d, fld_e, fld_nested};
    }
};

export struct Mix14 {
    std::vector<Money> amounts_;
    std::int64_t total_;
    std::string currency_;
};

export inline void write_mix14(specodec::SpecWriter& w, const Mix14& obj) {
    w.beginObject(3);
    w.writeField("amounts"); 
        w.beginArray(obj.amounts_.size());
        for (const auto& elem : obj.amounts_) { w.nextElement(); write_money(w, elem); }
        w.endArray();
    w.writeField("total"); w.writeInt64(obj.total_);;
    w.writeField("currency"); w.writeString(obj.currency_);;
    w.endObject();
}

export inline specodec::SpecCodec<Mix14> Mix14Codec = {
    .encode = [](specodec::SpecWriter& w, const Mix14& obj) { write_mix14(w, obj); },
    .decode = [](specodec::SpecReader& r) -> Mix14 {
        std::vector<Money> fld_amounts = {};
        std::int64_t fld_total = 0LL;
        std::string fld_currency = "";
        r.beginObject();
        while (r.hasNextField()) {
            auto field_name = r.readFieldName();
            if (field_name == "amounts") { fld_amounts = [&]() {
    std::vector<Money> result;
    r.beginArray();
    while (r.hasNextElement()) { result.push_back(MoneyCodec.decode(r)); }
    r.endArray();
    return result;
}(); }
            else if (field_name == "total") { fld_total = r.readInt64(); }
            else if (field_name == "currency") { fld_currency = r.readString(); }
            else { r.skip(); }
        }
        r.endObject();
        return Mix14{fld_amounts, fld_total, fld_currency};
    }
};

export struct Mix15 {
    Addr src_addr_;
    Addr dst_addr_;
    double distance_;
    double duration_;
};

export inline void write_mix15(specodec::SpecWriter& w, const Mix15& obj) {
    w.beginObject(4);
    w.writeField("src_addr"); write_addr(w, obj.src_addr_);;
    w.writeField("dst_addr"); write_addr(w, obj.dst_addr_);;
    w.writeField("distance"); w.writeFloat64(obj.distance_);;
    w.writeField("duration"); w.writeFloat64(obj.duration_);;
    w.endObject();
}

export inline specodec::SpecCodec<Mix15> Mix15Codec = {
    .encode = [](specodec::SpecWriter& w, const Mix15& obj) { write_mix15(w, obj); },
    .decode = [](specodec::SpecReader& r) -> Mix15 {
        Addr fld_src_addr = {};
        Addr fld_dst_addr = {};
        double fld_distance = 0.0;
        double fld_duration = 0.0;
        r.beginObject();
        while (r.hasNextField()) {
            auto field_name = r.readFieldName();
            if (field_name == "src_addr") { fld_src_addr = AddrCodec.decode(r); }
            else if (field_name == "dst_addr") { fld_dst_addr = AddrCodec.decode(r); }
            else if (field_name == "distance") { fld_distance = r.readFloat64(); }
            else if (field_name == "duration") { fld_duration = r.readFloat64(); }
            else { r.skip(); }
        }
        r.endObject();
        return Mix15{fld_src_addr, fld_dst_addr, fld_distance, fld_duration};
    }
};

export struct AllOpt1 {
    std::optional<std::string> a_;
    std::optional<std::int32_t> b_;
    std::optional<bool> c_;
};

export inline void write_all_opt1(specodec::SpecWriter& w, const AllOpt1& obj) {
    int field_count = 0;
    if (obj.a_.has_value()) field_count++;
    if (obj.b_.has_value()) field_count++;
    if (obj.c_.has_value()) field_count++;
    w.beginObject(field_count);
    if (obj.a_.has_value()) { w.writeField("a"); w.writeString(obj.a_.value());; }
    if (obj.b_.has_value()) { w.writeField("b"); w.writeInt32(obj.b_.value());; }
    if (obj.c_.has_value()) { w.writeField("c"); w.writeBool(obj.c_.value());; }
    w.endObject();
}

export inline specodec::SpecCodec<AllOpt1> AllOpt1Codec = {
    .encode = [](specodec::SpecWriter& w, const AllOpt1& obj) { write_all_opt1(w, obj); },
    .decode = [](specodec::SpecReader& r) -> AllOpt1 {
        std::optional<std::string> fld_a;
        std::optional<std::int32_t> fld_b;
        std::optional<bool> fld_c;
        r.beginObject();
        while (r.hasNextField()) {
            auto field_name = r.readFieldName();
            if (field_name == "a") { fld_a = std::optional<std::string>{r.readString()}; }
            else if (field_name == "b") { fld_b = std::optional<std::int32_t>{r.readInt32()}; }
            else if (field_name == "c") { fld_c = std::optional<bool>{r.readBool()}; }
            else { r.skip(); }
        }
        r.endObject();
        return AllOpt1{fld_a, fld_b, fld_c};
    }
};

export struct AllOpt2 {
    std::optional<double> x_;
    std::optional<std::vector<std::uint8_t>> y_;
    std::optional<std::int64_t> z_;
};

export inline void write_all_opt2(specodec::SpecWriter& w, const AllOpt2& obj) {
    int field_count = 0;
    if (obj.x_.has_value()) field_count++;
    if (obj.y_.has_value()) field_count++;
    if (obj.z_.has_value()) field_count++;
    w.beginObject(field_count);
    if (obj.x_.has_value()) { w.writeField("x"); w.writeFloat64(obj.x_.value());; }
    if (obj.y_.has_value()) { w.writeField("y"); w.writeBytes(obj.y_.value());; }
    if (obj.z_.has_value()) { w.writeField("z"); w.writeInt64(obj.z_.value());; }
    w.endObject();
}

export inline specodec::SpecCodec<AllOpt2> AllOpt2Codec = {
    .encode = [](specodec::SpecWriter& w, const AllOpt2& obj) { write_all_opt2(w, obj); },
    .decode = [](specodec::SpecReader& r) -> AllOpt2 {
        std::optional<double> fld_x;
        std::optional<std::vector<std::uint8_t>> fld_y;
        std::optional<std::int64_t> fld_z;
        r.beginObject();
        while (r.hasNextField()) {
            auto field_name = r.readFieldName();
            if (field_name == "x") { fld_x = std::optional<double>{r.readFloat64()}; }
            else if (field_name == "y") { fld_y = std::optional<std::vector<std::uint8_t>>{r.readBytes()}; }
            else if (field_name == "z") { fld_z = std::optional<std::int64_t>{r.readInt64()}; }
            else { r.skip(); }
        }
        r.endObject();
        return AllOpt2{fld_x, fld_y, fld_z};
    }
};

export struct AllOpt3 {
    std::optional<std::string> name_;
    std::optional<std::int32_t> age_;
    std::optional<double> score_;
    std::optional<bool> active_;
};

export inline void write_all_opt3(specodec::SpecWriter& w, const AllOpt3& obj) {
    int field_count = 0;
    if (obj.name_.has_value()) field_count++;
    if (obj.age_.has_value()) field_count++;
    if (obj.score_.has_value()) field_count++;
    if (obj.active_.has_value()) field_count++;
    w.beginObject(field_count);
    if (obj.name_.has_value()) { w.writeField("name"); w.writeString(obj.name_.value());; }
    if (obj.age_.has_value()) { w.writeField("age"); w.writeInt32(obj.age_.value());; }
    if (obj.score_.has_value()) { w.writeField("score"); w.writeFloat64(obj.score_.value());; }
    if (obj.active_.has_value()) { w.writeField("active"); w.writeBool(obj.active_.value());; }
    w.endObject();
}

export inline specodec::SpecCodec<AllOpt3> AllOpt3Codec = {
    .encode = [](specodec::SpecWriter& w, const AllOpt3& obj) { write_all_opt3(w, obj); },
    .decode = [](specodec::SpecReader& r) -> AllOpt3 {
        std::optional<std::string> fld_name;
        std::optional<std::int32_t> fld_age;
        std::optional<double> fld_score;
        std::optional<bool> fld_active;
        r.beginObject();
        while (r.hasNextField()) {
            auto field_name = r.readFieldName();
            if (field_name == "name") { fld_name = std::optional<std::string>{r.readString()}; }
            else if (field_name == "age") { fld_age = std::optional<std::int32_t>{r.readInt32()}; }
            else if (field_name == "score") { fld_score = std::optional<double>{r.readFloat64()}; }
            else if (field_name == "active") { fld_active = std::optional<bool>{r.readBool()}; }
            else { r.skip(); }
        }
        r.endObject();
        return AllOpt3{fld_name, fld_age, fld_score, fld_active};
    }
};

export struct AllOpt4 {
    std::optional<std::uint32_t> a_;
    std::optional<std::uint64_t> b_;
    std::optional<std::int32_t> c_;
    std::optional<std::string> d_;
    std::optional<std::vector<std::uint8_t>> e_;
};

export inline void write_all_opt4(specodec::SpecWriter& w, const AllOpt4& obj) {
    int field_count = 0;
    if (obj.a_.has_value()) field_count++;
    if (obj.b_.has_value()) field_count++;
    if (obj.c_.has_value()) field_count++;
    if (obj.d_.has_value()) field_count++;
    if (obj.e_.has_value()) field_count++;
    w.beginObject(field_count);
    if (obj.a_.has_value()) { w.writeField("a"); w.writeUint32(obj.a_.value());; }
    if (obj.b_.has_value()) { w.writeField("b"); w.writeUint64(obj.b_.value());; }
    if (obj.c_.has_value()) { w.writeField("c"); w.writeInt32(obj.c_.value());; }
    if (obj.d_.has_value()) { w.writeField("d"); w.writeString(obj.d_.value());; }
    if (obj.e_.has_value()) { w.writeField("e"); w.writeBytes(obj.e_.value());; }
    w.endObject();
}

export inline specodec::SpecCodec<AllOpt4> AllOpt4Codec = {
    .encode = [](specodec::SpecWriter& w, const AllOpt4& obj) { write_all_opt4(w, obj); },
    .decode = [](specodec::SpecReader& r) -> AllOpt4 {
        std::optional<std::uint32_t> fld_a;
        std::optional<std::uint64_t> fld_b;
        std::optional<std::int32_t> fld_c;
        std::optional<std::string> fld_d;
        std::optional<std::vector<std::uint8_t>> fld_e;
        r.beginObject();
        while (r.hasNextField()) {
            auto field_name = r.readFieldName();
            if (field_name == "a") { fld_a = std::optional<std::uint32_t>{r.readUint32()}; }
            else if (field_name == "b") { fld_b = std::optional<std::uint64_t>{r.readUint64()}; }
            else if (field_name == "c") { fld_c = std::optional<std::int32_t>{r.readInt32()}; }
            else if (field_name == "d") { fld_d = std::optional<std::string>{r.readString()}; }
            else if (field_name == "e") { fld_e = std::optional<std::vector<std::uint8_t>>{r.readBytes()}; }
            else { r.skip(); }
        }
        r.endObject();
        return AllOpt4{fld_a, fld_b, fld_c, fld_d, fld_e};
    }
};

export struct AllOpt5 {
    std::optional<Inner> p_;
    std::optional<std::string> q_;
};

export inline void write_all_opt5(specodec::SpecWriter& w, const AllOpt5& obj) {
    int field_count = 0;
    if (obj.p_.has_value()) field_count++;
    if (obj.q_.has_value()) field_count++;
    w.beginObject(field_count);
    if (obj.p_.has_value()) { w.writeField("p"); write_inner(w, obj.p_.value());; }
    if (obj.q_.has_value()) { w.writeField("q"); w.writeString(obj.q_.value());; }
    w.endObject();
}

export inline specodec::SpecCodec<AllOpt5> AllOpt5Codec = {
    .encode = [](specodec::SpecWriter& w, const AllOpt5& obj) { write_all_opt5(w, obj); },
    .decode = [](specodec::SpecReader& r) -> AllOpt5 {
        std::optional<Inner> fld_p;
        std::optional<std::string> fld_q;
        r.beginObject();
        while (r.hasNextField()) {
            auto field_name = r.readFieldName();
            if (field_name == "p") { fld_p = std::optional<Inner>{(r.isNull() ? (r.readNull(), std::optional<Inner>{std::nullopt}) : std::optional<Inner>{InnerCodec.decode(r)})}; }
            else if (field_name == "q") { fld_q = std::optional<std::string>{r.readString()}; }
            else { r.skip(); }
        }
        r.endObject();
        return AllOpt5{fld_p, fld_q};
    }
};

} // namespace all_types_mixed