// Generated by @specodec/typespec-emitter-cpp. DO NOT EDIT.
export module all_types_nests;
import std;
import specodec;
import all_types;
using namespace all_types;

namespace all_types_nests {

export struct NestInner {
    Inner nested;
};

export inline void write_nest_inner(specodec::SpecWriter& w, const NestInner& obj) {
    w.beginObject(1);
    w.writeField("nested"); write_inner(w, obj.nested);;
    w.endObject();
}

export inline specodec::SpecCodec<NestInner> NestInnerCodec = {
    .encode = [](specodec::SpecWriter& w, const NestInner& obj) { write_nest_inner(w, obj); },
    .decode = [](specodec::SpecReader& r) -> NestInner {
        Inner fld_nested = {};
        r.beginObject();
        while (r.hasNextField()) {
            auto field_name = r.readFieldName();
            if (field_name == "nested") { fld_nested = InnerCodec.decode(r); }
            else { r.skip(); }
        }
        r.endObject();
        return NestInner{fld_nested};
    }
};

export struct NestCoord {
    Coord nested;
};

export inline void write_nest_coord(specodec::SpecWriter& w, const NestCoord& obj) {
    w.beginObject(1);
    w.writeField("nested"); write_coord(w, obj.nested);;
    w.endObject();
}

export inline specodec::SpecCodec<NestCoord> NestCoordCodec = {
    .encode = [](specodec::SpecWriter& w, const NestCoord& obj) { write_nest_coord(w, obj); },
    .decode = [](specodec::SpecReader& r) -> NestCoord {
        Coord fld_nested = {};
        r.beginObject();
        while (r.hasNextField()) {
            auto field_name = r.readFieldName();
            if (field_name == "nested") { fld_nested = CoordCodec.decode(r); }
            else { r.skip(); }
        }
        r.endObject();
        return NestCoord{fld_nested};
    }
};

export struct NestIdVal {
    IdVal nested;
};

export inline void write_nest_id_val(specodec::SpecWriter& w, const NestIdVal& obj) {
    w.beginObject(1);
    w.writeField("nested"); write_id_val(w, obj.nested);;
    w.endObject();
}

export inline specodec::SpecCodec<NestIdVal> NestIdValCodec = {
    .encode = [](specodec::SpecWriter& w, const NestIdVal& obj) { write_nest_id_val(w, obj); },
    .decode = [](specodec::SpecReader& r) -> NestIdVal {
        IdVal fld_nested = {};
        r.beginObject();
        while (r.hasNextField()) {
            auto field_name = r.readFieldName();
            if (field_name == "nested") { fld_nested = IdValCodec.decode(r); }
            else { r.skip(); }
        }
        r.endObject();
        return NestIdVal{fld_nested};
    }
};

export struct NestLabel {
    Label nested;
};

export inline void write_nest_label(specodec::SpecWriter& w, const NestLabel& obj) {
    w.beginObject(1);
    w.writeField("nested"); write_label(w, obj.nested);;
    w.endObject();
}

export inline specodec::SpecCodec<NestLabel> NestLabelCodec = {
    .encode = [](specodec::SpecWriter& w, const NestLabel& obj) { write_nest_label(w, obj); },
    .decode = [](specodec::SpecReader& r) -> NestLabel {
        Label fld_nested = {};
        r.beginObject();
        while (r.hasNextField()) {
            auto field_name = r.readFieldName();
            if (field_name == "nested") { fld_nested = LabelCodec.decode(r); }
            else { r.skip(); }
        }
        r.endObject();
        return NestLabel{fld_nested};
    }
};

export struct NestMoney {
    Money nested;
};

export inline void write_nest_money(specodec::SpecWriter& w, const NestMoney& obj) {
    w.beginObject(1);
    w.writeField("nested"); write_money(w, obj.nested);;
    w.endObject();
}

export inline specodec::SpecCodec<NestMoney> NestMoneyCodec = {
    .encode = [](specodec::SpecWriter& w, const NestMoney& obj) { write_nest_money(w, obj); },
    .decode = [](specodec::SpecReader& r) -> NestMoney {
        Money fld_nested = {};
        r.beginObject();
        while (r.hasNextField()) {
            auto field_name = r.readFieldName();
            if (field_name == "nested") { fld_nested = MoneyCodec.decode(r); }
            else { r.skip(); }
        }
        r.endObject();
        return NestMoney{fld_nested};
    }
};

export struct NestRange32 {
    Range32 nested;
};

export inline void write_nest_range32(specodec::SpecWriter& w, const NestRange32& obj) {
    w.beginObject(1);
    w.writeField("nested"); write_range32(w, obj.nested);;
    w.endObject();
}

export inline specodec::SpecCodec<NestRange32> NestRange32Codec = {
    .encode = [](specodec::SpecWriter& w, const NestRange32& obj) { write_nest_range32(w, obj); },
    .decode = [](specodec::SpecReader& r) -> NestRange32 {
        Range32 fld_nested = {};
        r.beginObject();
        while (r.hasNextField()) {
            auto field_name = r.readFieldName();
            if (field_name == "nested") { fld_nested = Range32Codec.decode(r); }
            else { r.skip(); }
        }
        r.endObject();
        return NestRange32{fld_nested};
    }
};

export struct NestAddr {
    Addr nested;
};

export inline void write_nest_addr(specodec::SpecWriter& w, const NestAddr& obj) {
    w.beginObject(1);
    w.writeField("nested"); write_addr(w, obj.nested);;
    w.endObject();
}

export inline specodec::SpecCodec<NestAddr> NestAddrCodec = {
    .encode = [](specodec::SpecWriter& w, const NestAddr& obj) { write_nest_addr(w, obj); },
    .decode = [](specodec::SpecReader& r) -> NestAddr {
        Addr fld_nested = {};
        r.beginObject();
        while (r.hasNextField()) {
            auto field_name = r.readFieldName();
            if (field_name == "nested") { fld_nested = AddrCodec.decode(r); }
            else { r.skip(); }
        }
        r.endObject();
        return NestAddr{fld_nested};
    }
};

export struct NestPoint3 {
    Point3 nested;
};

export inline void write_nest_point3(specodec::SpecWriter& w, const NestPoint3& obj) {
    w.beginObject(1);
    w.writeField("nested"); write_point3(w, obj.nested);;
    w.endObject();
}

export inline specodec::SpecCodec<NestPoint3> NestPoint3Codec = {
    .encode = [](specodec::SpecWriter& w, const NestPoint3& obj) { write_nest_point3(w, obj); },
    .decode = [](specodec::SpecReader& r) -> NestPoint3 {
        Point3 fld_nested = {};
        r.beginObject();
        while (r.hasNextField()) {
            auto field_name = r.readFieldName();
            if (field_name == "nested") { fld_nested = Point3Codec.decode(r); }
            else { r.skip(); }
        }
        r.endObject();
        return NestPoint3{fld_nested};
    }
};

export struct OptNestInner {
    std::string label;
    std::optional<Inner> nested;
};

export inline void write_opt_nest_inner(specodec::SpecWriter& w, const OptNestInner& obj) {
    int field_count = 1;
    if (obj.nested.has_value()) field_count++;
    w.beginObject(field_count);
    w.writeField("label"); w.writeString(obj.label);;
    if (obj.nested.has_value()) { w.writeField("nested"); write_inner(w, obj.nested.value());; }
    w.endObject();
}

export inline specodec::SpecCodec<OptNestInner> OptNestInnerCodec = {
    .encode = [](specodec::SpecWriter& w, const OptNestInner& obj) { write_opt_nest_inner(w, obj); },
    .decode = [](specodec::SpecReader& r) -> OptNestInner {
        std::string fld_label = "";
        std::optional<Inner> fld_nested;
        r.beginObject();
        while (r.hasNextField()) {
            auto field_name = r.readFieldName();
            if (field_name == "label") { fld_label = r.readString(); }
            else if (field_name == "nested") { fld_nested = std::optional<Inner>{(r.isNull() ? (r.readNull(), std::optional<Inner>{std::nullopt}) : std::optional<Inner>{InnerCodec.decode(r)})}; }
            else { r.skip(); }
        }
        r.endObject();
        return OptNestInner{fld_label, fld_nested};
    }
};

export struct OptNestCoord {
    std::string label;
    std::optional<Coord> nested;
};

export inline void write_opt_nest_coord(specodec::SpecWriter& w, const OptNestCoord& obj) {
    int field_count = 1;
    if (obj.nested.has_value()) field_count++;
    w.beginObject(field_count);
    w.writeField("label"); w.writeString(obj.label);;
    if (obj.nested.has_value()) { w.writeField("nested"); write_coord(w, obj.nested.value());; }
    w.endObject();
}

export inline specodec::SpecCodec<OptNestCoord> OptNestCoordCodec = {
    .encode = [](specodec::SpecWriter& w, const OptNestCoord& obj) { write_opt_nest_coord(w, obj); },
    .decode = [](specodec::SpecReader& r) -> OptNestCoord {
        std::string fld_label = "";
        std::optional<Coord> fld_nested;
        r.beginObject();
        while (r.hasNextField()) {
            auto field_name = r.readFieldName();
            if (field_name == "label") { fld_label = r.readString(); }
            else if (field_name == "nested") { fld_nested = std::optional<Coord>{(r.isNull() ? (r.readNull(), std::optional<Coord>{std::nullopt}) : std::optional<Coord>{CoordCodec.decode(r)})}; }
            else { r.skip(); }
        }
        r.endObject();
        return OptNestCoord{fld_label, fld_nested};
    }
};

export struct OptNestIdVal {
    std::string label;
    std::optional<IdVal> nested;
};

export inline void write_opt_nest_id_val(specodec::SpecWriter& w, const OptNestIdVal& obj) {
    int field_count = 1;
    if (obj.nested.has_value()) field_count++;
    w.beginObject(field_count);
    w.writeField("label"); w.writeString(obj.label);;
    if (obj.nested.has_value()) { w.writeField("nested"); write_id_val(w, obj.nested.value());; }
    w.endObject();
}

export inline specodec::SpecCodec<OptNestIdVal> OptNestIdValCodec = {
    .encode = [](specodec::SpecWriter& w, const OptNestIdVal& obj) { write_opt_nest_id_val(w, obj); },
    .decode = [](specodec::SpecReader& r) -> OptNestIdVal {
        std::string fld_label = "";
        std::optional<IdVal> fld_nested;
        r.beginObject();
        while (r.hasNextField()) {
            auto field_name = r.readFieldName();
            if (field_name == "label") { fld_label = r.readString(); }
            else if (field_name == "nested") { fld_nested = std::optional<IdVal>{(r.isNull() ? (r.readNull(), std::optional<IdVal>{std::nullopt}) : std::optional<IdVal>{IdValCodec.decode(r)})}; }
            else { r.skip(); }
        }
        r.endObject();
        return OptNestIdVal{fld_label, fld_nested};
    }
};

export struct OptNestLabel {
    std::string label;
    std::optional<Label> nested;
};

export inline void write_opt_nest_label(specodec::SpecWriter& w, const OptNestLabel& obj) {
    int field_count = 1;
    if (obj.nested.has_value()) field_count++;
    w.beginObject(field_count);
    w.writeField("label"); w.writeString(obj.label);;
    if (obj.nested.has_value()) { w.writeField("nested"); write_label(w, obj.nested.value());; }
    w.endObject();
}

export inline specodec::SpecCodec<OptNestLabel> OptNestLabelCodec = {
    .encode = [](specodec::SpecWriter& w, const OptNestLabel& obj) { write_opt_nest_label(w, obj); },
    .decode = [](specodec::SpecReader& r) -> OptNestLabel {
        std::string fld_label = "";
        std::optional<Label> fld_nested;
        r.beginObject();
        while (r.hasNextField()) {
            auto field_name = r.readFieldName();
            if (field_name == "label") { fld_label = r.readString(); }
            else if (field_name == "nested") { fld_nested = std::optional<Label>{(r.isNull() ? (r.readNull(), std::optional<Label>{std::nullopt}) : std::optional<Label>{LabelCodec.decode(r)})}; }
            else { r.skip(); }
        }
        r.endObject();
        return OptNestLabel{fld_label, fld_nested};
    }
};

export struct OptNestMoney {
    std::string label;
    std::optional<Money> nested;
};

export inline void write_opt_nest_money(specodec::SpecWriter& w, const OptNestMoney& obj) {
    int field_count = 1;
    if (obj.nested.has_value()) field_count++;
    w.beginObject(field_count);
    w.writeField("label"); w.writeString(obj.label);;
    if (obj.nested.has_value()) { w.writeField("nested"); write_money(w, obj.nested.value());; }
    w.endObject();
}

export inline specodec::SpecCodec<OptNestMoney> OptNestMoneyCodec = {
    .encode = [](specodec::SpecWriter& w, const OptNestMoney& obj) { write_opt_nest_money(w, obj); },
    .decode = [](specodec::SpecReader& r) -> OptNestMoney {
        std::string fld_label = "";
        std::optional<Money> fld_nested;
        r.beginObject();
        while (r.hasNextField()) {
            auto field_name = r.readFieldName();
            if (field_name == "label") { fld_label = r.readString(); }
            else if (field_name == "nested") { fld_nested = std::optional<Money>{(r.isNull() ? (r.readNull(), std::optional<Money>{std::nullopt}) : std::optional<Money>{MoneyCodec.decode(r)})}; }
            else { r.skip(); }
        }
        r.endObject();
        return OptNestMoney{fld_label, fld_nested};
    }
};

export struct OptNestRange32 {
    std::string label;
    std::optional<Range32> nested;
};

export inline void write_opt_nest_range32(specodec::SpecWriter& w, const OptNestRange32& obj) {
    int field_count = 1;
    if (obj.nested.has_value()) field_count++;
    w.beginObject(field_count);
    w.writeField("label"); w.writeString(obj.label);;
    if (obj.nested.has_value()) { w.writeField("nested"); write_range32(w, obj.nested.value());; }
    w.endObject();
}

export inline specodec::SpecCodec<OptNestRange32> OptNestRange32Codec = {
    .encode = [](specodec::SpecWriter& w, const OptNestRange32& obj) { write_opt_nest_range32(w, obj); },
    .decode = [](specodec::SpecReader& r) -> OptNestRange32 {
        std::string fld_label = "";
        std::optional<Range32> fld_nested;
        r.beginObject();
        while (r.hasNextField()) {
            auto field_name = r.readFieldName();
            if (field_name == "label") { fld_label = r.readString(); }
            else if (field_name == "nested") { fld_nested = std::optional<Range32>{(r.isNull() ? (r.readNull(), std::optional<Range32>{std::nullopt}) : std::optional<Range32>{Range32Codec.decode(r)})}; }
            else { r.skip(); }
        }
        r.endObject();
        return OptNestRange32{fld_label, fld_nested};
    }
};

export struct OptNestAddr {
    std::string label;
    std::optional<Addr> nested;
};

export inline void write_opt_nest_addr(specodec::SpecWriter& w, const OptNestAddr& obj) {
    int field_count = 1;
    if (obj.nested.has_value()) field_count++;
    w.beginObject(field_count);
    w.writeField("label"); w.writeString(obj.label);;
    if (obj.nested.has_value()) { w.writeField("nested"); write_addr(w, obj.nested.value());; }
    w.endObject();
}

export inline specodec::SpecCodec<OptNestAddr> OptNestAddrCodec = {
    .encode = [](specodec::SpecWriter& w, const OptNestAddr& obj) { write_opt_nest_addr(w, obj); },
    .decode = [](specodec::SpecReader& r) -> OptNestAddr {
        std::string fld_label = "";
        std::optional<Addr> fld_nested;
        r.beginObject();
        while (r.hasNextField()) {
            auto field_name = r.readFieldName();
            if (field_name == "label") { fld_label = r.readString(); }
            else if (field_name == "nested") { fld_nested = std::optional<Addr>{(r.isNull() ? (r.readNull(), std::optional<Addr>{std::nullopt}) : std::optional<Addr>{AddrCodec.decode(r)})}; }
            else { r.skip(); }
        }
        r.endObject();
        return OptNestAddr{fld_label, fld_nested};
    }
};

export struct OptNestPoint3 {
    std::string label;
    std::optional<Point3> nested;
};

export inline void write_opt_nest_point3(specodec::SpecWriter& w, const OptNestPoint3& obj) {
    int field_count = 1;
    if (obj.nested.has_value()) field_count++;
    w.beginObject(field_count);
    w.writeField("label"); w.writeString(obj.label);;
    if (obj.nested.has_value()) { w.writeField("nested"); write_point3(w, obj.nested.value());; }
    w.endObject();
}

export inline specodec::SpecCodec<OptNestPoint3> OptNestPoint3Codec = {
    .encode = [](specodec::SpecWriter& w, const OptNestPoint3& obj) { write_opt_nest_point3(w, obj); },
    .decode = [](specodec::SpecReader& r) -> OptNestPoint3 {
        std::string fld_label = "";
        std::optional<Point3> fld_nested;
        r.beginObject();
        while (r.hasNextField()) {
            auto field_name = r.readFieldName();
            if (field_name == "label") { fld_label = r.readString(); }
            else if (field_name == "nested") { fld_nested = std::optional<Point3>{(r.isNull() ? (r.readNull(), std::optional<Point3>{std::nullopt}) : std::optional<Point3>{Point3Codec.decode(r)})}; }
            else { r.skip(); }
        }
        r.endObject();
        return OptNestPoint3{fld_label, fld_nested};
    }
};

} // namespace all_types_nests