// Generated by @specodec/typespec-emitter-cpp. DO NOT EDIT.
export module all_types_edge;
import std;
import specodec;
import all_types;
using namespace all_types;

namespace all_types_edge {

export struct EdgeEmpty {};

export inline void write_edge_empty(specodec::SpecWriter& w, const EdgeEmpty& obj) {
    w.beginObject(0);
    w.endObject();
}

export inline specodec::SpecCodec<EdgeEmpty> EdgeEmptyCodec = {
    .encode = [](specodec::SpecWriter& w, const EdgeEmpty& obj) { write_edge_empty(w, obj); },
    .decode = [](specodec::SpecReader& r) -> EdgeEmpty {
        r.beginObject();
        while (r.hasNextField()) {
            auto field_name = r.readFieldName();
        }
        r.endObject();
        return EdgeEmpty{};
    }
};

export struct EdgeOneOpt {
    std::optional<std::string> maybe_;
};

export inline void write_edge_one_opt(specodec::SpecWriter& w, const EdgeOneOpt& obj) {
    int field_count = 0;
    if (obj.maybe_.has_value()) field_count++;
    w.beginObject(field_count);
    if (obj.maybe_.has_value()) { w.writeField("maybe"); w.writeString(obj.maybe_.value());; }
    w.endObject();
}

export inline specodec::SpecCodec<EdgeOneOpt> EdgeOneOptCodec = {
    .encode = [](specodec::SpecWriter& w, const EdgeOneOpt& obj) { write_edge_one_opt(w, obj); },
    .decode = [](specodec::SpecReader& r) -> EdgeOneOpt {
        std::optional<std::string> fld_maybe;
        r.beginObject();
        while (r.hasNextField()) {
            auto field_name = r.readFieldName();
            if (field_name == "maybe") { fld_maybe = std::optional<std::string>{r.readString()}; }
            else { r.skip(); }
        }
        r.endObject();
        return EdgeOneOpt{fld_maybe};
    }
};

export struct EdgeBigNums {
    std::int8_t i8_;
    std::int16_t i16_;
    std::int32_t i32_;
    std::int64_t i64_;
    std::uint8_t u8_;
    std::uint16_t u16_;
    std::uint32_t u32_;
    std::uint64_t u64_;
};

export inline void write_edge_big_nums(specodec::SpecWriter& w, const EdgeBigNums& obj) {
    w.beginObject(8);
    w.writeField("i8"); w.writeInt32(static_cast<std::int32_t>(obj.i8_));;
    w.writeField("i16"); w.writeInt32(static_cast<std::int32_t>(obj.i16_));;
    w.writeField("i32"); w.writeInt32(obj.i32_);;
    w.writeField("i64"); w.writeInt64(obj.i64_);;
    w.writeField("u8"); w.writeUint32(static_cast<std::uint32_t>(obj.u8_));;
    w.writeField("u16"); w.writeUint32(static_cast<std::uint32_t>(obj.u16_));;
    w.writeField("u32"); w.writeUint32(obj.u32_);;
    w.writeField("u64"); w.writeUint64(obj.u64_);;
    w.endObject();
}

export inline specodec::SpecCodec<EdgeBigNums> EdgeBigNumsCodec = {
    .encode = [](specodec::SpecWriter& w, const EdgeBigNums& obj) { write_edge_big_nums(w, obj); },
    .decode = [](specodec::SpecReader& r) -> EdgeBigNums {
        std::int8_t fld_i8 = 0;
        std::int16_t fld_i16 = 0;
        std::int32_t fld_i32 = 0;
        std::int64_t fld_i64 = 0LL;
        std::uint8_t fld_u8 = 0u;
        std::uint16_t fld_u16 = 0u;
        std::uint32_t fld_u32 = 0u;
        std::uint64_t fld_u64 = 0ULL;
        r.beginObject();
        while (r.hasNextField()) {
            auto field_name = r.readFieldName();
            if (field_name == "i8") { fld_i8 = static_cast<std::int8_t>(r.readInt32()); }
            else if (field_name == "i16") { fld_i16 = static_cast<std::int16_t>(r.readInt32()); }
            else if (field_name == "i32") { fld_i32 = r.readInt32(); }
            else if (field_name == "i64") { fld_i64 = r.readInt64(); }
            else if (field_name == "u8") { fld_u8 = static_cast<std::uint8_t>(r.readUint32()); }
            else if (field_name == "u16") { fld_u16 = static_cast<std::uint16_t>(r.readUint32()); }
            else if (field_name == "u32") { fld_u32 = r.readUint32(); }
            else if (field_name == "u64") { fld_u64 = r.readUint64(); }
            else { r.skip(); }
        }
        r.endObject();
        return EdgeBigNums{fld_i8, fld_i16, fld_i32, fld_i64, fld_u8, fld_u16, fld_u32, fld_u64};
    }
};

export struct EdgeZeroVals {
    std::string s_;
    std::int32_t i_;
    double f_;
    bool b_;
    std::vector<std::uint8_t> by_field_;
};

export inline void write_edge_zero_vals(specodec::SpecWriter& w, const EdgeZeroVals& obj) {
    w.beginObject(5);
    w.writeField("s"); w.writeString(obj.s_);;
    w.writeField("i"); w.writeInt32(obj.i_);;
    w.writeField("f"); w.writeFloat64(obj.f_);;
    w.writeField("b"); w.writeBool(obj.b_);;
    w.writeField("by_field"); w.writeBytes(obj.by_field_);;
    w.endObject();
}

export inline specodec::SpecCodec<EdgeZeroVals> EdgeZeroValsCodec = {
    .encode = [](specodec::SpecWriter& w, const EdgeZeroVals& obj) { write_edge_zero_vals(w, obj); },
    .decode = [](specodec::SpecReader& r) -> EdgeZeroVals {
        std::string fld_s = "";
        std::int32_t fld_i = 0;
        double fld_f = 0.0;
        bool fld_b = false;
        std::vector<std::uint8_t> fld_by_field = {};
        r.beginObject();
        while (r.hasNextField()) {
            auto field_name = r.readFieldName();
            if (field_name == "s") { fld_s = r.readString(); }
            else if (field_name == "i") { fld_i = r.readInt32(); }
            else if (field_name == "f") { fld_f = r.readFloat64(); }
            else if (field_name == "b") { fld_b = r.readBool(); }
            else if (field_name == "by_field") { fld_by_field = r.readBytes(); }
            else { r.skip(); }
        }
        r.endObject();
        return EdgeZeroVals{fld_s, fld_i, fld_f, fld_b, fld_by_field};
    }
};

export struct EdgeNullable {
    std::optional<std::string> a_;
    std::optional<std::int32_t> b_;
    std::optional<Inner> c_;
    std::optional<std::vector<std::string>> d_;
};

export inline void write_edge_nullable(specodec::SpecWriter& w, const EdgeNullable& obj) {
    int field_count = 0;
    if (obj.a_.has_value()) field_count++;
    if (obj.b_.has_value()) field_count++;
    if (obj.c_.has_value()) field_count++;
    if (obj.d_.has_value()) field_count++;
    w.beginObject(field_count);
    if (obj.a_.has_value()) { w.writeField("a"); w.writeString(obj.a_.value());; }
    if (obj.b_.has_value()) { w.writeField("b"); w.writeInt32(obj.b_.value());; }
    if (obj.c_.has_value()) { w.writeField("c"); write_inner(w, obj.c_.value());; }
    if (obj.d_.has_value()) { w.writeField("d"); 
        w.beginArray(obj.d_.value().size());
        for (const auto& elem : obj.d_.value()) { w.nextElement(); w.writeString(elem); }
        w.endArray(); }
    w.endObject();
}

export inline specodec::SpecCodec<EdgeNullable> EdgeNullableCodec = {
    .encode = [](specodec::SpecWriter& w, const EdgeNullable& obj) { write_edge_nullable(w, obj); },
    .decode = [](specodec::SpecReader& r) -> EdgeNullable {
        std::optional<std::string> fld_a;
        std::optional<std::int32_t> fld_b;
        std::optional<Inner> fld_c;
        std::optional<std::vector<std::string>> fld_d;
        r.beginObject();
        while (r.hasNextField()) {
            auto field_name = r.readFieldName();
            if (field_name == "a") { fld_a = std::optional<std::string>{r.readString()}; }
            else if (field_name == "b") { fld_b = std::optional<std::int32_t>{r.readInt32()}; }
            else if (field_name == "c") { fld_c = std::optional<Inner>{(r.isNull() ? (r.readNull(), std::optional<Inner>{std::nullopt}) : std::optional<Inner>{InnerCodec.decode(r)})}; }
            else if (field_name == "d") { fld_d = std::optional<std::vector<std::string>>{[&]() {
    std::vector<std::string> result;
    r.beginArray();
    while (r.hasNextElement()) { result.push_back(r.readString()); }
    r.endArray();
    return result;
}()}; }
            else { r.skip(); }
        }
        r.endObject();
        return EdgeNullable{fld_a, fld_b, fld_c, fld_d};
    }
};

export struct EdgeNegZero {
    double v_;
};

export inline void write_edge_neg_zero(specodec::SpecWriter& w, const EdgeNegZero& obj) {
    w.beginObject(1);
    w.writeField("v"); w.writeFloat64(obj.v_);;
    w.endObject();
}

export inline specodec::SpecCodec<EdgeNegZero> EdgeNegZeroCodec = {
    .encode = [](specodec::SpecWriter& w, const EdgeNegZero& obj) { write_edge_neg_zero(w, obj); },
    .decode = [](specodec::SpecReader& r) -> EdgeNegZero {
        double fld_v = 0.0;
        r.beginObject();
        while (r.hasNextField()) {
            auto field_name = r.readFieldName();
            if (field_name == "v") { fld_v = r.readFloat64(); }
            else { r.skip(); }
        }
        r.endObject();
        return EdgeNegZero{fld_v};
    }
};

export struct EdgeNullByte {
    std::string s_;
    std::vector<std::uint8_t> b_;
};

export inline void write_edge_null_byte(specodec::SpecWriter& w, const EdgeNullByte& obj) {
    w.beginObject(2);
    w.writeField("s"); w.writeString(obj.s_);;
    w.writeField("b"); w.writeBytes(obj.b_);;
    w.endObject();
}

export inline specodec::SpecCodec<EdgeNullByte> EdgeNullByteCodec = {
    .encode = [](specodec::SpecWriter& w, const EdgeNullByte& obj) { write_edge_null_byte(w, obj); },
    .decode = [](specodec::SpecReader& r) -> EdgeNullByte {
        std::string fld_s = "";
        std::vector<std::uint8_t> fld_b = {};
        r.beginObject();
        while (r.hasNextField()) {
            auto field_name = r.readFieldName();
            if (field_name == "s") { fld_s = r.readString(); }
            else if (field_name == "b") { fld_b = r.readBytes(); }
            else { r.skip(); }
        }
        r.endObject();
        return EdgeNullByte{fld_s, fld_b};
    }
};

export struct EdgeBoundary {
    std::int32_t i32_neg129_;
    std::int32_t i32_128_;
    std::int32_t i32_256_;
    std::int32_t i32_65536_;
    std::int32_t i32_neg32769_;
    std::uint32_t u32_65536_;
};

export inline void write_edge_boundary(specodec::SpecWriter& w, const EdgeBoundary& obj) {
    w.beginObject(6);
    w.writeField("i32_neg129"); w.writeInt32(obj.i32_neg129_);;
    w.writeField("i32_128"); w.writeInt32(obj.i32_128_);;
    w.writeField("i32_256"); w.writeInt32(obj.i32_256_);;
    w.writeField("i32_65536"); w.writeInt32(obj.i32_65536_);;
    w.writeField("i32_neg32769"); w.writeInt32(obj.i32_neg32769_);;
    w.writeField("u32_65536"); w.writeUint32(obj.u32_65536_);;
    w.endObject();
}

export inline specodec::SpecCodec<EdgeBoundary> EdgeBoundaryCodec = {
    .encode = [](specodec::SpecWriter& w, const EdgeBoundary& obj) { write_edge_boundary(w, obj); },
    .decode = [](specodec::SpecReader& r) -> EdgeBoundary {
        std::int32_t fld_i32_neg129 = 0;
        std::int32_t fld_i32_128 = 0;
        std::int32_t fld_i32_256 = 0;
        std::int32_t fld_i32_65536 = 0;
        std::int32_t fld_i32_neg32769 = 0;
        std::uint32_t fld_u32_65536 = 0u;
        r.beginObject();
        while (r.hasNextField()) {
            auto field_name = r.readFieldName();
            if (field_name == "i32_neg129") { fld_i32_neg129 = r.readInt32(); }
            else if (field_name == "i32_128") { fld_i32_128 = r.readInt32(); }
            else if (field_name == "i32_256") { fld_i32_256 = r.readInt32(); }
            else if (field_name == "i32_65536") { fld_i32_65536 = r.readInt32(); }
            else if (field_name == "i32_neg32769") { fld_i32_neg32769 = r.readInt32(); }
            else if (field_name == "u32_65536") { fld_u32_65536 = r.readUint32(); }
            else { r.skip(); }
        }
        r.endObject();
        return EdgeBoundary{fld_i32_neg129, fld_i32_128, fld_i32_256, fld_i32_65536, fld_i32_neg32769, fld_u32_65536};
    }
};

export struct EdgeStrLen {
    std::string s31_;
    std::string s32_;
    std::string s255_;
    std::string s256_;
};

export inline void write_edge_str_len(specodec::SpecWriter& w, const EdgeStrLen& obj) {
    w.beginObject(4);
    w.writeField("s31"); w.writeString(obj.s31_);;
    w.writeField("s32"); w.writeString(obj.s32_);;
    w.writeField("s255"); w.writeString(obj.s255_);;
    w.writeField("s256"); w.writeString(obj.s256_);;
    w.endObject();
}

export inline specodec::SpecCodec<EdgeStrLen> EdgeStrLenCodec = {
    .encode = [](specodec::SpecWriter& w, const EdgeStrLen& obj) { write_edge_str_len(w, obj); },
    .decode = [](specodec::SpecReader& r) -> EdgeStrLen {
        std::string fld_s31 = "";
        std::string fld_s32 = "";
        std::string fld_s255 = "";
        std::string fld_s256 = "";
        r.beginObject();
        while (r.hasNextField()) {
            auto field_name = r.readFieldName();
            if (field_name == "s31") { fld_s31 = r.readString(); }
            else if (field_name == "s32") { fld_s32 = r.readString(); }
            else if (field_name == "s255") { fld_s255 = r.readString(); }
            else if (field_name == "s256") { fld_s256 = r.readString(); }
            else { r.skip(); }
        }
        r.endObject();
        return EdgeStrLen{fld_s31, fld_s32, fld_s255, fld_s256};
    }
};

export struct EdgeBytesLen {
    std::vector<std::uint8_t> b31_;
    std::vector<std::uint8_t> b32_;
    std::vector<std::uint8_t> b255_;
    std::vector<std::uint8_t> b256_;
};

export inline void write_edge_bytes_len(specodec::SpecWriter& w, const EdgeBytesLen& obj) {
    w.beginObject(4);
    w.writeField("b31"); w.writeBytes(obj.b31_);;
    w.writeField("b32"); w.writeBytes(obj.b32_);;
    w.writeField("b255"); w.writeBytes(obj.b255_);;
    w.writeField("b256"); w.writeBytes(obj.b256_);;
    w.endObject();
}

export inline specodec::SpecCodec<EdgeBytesLen> EdgeBytesLenCodec = {
    .encode = [](specodec::SpecWriter& w, const EdgeBytesLen& obj) { write_edge_bytes_len(w, obj); },
    .decode = [](specodec::SpecReader& r) -> EdgeBytesLen {
        std::vector<std::uint8_t> fld_b31 = {};
        std::vector<std::uint8_t> fld_b32 = {};
        std::vector<std::uint8_t> fld_b255 = {};
        std::vector<std::uint8_t> fld_b256 = {};
        r.beginObject();
        while (r.hasNextField()) {
            auto field_name = r.readFieldName();
            if (field_name == "b31") { fld_b31 = r.readBytes(); }
            else if (field_name == "b32") { fld_b32 = r.readBytes(); }
            else if (field_name == "b255") { fld_b255 = r.readBytes(); }
            else if (field_name == "b256") { fld_b256 = r.readBytes(); }
            else { r.skip(); }
        }
        r.endObject();
        return EdgeBytesLen{fld_b31, fld_b32, fld_b255, fld_b256};
    }
};

export struct EdgeArrEmpty {
    std::vector<std::string> items_;
};

export inline void write_edge_arr_empty(specodec::SpecWriter& w, const EdgeArrEmpty& obj) {
    w.beginObject(1);
    w.writeField("items"); 
        w.beginArray(obj.items_.size());
        for (const auto& elem : obj.items_) { w.nextElement(); w.writeString(elem); }
        w.endArray();
    w.endObject();
}

export inline specodec::SpecCodec<EdgeArrEmpty> EdgeArrEmptyCodec = {
    .encode = [](specodec::SpecWriter& w, const EdgeArrEmpty& obj) { write_edge_arr_empty(w, obj); },
    .decode = [](specodec::SpecReader& r) -> EdgeArrEmpty {
        std::vector<std::string> fld_items = {};
        r.beginObject();
        while (r.hasNextField()) {
            auto field_name = r.readFieldName();
            if (field_name == "items") { fld_items = [&]() {
    std::vector<std::string> result;
    r.beginArray();
    while (r.hasNextElement()) { result.push_back(r.readString()); }
    r.endArray();
    return result;
}(); }
            else { r.skip(); }
        }
        r.endObject();
        return EdgeArrEmpty{fld_items};
    }
};

export struct EdgeArrBoundary {
    std::vector<std::int32_t> a15_;
    std::vector<std::int32_t> a16_;
};

export inline void write_edge_arr_boundary(specodec::SpecWriter& w, const EdgeArrBoundary& obj) {
    w.beginObject(2);
    w.writeField("a15"); 
        w.beginArray(obj.a15_.size());
        for (const auto& elem : obj.a15_) { w.nextElement(); w.writeInt32(elem); }
        w.endArray();
    w.writeField("a16"); 
        w.beginArray(obj.a16_.size());
        for (const auto& elem : obj.a16_) { w.nextElement(); w.writeInt32(elem); }
        w.endArray();
    w.endObject();
}

export inline specodec::SpecCodec<EdgeArrBoundary> EdgeArrBoundaryCodec = {
    .encode = [](specodec::SpecWriter& w, const EdgeArrBoundary& obj) { write_edge_arr_boundary(w, obj); },
    .decode = [](specodec::SpecReader& r) -> EdgeArrBoundary {
        std::vector<std::int32_t> fld_a15 = {};
        std::vector<std::int32_t> fld_a16 = {};
        r.beginObject();
        while (r.hasNextField()) {
            auto field_name = r.readFieldName();
            if (field_name == "a15") { fld_a15 = [&]() {
    std::vector<std::int32_t> result;
    r.beginArray();
    while (r.hasNextElement()) { result.push_back(r.readInt32()); }
    r.endArray();
    return result;
}(); }
            else if (field_name == "a16") { fld_a16 = [&]() {
    std::vector<std::int32_t> result;
    r.beginArray();
    while (r.hasNextElement()) { result.push_back(r.readInt32()); }
    r.endArray();
    return result;
}(); }
            else { r.skip(); }
        }
        r.endObject();
        return EdgeArrBoundary{fld_a15, fld_a16};
    }
};

} // namespace all_types_edge