// Generated by @specodec/typespec-emitter-cpp. DO NOT EDIT.
export module all_types_extra;
import std;
import specodec;
import all_types;
using namespace all_types;

namespace all_types_extra {

export struct OptArr1 {
    std::string req_;
    std::optional<std::vector<std::int32_t>> items_;
};

export inline void write_opt_arr1(specodec::SpecWriter& w, const OptArr1& obj) {
    int field_count = 1;
    if (obj.items_.has_value()) field_count++;
    w.beginObject(field_count);
    w.writeField("req"); w.writeString(obj.req_);;
    if (obj.items_.has_value()) { w.writeField("items"); 
        w.beginArray(obj.items_.value().size());
        for (const auto& elem : obj.items_.value()) { w.nextElement(); w.writeInt32(elem); }
        w.endArray(); }
    w.endObject();
}

export inline specodec::SpecCodec<OptArr1> OptArr1Codec = {
    .encode = [](specodec::SpecWriter& w, const OptArr1& obj) { write_opt_arr1(w, obj); },
    .decode = [](specodec::SpecReader& r) -> OptArr1 {
        std::string fld_req = "";
        std::optional<std::vector<std::int32_t>> fld_items;
        r.beginObject();
        while (r.hasNextField()) {
            auto field_name = r.readFieldName();
            if (field_name == "req") { fld_req = r.readString(); }
            else if (field_name == "items") { fld_items = std::optional<std::vector<std::int32_t>>{[&]() {
    std::vector<std::int32_t> result;
    r.beginArray();
    while (r.hasNextElement()) { result.push_back(r.readInt32()); }
    r.endArray();
    return result;
}()}; }
            else { r.skip(); }
        }
        r.endObject();
        return OptArr1{fld_req, fld_items};
    }
};

export struct OptArr2 {
    std::int32_t id_;
    std::optional<std::vector<std::string>> names_;
    std::optional<std::vector<bool>> flags_;
};

export inline void write_opt_arr2(specodec::SpecWriter& w, const OptArr2& obj) {
    int field_count = 1;
    if (obj.names_.has_value()) field_count++;
    if (obj.flags_.has_value()) field_count++;
    w.beginObject(field_count);
    w.writeField("id"); w.writeInt32(obj.id_);;
    if (obj.names_.has_value()) { w.writeField("names"); 
        w.beginArray(obj.names_.value().size());
        for (const auto& elem : obj.names_.value()) { w.nextElement(); w.writeString(elem); }
        w.endArray(); }
    if (obj.flags_.has_value()) { w.writeField("flags"); 
        w.beginArray(obj.flags_.value().size());
        for (const auto& elem : obj.flags_.value()) { w.nextElement(); w.writeBool(elem); }
        w.endArray(); }
    w.endObject();
}

export inline specodec::SpecCodec<OptArr2> OptArr2Codec = {
    .encode = [](specodec::SpecWriter& w, const OptArr2& obj) { write_opt_arr2(w, obj); },
    .decode = [](specodec::SpecReader& r) -> OptArr2 {
        std::int32_t fld_id = 0;
        std::optional<std::vector<std::string>> fld_names;
        std::optional<std::vector<bool>> fld_flags;
        r.beginObject();
        while (r.hasNextField()) {
            auto field_name = r.readFieldName();
            if (field_name == "id") { fld_id = r.readInt32(); }
            else if (field_name == "names") { fld_names = std::optional<std::vector<std::string>>{[&]() {
    std::vector<std::string> result;
    r.beginArray();
    while (r.hasNextElement()) { result.push_back(r.readString()); }
    r.endArray();
    return result;
}()}; }
            else if (field_name == "flags") { fld_flags = std::optional<std::vector<bool>>{[&]() {
    std::vector<bool> result;
    r.beginArray();
    while (r.hasNextElement()) { result.push_back(r.readBool()); }
    r.endArray();
    return result;
}()}; }
            else { r.skip(); }
        }
        r.endObject();
        return OptArr2{fld_id, fld_names, fld_flags};
    }
};

export struct OptArr3 {
    std::optional<std::vector<std::string>> a_;
    std::optional<std::vector<double>> b_;
};

export inline void write_opt_arr3(specodec::SpecWriter& w, const OptArr3& obj) {
    int field_count = 0;
    if (obj.a_.has_value()) field_count++;
    if (obj.b_.has_value()) field_count++;
    w.beginObject(field_count);
    if (obj.a_.has_value()) { w.writeField("a"); 
        w.beginArray(obj.a_.value().size());
        for (const auto& elem : obj.a_.value()) { w.nextElement(); w.writeString(elem); }
        w.endArray(); }
    if (obj.b_.has_value()) { w.writeField("b"); 
        w.beginArray(obj.b_.value().size());
        for (const auto& elem : obj.b_.value()) { w.nextElement(); w.writeFloat64(elem); }
        w.endArray(); }
    w.endObject();
}

export inline specodec::SpecCodec<OptArr3> OptArr3Codec = {
    .encode = [](specodec::SpecWriter& w, const OptArr3& obj) { write_opt_arr3(w, obj); },
    .decode = [](specodec::SpecReader& r) -> OptArr3 {
        std::optional<std::vector<std::string>> fld_a;
        std::optional<std::vector<double>> fld_b;
        r.beginObject();
        while (r.hasNextField()) {
            auto field_name = r.readFieldName();
            if (field_name == "a") { fld_a = std::optional<std::vector<std::string>>{[&]() {
    std::vector<std::string> result;
    r.beginArray();
    while (r.hasNextElement()) { result.push_back(r.readString()); }
    r.endArray();
    return result;
}()}; }
            else if (field_name == "b") { fld_b = std::optional<std::vector<double>>{[&]() {
    std::vector<double> result;
    r.beginArray();
    while (r.hasNextElement()) { result.push_back(r.readFloat64()); }
    r.endArray();
    return result;
}()}; }
            else { r.skip(); }
        }
        r.endObject();
        return OptArr3{fld_a, fld_b};
    }
};

export struct OptArr4 {
    std::vector<std::uint8_t> payload_;
    std::optional<std::vector<std::vector<std::uint8_t>>> chunks_;
};

export inline void write_opt_arr4(specodec::SpecWriter& w, const OptArr4& obj) {
    int field_count = 1;
    if (obj.chunks_.has_value()) field_count++;
    w.beginObject(field_count);
    w.writeField("payload"); w.writeBytes(obj.payload_);;
    if (obj.chunks_.has_value()) { w.writeField("chunks"); 
        w.beginArray(obj.chunks_.value().size());
        for (const auto& elem : obj.chunks_.value()) { w.nextElement(); w.writeBytes(elem); }
        w.endArray(); }
    w.endObject();
}

export inline specodec::SpecCodec<OptArr4> OptArr4Codec = {
    .encode = [](specodec::SpecWriter& w, const OptArr4& obj) { write_opt_arr4(w, obj); },
    .decode = [](specodec::SpecReader& r) -> OptArr4 {
        std::vector<std::uint8_t> fld_payload = {};
        std::optional<std::vector<std::vector<std::uint8_t>>> fld_chunks;
        r.beginObject();
        while (r.hasNextField()) {
            auto field_name = r.readFieldName();
            if (field_name == "payload") { fld_payload = r.readBytes(); }
            else if (field_name == "chunks") { fld_chunks = std::optional<std::vector<std::vector<std::uint8_t>>>{[&]() {
    std::vector<std::vector<std::uint8_t>> result;
    r.beginArray();
    while (r.hasNextElement()) { result.push_back(r.readBytes()); }
    r.endArray();
    return result;
}()}; }
            else { r.skip(); }
        }
        r.endObject();
        return OptArr4{fld_payload, fld_chunks};
    }
};

export struct OptArr5 {
    std::optional<std::vector<Inner>> models_;
    std::string name_;
};

export inline void write_opt_arr5(specodec::SpecWriter& w, const OptArr5& obj) {
    int field_count = 1;
    if (obj.models_.has_value()) field_count++;
    w.beginObject(field_count);
    if (obj.models_.has_value()) { w.writeField("models"); 
        w.beginArray(obj.models_.value().size());
        for (const auto& elem : obj.models_.value()) { w.nextElement(); write_inner(w, elem); }
        w.endArray(); }
    w.writeField("name"); w.writeString(obj.name_);;
    w.endObject();
}

export inline specodec::SpecCodec<OptArr5> OptArr5Codec = {
    .encode = [](specodec::SpecWriter& w, const OptArr5& obj) { write_opt_arr5(w, obj); },
    .decode = [](specodec::SpecReader& r) -> OptArr5 {
        std::optional<std::vector<Inner>> fld_models;
        std::string fld_name = "";
        r.beginObject();
        while (r.hasNextField()) {
            auto field_name = r.readFieldName();
            if (field_name == "models") { fld_models = std::optional<std::vector<Inner>>{[&]() {
    std::vector<Inner> result;
    r.beginArray();
    while (r.hasNextElement()) { result.push_back(InnerCodec.decode(r)); }
    r.endArray();
    return result;
}()}; }
            else if (field_name == "name") { fld_name = r.readString(); }
            else { r.skip(); }
        }
        r.endObject();
        return OptArr5{fld_models, fld_name};
    }
};

export struct NestOpt1 {
    Label outer_;
    std::string name_;
};

export inline void write_nest_opt1(specodec::SpecWriter& w, const NestOpt1& obj) {
    w.beginObject(2);
    w.writeField("outer"); write_label(w, obj.outer_);;
    w.writeField("name"); w.writeString(obj.name_);;
    w.endObject();
}

export inline specodec::SpecCodec<NestOpt1> NestOpt1Codec = {
    .encode = [](specodec::SpecWriter& w, const NestOpt1& obj) { write_nest_opt1(w, obj); },
    .decode = [](specodec::SpecReader& r) -> NestOpt1 {
        Label fld_outer = {};
        std::string fld_name = "";
        r.beginObject();
        while (r.hasNextField()) {
            auto field_name = r.readFieldName();
            if (field_name == "outer") { fld_outer = LabelCodec.decode(r); }
            else if (field_name == "name") { fld_name = r.readString(); }
            else { r.skip(); }
        }
        r.endObject();
        return NestOpt1{fld_outer, fld_name};
    }
};

export struct NestOpt2 {
    std::optional<IdVal> a_;
    std::optional<IdVal> b_;
    std::optional<IdVal> c_;
};

export inline void write_nest_opt2(specodec::SpecWriter& w, const NestOpt2& obj) {
    int field_count = 0;
    if (obj.a_.has_value()) field_count++;
    if (obj.b_.has_value()) field_count++;
    if (obj.c_.has_value()) field_count++;
    w.beginObject(field_count);
    if (obj.a_.has_value()) { w.writeField("a"); write_id_val(w, obj.a_.value());; }
    if (obj.b_.has_value()) { w.writeField("b"); write_id_val(w, obj.b_.value());; }
    if (obj.c_.has_value()) { w.writeField("c"); write_id_val(w, obj.c_.value());; }
    w.endObject();
}

export inline specodec::SpecCodec<NestOpt2> NestOpt2Codec = {
    .encode = [](specodec::SpecWriter& w, const NestOpt2& obj) { write_nest_opt2(w, obj); },
    .decode = [](specodec::SpecReader& r) -> NestOpt2 {
        std::optional<IdVal> fld_a;
        std::optional<IdVal> fld_b;
        std::optional<IdVal> fld_c;
        r.beginObject();
        while (r.hasNextField()) {
            auto field_name = r.readFieldName();
            if (field_name == "a") { fld_a = std::optional<IdVal>{(r.isNull() ? (r.readNull(), std::optional<IdVal>{std::nullopt}) : std::optional<IdVal>{IdValCodec.decode(r)})}; }
            else if (field_name == "b") { fld_b = std::optional<IdVal>{(r.isNull() ? (r.readNull(), std::optional<IdVal>{std::nullopt}) : std::optional<IdVal>{IdValCodec.decode(r)})}; }
            else if (field_name == "c") { fld_c = std::optional<IdVal>{(r.isNull() ? (r.readNull(), std::optional<IdVal>{std::nullopt}) : std::optional<IdVal>{IdValCodec.decode(r)})}; }
            else { r.skip(); }
        }
        r.endObject();
        return NestOpt2{fld_a, fld_b, fld_c};
    }
};

export struct NestOpt3 {
    Money money_;
    std::optional<Range32> value_range_;
};

export inline void write_nest_opt3(specodec::SpecWriter& w, const NestOpt3& obj) {
    int field_count = 1;
    if (obj.value_range_.has_value()) field_count++;
    w.beginObject(field_count);
    w.writeField("money"); write_money(w, obj.money_);;
    if (obj.value_range_.has_value()) { w.writeField("value_range"); write_range32(w, obj.value_range_.value());; }
    w.endObject();
}

export inline specodec::SpecCodec<NestOpt3> NestOpt3Codec = {
    .encode = [](specodec::SpecWriter& w, const NestOpt3& obj) { write_nest_opt3(w, obj); },
    .decode = [](specodec::SpecReader& r) -> NestOpt3 {
        Money fld_money = {};
        std::optional<Range32> fld_value_range;
        r.beginObject();
        while (r.hasNextField()) {
            auto field_name = r.readFieldName();
            if (field_name == "money") { fld_money = MoneyCodec.decode(r); }
            else if (field_name == "value_range") { fld_value_range = std::optional<Range32>{(r.isNull() ? (r.readNull(), std::optional<Range32>{std::nullopt}) : std::optional<Range32>{Range32Codec.decode(r)})}; }
            else { r.skip(); }
        }
        r.endObject();
        return NestOpt3{fld_money, fld_value_range};
    }
};

export struct NestOpt4 {
    std::optional<Addr> addr_;
    std::optional<Coord> coord_;
    std::string name_;
};

export inline void write_nest_opt4(specodec::SpecWriter& w, const NestOpt4& obj) {
    int field_count = 1;
    if (obj.addr_.has_value()) field_count++;
    if (obj.coord_.has_value()) field_count++;
    w.beginObject(field_count);
    if (obj.addr_.has_value()) { w.writeField("addr"); write_addr(w, obj.addr_.value());; }
    if (obj.coord_.has_value()) { w.writeField("coord"); write_coord(w, obj.coord_.value());; }
    w.writeField("name"); w.writeString(obj.name_);;
    w.endObject();
}

export inline specodec::SpecCodec<NestOpt4> NestOpt4Codec = {
    .encode = [](specodec::SpecWriter& w, const NestOpt4& obj) { write_nest_opt4(w, obj); },
    .decode = [](specodec::SpecReader& r) -> NestOpt4 {
        std::optional<Addr> fld_addr;
        std::optional<Coord> fld_coord;
        std::string fld_name = "";
        r.beginObject();
        while (r.hasNextField()) {
            auto field_name = r.readFieldName();
            if (field_name == "addr") { fld_addr = std::optional<Addr>{(r.isNull() ? (r.readNull(), std::optional<Addr>{std::nullopt}) : std::optional<Addr>{AddrCodec.decode(r)})}; }
            else if (field_name == "coord") { fld_coord = std::optional<Coord>{(r.isNull() ? (r.readNull(), std::optional<Coord>{std::nullopt}) : std::optional<Coord>{CoordCodec.decode(r)})}; }
            else if (field_name == "name") { fld_name = r.readString(); }
            else { r.skip(); }
        }
        r.endObject();
        return NestOpt4{fld_addr, fld_coord, fld_name};
    }
};

export struct NestOpt5 {
    Point3 point_;
    Addr addr_;
    std::optional<Label> label_;
};

export inline void write_nest_opt5(specodec::SpecWriter& w, const NestOpt5& obj) {
    int field_count = 2;
    if (obj.label_.has_value()) field_count++;
    w.beginObject(field_count);
    w.writeField("point"); write_point3(w, obj.point_);;
    w.writeField("addr"); write_addr(w, obj.addr_);;
    if (obj.label_.has_value()) { w.writeField("label"); write_label(w, obj.label_.value());; }
    w.endObject();
}

export inline specodec::SpecCodec<NestOpt5> NestOpt5Codec = {
    .encode = [](specodec::SpecWriter& w, const NestOpt5& obj) { write_nest_opt5(w, obj); },
    .decode = [](specodec::SpecReader& r) -> NestOpt5 {
        Point3 fld_point = {};
        Addr fld_addr = {};
        std::optional<Label> fld_label;
        r.beginObject();
        while (r.hasNextField()) {
            auto field_name = r.readFieldName();
            if (field_name == "point") { fld_point = Point3Codec.decode(r); }
            else if (field_name == "addr") { fld_addr = AddrCodec.decode(r); }
            else if (field_name == "label") { fld_label = std::optional<Label>{(r.isNull() ? (r.readNull(), std::optional<Label>{std::nullopt}) : std::optional<Label>{LabelCodec.decode(r)})}; }
            else { r.skip(); }
        }
        r.endObject();
        return NestOpt5{fld_point, fld_addr, fld_label};
    }
};

export struct NestOptInner1 {
    std::string tag_;
    std::optional<OptInner> nested_;
};

export inline void write_nest_opt_inner1(specodec::SpecWriter& w, const NestOptInner1& obj) {
    int field_count = 1;
    if (obj.nested_.has_value()) field_count++;
    w.beginObject(field_count);
    w.writeField("tag"); w.writeString(obj.tag_);;
    if (obj.nested_.has_value()) { w.writeField("nested"); write_opt_inner(w, obj.nested_.value());; }
    w.endObject();
}

export inline specodec::SpecCodec<NestOptInner1> NestOptInner1Codec = {
    .encode = [](specodec::SpecWriter& w, const NestOptInner1& obj) { write_nest_opt_inner1(w, obj); },
    .decode = [](specodec::SpecReader& r) -> NestOptInner1 {
        std::string fld_tag = "";
        std::optional<OptInner> fld_nested;
        r.beginObject();
        while (r.hasNextField()) {
            auto field_name = r.readFieldName();
            if (field_name == "tag") { fld_tag = r.readString(); }
            else if (field_name == "nested") { fld_nested = std::optional<OptInner>{(r.isNull() ? (r.readNull(), std::optional<OptInner>{std::nullopt}) : std::optional<OptInner>{OptInnerCodec.decode(r)})}; }
            else { r.skip(); }
        }
        r.endObject();
        return NestOptInner1{fld_tag, fld_nested};
    }
};

export struct NestOptInner2 {
    std::string tag_;
    OptInner nested_;
};

export inline void write_nest_opt_inner2(specodec::SpecWriter& w, const NestOptInner2& obj) {
    w.beginObject(2);
    w.writeField("tag"); w.writeString(obj.tag_);;
    w.writeField("nested"); write_opt_inner(w, obj.nested_);;
    w.endObject();
}

export inline specodec::SpecCodec<NestOptInner2> NestOptInner2Codec = {
    .encode = [](specodec::SpecWriter& w, const NestOptInner2& obj) { write_nest_opt_inner2(w, obj); },
    .decode = [](specodec::SpecReader& r) -> NestOptInner2 {
        std::string fld_tag = "";
        OptInner fld_nested = {};
        r.beginObject();
        while (r.hasNextField()) {
            auto field_name = r.readFieldName();
            if (field_name == "tag") { fld_tag = r.readString(); }
            else if (field_name == "nested") { fld_nested = OptInnerCodec.decode(r); }
            else { r.skip(); }
        }
        r.endObject();
        return NestOptInner2{fld_tag, fld_nested};
    }
};

export struct NestOptInner3 {
    std::optional<OptInner> outer_;
    std::optional<OptInner> nested_;
};

export inline void write_nest_opt_inner3(specodec::SpecWriter& w, const NestOptInner3& obj) {
    int field_count = 0;
    if (obj.outer_.has_value()) field_count++;
    if (obj.nested_.has_value()) field_count++;
    w.beginObject(field_count);
    if (obj.outer_.has_value()) { w.writeField("outer"); write_opt_inner(w, obj.outer_.value());; }
    if (obj.nested_.has_value()) { w.writeField("nested"); write_opt_inner(w, obj.nested_.value());; }
    w.endObject();
}

export inline specodec::SpecCodec<NestOptInner3> NestOptInner3Codec = {
    .encode = [](specodec::SpecWriter& w, const NestOptInner3& obj) { write_nest_opt_inner3(w, obj); },
    .decode = [](specodec::SpecReader& r) -> NestOptInner3 {
        std::optional<OptInner> fld_outer;
        std::optional<OptInner> fld_nested;
        r.beginObject();
        while (r.hasNextField()) {
            auto field_name = r.readFieldName();
            if (field_name == "outer") { fld_outer = std::optional<OptInner>{(r.isNull() ? (r.readNull(), std::optional<OptInner>{std::nullopt}) : std::optional<OptInner>{OptInnerCodec.decode(r)})}; }
            else if (field_name == "nested") { fld_nested = std::optional<OptInner>{(r.isNull() ? (r.readNull(), std::optional<OptInner>{std::nullopt}) : std::optional<OptInner>{OptInnerCodec.decode(r)})}; }
            else { r.skip(); }
        }
        r.endObject();
        return NestOptInner3{fld_outer, fld_nested};
    }
};

export struct DeepNest1 {
    std::string label_;
    Addr nested_;
};

export inline void write_deep_nest1(specodec::SpecWriter& w, const DeepNest1& obj) {
    w.beginObject(2);
    w.writeField("label"); w.writeString(obj.label_);;
    w.writeField("nested"); write_addr(w, obj.nested_);;
    w.endObject();
}

export inline specodec::SpecCodec<DeepNest1> DeepNest1Codec = {
    .encode = [](specodec::SpecWriter& w, const DeepNest1& obj) { write_deep_nest1(w, obj); },
    .decode = [](specodec::SpecReader& r) -> DeepNest1 {
        std::string fld_label = "";
        Addr fld_nested = {};
        r.beginObject();
        while (r.hasNextField()) {
            auto field_name = r.readFieldName();
            if (field_name == "label") { fld_label = r.readString(); }
            else if (field_name == "nested") { fld_nested = AddrCodec.decode(r); }
            else { r.skip(); }
        }
        r.endObject();
        return DeepNest1{fld_label, fld_nested};
    }
};

export struct DeepNest2 {
    std::string name_;
    Money money_;
    Addr addr_;
};

export inline void write_deep_nest2(specodec::SpecWriter& w, const DeepNest2& obj) {
    w.beginObject(3);
    w.writeField("name"); w.writeString(obj.name_);;
    w.writeField("money"); write_money(w, obj.money_);;
    w.writeField("addr"); write_addr(w, obj.addr_);;
    w.endObject();
}

export inline specodec::SpecCodec<DeepNest2> DeepNest2Codec = {
    .encode = [](specodec::SpecWriter& w, const DeepNest2& obj) { write_deep_nest2(w, obj); },
    .decode = [](specodec::SpecReader& r) -> DeepNest2 {
        std::string fld_name = "";
        Money fld_money = {};
        Addr fld_addr = {};
        r.beginObject();
        while (r.hasNextField()) {
            auto field_name = r.readFieldName();
            if (field_name == "name") { fld_name = r.readString(); }
            else if (field_name == "money") { fld_money = MoneyCodec.decode(r); }
            else if (field_name == "addr") { fld_addr = AddrCodec.decode(r); }
            else { r.skip(); }
        }
        r.endObject();
        return DeepNest2{fld_name, fld_money, fld_addr};
    }
};

export struct DeepNest3 {
    std::string title_;
    Point3 point_;
    Range32 value_range_;
    Money money_;
};

export inline void write_deep_nest3(specodec::SpecWriter& w, const DeepNest3& obj) {
    w.beginObject(4);
    w.writeField("title"); w.writeString(obj.title_);;
    w.writeField("point"); write_point3(w, obj.point_);;
    w.writeField("value_range"); write_range32(w, obj.value_range_);;
    w.writeField("money"); write_money(w, obj.money_);;
    w.endObject();
}

export inline specodec::SpecCodec<DeepNest3> DeepNest3Codec = {
    .encode = [](specodec::SpecWriter& w, const DeepNest3& obj) { write_deep_nest3(w, obj); },
    .decode = [](specodec::SpecReader& r) -> DeepNest3 {
        std::string fld_title = "";
        Point3 fld_point = {};
        Range32 fld_value_range = {};
        Money fld_money = {};
        r.beginObject();
        while (r.hasNextField()) {
            auto field_name = r.readFieldName();
            if (field_name == "title") { fld_title = r.readString(); }
            else if (field_name == "point") { fld_point = Point3Codec.decode(r); }
            else if (field_name == "value_range") { fld_value_range = Range32Codec.decode(r); }
            else if (field_name == "money") { fld_money = MoneyCodec.decode(r); }
            else { r.skip(); }
        }
        r.endObject();
        return DeepNest3{fld_title, fld_point, fld_value_range, fld_money};
    }
};

export struct DeepNest4 {
    std::vector<Coord> coords_;
    Inner nested_;
    std::string tag_;
};

export inline void write_deep_nest4(specodec::SpecWriter& w, const DeepNest4& obj) {
    w.beginObject(3);
    w.writeField("coords"); 
        w.beginArray(obj.coords_.size());
        for (const auto& elem : obj.coords_) { w.nextElement(); write_coord(w, elem); }
        w.endArray();
    w.writeField("nested"); write_inner(w, obj.nested_);;
    w.writeField("tag"); w.writeString(obj.tag_);;
    w.endObject();
}

export inline specodec::SpecCodec<DeepNest4> DeepNest4Codec = {
    .encode = [](specodec::SpecWriter& w, const DeepNest4& obj) { write_deep_nest4(w, obj); },
    .decode = [](specodec::SpecReader& r) -> DeepNest4 {
        std::vector<Coord> fld_coords = {};
        Inner fld_nested = {};
        std::string fld_tag = "";
        r.beginObject();
        while (r.hasNextField()) {
            auto field_name = r.readFieldName();
            if (field_name == "coords") { fld_coords = [&]() {
    std::vector<Coord> result;
    r.beginArray();
    while (r.hasNextElement()) { result.push_back(CoordCodec.decode(r)); }
    r.endArray();
    return result;
}(); }
            else if (field_name == "nested") { fld_nested = InnerCodec.decode(r); }
            else if (field_name == "tag") { fld_tag = r.readString(); }
            else { r.skip(); }
        }
        r.endObject();
        return DeepNest4{fld_coords, fld_nested, fld_tag};
    }
};

export struct DeepNest5 {
    std::vector<Label> labels_;
    Money money_;
    std::string name_;
};

export inline void write_deep_nest5(specodec::SpecWriter& w, const DeepNest5& obj) {
    w.beginObject(3);
    w.writeField("labels"); 
        w.beginArray(obj.labels_.size());
        for (const auto& elem : obj.labels_) { w.nextElement(); write_label(w, elem); }
        w.endArray();
    w.writeField("money"); write_money(w, obj.money_);;
    w.writeField("name"); w.writeString(obj.name_);;
    w.endObject();
}

export inline specodec::SpecCodec<DeepNest5> DeepNest5Codec = {
    .encode = [](specodec::SpecWriter& w, const DeepNest5& obj) { write_deep_nest5(w, obj); },
    .decode = [](specodec::SpecReader& r) -> DeepNest5 {
        std::vector<Label> fld_labels = {};
        Money fld_money = {};
        std::string fld_name = "";
        r.beginObject();
        while (r.hasNextField()) {
            auto field_name = r.readFieldName();
            if (field_name == "labels") { fld_labels = [&]() {
    std::vector<Label> result;
    r.beginArray();
    while (r.hasNextElement()) { result.push_back(LabelCodec.decode(r)); }
    r.endArray();
    return result;
}(); }
            else if (field_name == "money") { fld_money = MoneyCodec.decode(r); }
            else if (field_name == "name") { fld_name = r.readString(); }
            else { r.skip(); }
        }
        r.endObject();
        return DeepNest5{fld_labels, fld_money, fld_name};
    }
};

export struct DeepNest6 {
    std::vector<IdVal> items_;
    std::optional<Addr> addr_;
    Coord coord_;
};

export inline void write_deep_nest6(specodec::SpecWriter& w, const DeepNest6& obj) {
    int field_count = 2;
    if (obj.addr_.has_value()) field_count++;
    w.beginObject(field_count);
    w.writeField("items"); 
        w.beginArray(obj.items_.size());
        for (const auto& elem : obj.items_) { w.nextElement(); write_id_val(w, elem); }
        w.endArray();
    if (obj.addr_.has_value()) { w.writeField("addr"); write_addr(w, obj.addr_.value());; }
    w.writeField("coord"); write_coord(w, obj.coord_);;
    w.endObject();
}

export inline specodec::SpecCodec<DeepNest6> DeepNest6Codec = {
    .encode = [](specodec::SpecWriter& w, const DeepNest6& obj) { write_deep_nest6(w, obj); },
    .decode = [](specodec::SpecReader& r) -> DeepNest6 {
        std::vector<IdVal> fld_items = {};
        std::optional<Addr> fld_addr;
        Coord fld_coord = {};
        r.beginObject();
        while (r.hasNextField()) {
            auto field_name = r.readFieldName();
            if (field_name == "items") { fld_items = [&]() {
    std::vector<IdVal> result;
    r.beginArray();
    while (r.hasNextElement()) { result.push_back(IdValCodec.decode(r)); }
    r.endArray();
    return result;
}(); }
            else if (field_name == "addr") { fld_addr = std::optional<Addr>{(r.isNull() ? (r.readNull(), std::optional<Addr>{std::nullopt}) : std::optional<Addr>{AddrCodec.decode(r)})}; }
            else if (field_name == "coord") { fld_coord = CoordCodec.decode(r); }
            else { r.skip(); }
        }
        r.endObject();
        return DeepNest6{fld_items, fld_addr, fld_coord};
    }
};

export struct DeepNest7 {
    Addr a_;
    Addr b_;
    Addr c_;
};

export inline void write_deep_nest7(specodec::SpecWriter& w, const DeepNest7& obj) {
    w.beginObject(3);
    w.writeField("a"); write_addr(w, obj.a_);;
    w.writeField("b"); write_addr(w, obj.b_);;
    w.writeField("c"); write_addr(w, obj.c_);;
    w.endObject();
}

export inline specodec::SpecCodec<DeepNest7> DeepNest7Codec = {
    .encode = [](specodec::SpecWriter& w, const DeepNest7& obj) { write_deep_nest7(w, obj); },
    .decode = [](specodec::SpecReader& r) -> DeepNest7 {
        Addr fld_a = {};
        Addr fld_b = {};
        Addr fld_c = {};
        r.beginObject();
        while (r.hasNextField()) {
            auto field_name = r.readFieldName();
            if (field_name == "a") { fld_a = AddrCodec.decode(r); }
            else if (field_name == "b") { fld_b = AddrCodec.decode(r); }
            else if (field_name == "c") { fld_c = AddrCodec.decode(r); }
            else { r.skip(); }
        }
        r.endObject();
        return DeepNest7{fld_a, fld_b, fld_c};
    }
};

export struct TimestampEntry {
    std::int64_t ts_;
    std::string event_;
    std::optional<std::vector<std::uint8_t>> payload_;
};

export inline void write_timestamp_entry(specodec::SpecWriter& w, const TimestampEntry& obj) {
    int field_count = 2;
    if (obj.payload_.has_value()) field_count++;
    w.beginObject(field_count);
    w.writeField("ts"); w.writeInt64(obj.ts_);;
    w.writeField("event"); w.writeString(obj.event_);;
    if (obj.payload_.has_value()) { w.writeField("payload"); w.writeBytes(obj.payload_.value());; }
    w.endObject();
}

export inline specodec::SpecCodec<TimestampEntry> TimestampEntryCodec = {
    .encode = [](specodec::SpecWriter& w, const TimestampEntry& obj) { write_timestamp_entry(w, obj); },
    .decode = [](specodec::SpecReader& r) -> TimestampEntry {
        std::int64_t fld_ts = 0LL;
        std::string fld_event = "";
        std::optional<std::vector<std::uint8_t>> fld_payload;
        r.beginObject();
        while (r.hasNextField()) {
            auto field_name = r.readFieldName();
            if (field_name == "ts") { fld_ts = r.readInt64(); }
            else if (field_name == "event") { fld_event = r.readString(); }
            else if (field_name == "payload") { fld_payload = std::optional<std::vector<std::uint8_t>>{r.readBytes()}; }
            else { r.skip(); }
        }
        r.endObject();
        return TimestampEntry{fld_ts, fld_event, fld_payload};
    }
};

export struct ConfigEntry {
    std::string key_;
    std::optional<std::int32_t> int_value_;
    std::optional<std::string> str_value_;
    std::optional<bool> bool_value_;
    std::optional<double> float_value_;
};

export inline void write_config_entry(specodec::SpecWriter& w, const ConfigEntry& obj) {
    int field_count = 1;
    if (obj.int_value_.has_value()) field_count++;
    if (obj.str_value_.has_value()) field_count++;
    if (obj.bool_value_.has_value()) field_count++;
    if (obj.float_value_.has_value()) field_count++;
    w.beginObject(field_count);
    w.writeField("key"); w.writeString(obj.key_);;
    if (obj.int_value_.has_value()) { w.writeField("intValue"); w.writeInt32(obj.int_value_.value());; }
    if (obj.str_value_.has_value()) { w.writeField("strValue"); w.writeString(obj.str_value_.value());; }
    if (obj.bool_value_.has_value()) { w.writeField("boolValue"); w.writeBool(obj.bool_value_.value());; }
    if (obj.float_value_.has_value()) { w.writeField("floatValue"); w.writeFloat64(obj.float_value_.value());; }
    w.endObject();
}

export inline specodec::SpecCodec<ConfigEntry> ConfigEntryCodec = {
    .encode = [](specodec::SpecWriter& w, const ConfigEntry& obj) { write_config_entry(w, obj); },
    .decode = [](specodec::SpecReader& r) -> ConfigEntry {
        std::string fld_key = "";
        std::optional<std::int32_t> fld_int_value;
        std::optional<std::string> fld_str_value;
        std::optional<bool> fld_bool_value;
        std::optional<double> fld_float_value;
        r.beginObject();
        while (r.hasNextField()) {
            auto field_name = r.readFieldName();
            if (field_name == "key") { fld_key = r.readString(); }
            else if (field_name == "intValue") { fld_int_value = std::optional<std::int32_t>{r.readInt32()}; }
            else if (field_name == "strValue") { fld_str_value = std::optional<std::string>{r.readString()}; }
            else if (field_name == "boolValue") { fld_bool_value = std::optional<bool>{r.readBool()}; }
            else if (field_name == "floatValue") { fld_float_value = std::optional<double>{r.readFloat64()}; }
            else { r.skip(); }
        }
        r.endObject();
        return ConfigEntry{fld_key, fld_int_value, fld_str_value, fld_bool_value, fld_float_value};
    }
};

} // namespace all_types_extra