// Generated by @specodec/typespec-emitter-cpp. DO NOT EDIT.
export module all_types_recursive;
import std;
import specodec;
import all_types;
using namespace all_types;

namespace all_types_recursive {

export struct RecList {
    std::int32_t value_;
    std::shared_ptr<RecList> next_;
};

export inline void write_rec_list(specodec::SpecWriter& w, const RecList& obj) {
    int field_count = 1;
    if (obj.next_ != nullptr) field_count++;
    w.beginObject(field_count);
    w.writeField("value"); w.writeInt32(obj.value_);;
    if (obj.next_ != nullptr) { w.writeField("next"); write_rec_list(w, *obj.next_);; }
    w.endObject();
}

export inline specodec::SpecCodec<RecList> RecListCodec = {
    .encode = [](specodec::SpecWriter& w, const RecList& obj) { write_rec_list(w, obj); },
    .decode = [](specodec::SpecReader& r) -> RecList {
        std::int32_t fld_value = 0;
        std::shared_ptr<RecList> fld_next;
        r.beginObject();
        while (r.hasNextField()) {
            auto field_name = r.readFieldName();
            if (field_name == "value") { fld_value = r.readInt32(); }
            else if (field_name == "next") { auto opt = (r.isNull() ? (r.readNull(), std::optional<RecList>{std::nullopt}) : std::optional<RecList>{RecListCodec.decode(r)}); fld_next = opt ? std::make_shared<RecList>(*opt) : nullptr; }
            else { r.skip(); }
        }
        r.endObject();
        return RecList{fld_value, fld_next};
    }
};

export struct RecTree {
    std::string value_;
    std::shared_ptr<RecTree> left_node_;
    std::shared_ptr<RecTree> right_node_;
};

export inline void write_rec_tree(specodec::SpecWriter& w, const RecTree& obj) {
    int field_count = 1;
    if (obj.left_node_ != nullptr) field_count++;
    if (obj.right_node_ != nullptr) field_count++;
    w.beginObject(field_count);
    w.writeField("value"); w.writeString(obj.value_);;
    if (obj.left_node_ != nullptr) { w.writeField("left_node"); write_rec_tree(w, *obj.left_node_);; }
    if (obj.right_node_ != nullptr) { w.writeField("right_node"); write_rec_tree(w, *obj.right_node_);; }
    w.endObject();
}

export inline specodec::SpecCodec<RecTree> RecTreeCodec = {
    .encode = [](specodec::SpecWriter& w, const RecTree& obj) { write_rec_tree(w, obj); },
    .decode = [](specodec::SpecReader& r) -> RecTree {
        std::string fld_value = "";
        std::shared_ptr<RecTree> fld_left_node;
        std::shared_ptr<RecTree> fld_right_node;
        r.beginObject();
        while (r.hasNextField()) {
            auto field_name = r.readFieldName();
            if (field_name == "value") { fld_value = r.readString(); }
            else if (field_name == "left_node") { auto opt = (r.isNull() ? (r.readNull(), std::optional<RecTree>{std::nullopt}) : std::optional<RecTree>{RecTreeCodec.decode(r)}); fld_left_node = opt ? std::make_shared<RecTree>(*opt) : nullptr; }
            else if (field_name == "right_node") { auto opt = (r.isNull() ? (r.readNull(), std::optional<RecTree>{std::nullopt}) : std::optional<RecTree>{RecTreeCodec.decode(r)}); fld_right_node = opt ? std::make_shared<RecTree>(*opt) : nullptr; }
            else { r.skip(); }
        }
        r.endObject();
        return RecTree{fld_value, fld_left_node, fld_right_node};
    }
};

export struct RecChain {
    std::int32_t id_;
    std::string label_;
    std::shared_ptr<RecChain> next_;
};

export inline void write_rec_chain(specodec::SpecWriter& w, const RecChain& obj) {
    int field_count = 2;
    if (obj.next_ != nullptr) field_count++;
    w.beginObject(field_count);
    w.writeField("id"); w.writeInt32(obj.id_);;
    w.writeField("label"); w.writeString(obj.label_);;
    if (obj.next_ != nullptr) { w.writeField("next"); write_rec_chain(w, *obj.next_);; }
    w.endObject();
}

export inline specodec::SpecCodec<RecChain> RecChainCodec = {
    .encode = [](specodec::SpecWriter& w, const RecChain& obj) { write_rec_chain(w, obj); },
    .decode = [](specodec::SpecReader& r) -> RecChain {
        std::int32_t fld_id = 0;
        std::string fld_label = "";
        std::shared_ptr<RecChain> fld_next;
        r.beginObject();
        while (r.hasNextField()) {
            auto field_name = r.readFieldName();
            if (field_name == "id") { fld_id = r.readInt32(); }
            else if (field_name == "label") { fld_label = r.readString(); }
            else if (field_name == "next") { auto opt = (r.isNull() ? (r.readNull(), std::optional<RecChain>{std::nullopt}) : std::optional<RecChain>{RecChainCodec.decode(r)}); fld_next = opt ? std::make_shared<RecChain>(*opt) : nullptr; }
            else { r.skip(); }
        }
        r.endObject();
        return RecChain{fld_id, fld_label, fld_next};
    }
};

export struct RecWrap {
    std::vector<std::uint8_t> payload_;
    std::shared_ptr<RecWrap> nested_;
};

export inline void write_rec_wrap(specodec::SpecWriter& w, const RecWrap& obj) {
    int field_count = 1;
    if (obj.nested_ != nullptr) field_count++;
    w.beginObject(field_count);
    w.writeField("payload"); w.writeBytes(obj.payload_);;
    if (obj.nested_ != nullptr) { w.writeField("nested"); write_rec_wrap(w, *obj.nested_);; }
    w.endObject();
}

export inline specodec::SpecCodec<RecWrap> RecWrapCodec = {
    .encode = [](specodec::SpecWriter& w, const RecWrap& obj) { write_rec_wrap(w, obj); },
    .decode = [](specodec::SpecReader& r) -> RecWrap {
        std::vector<std::uint8_t> fld_payload = {};
        std::shared_ptr<RecWrap> fld_nested;
        r.beginObject();
        while (r.hasNextField()) {
            auto field_name = r.readFieldName();
            if (field_name == "payload") { fld_payload = r.readBytes(); }
            else if (field_name == "nested") { auto opt = (r.isNull() ? (r.readNull(), std::optional<RecWrap>{std::nullopt}) : std::optional<RecWrap>{RecWrapCodec.decode(r)}); fld_nested = opt ? std::make_shared<RecWrap>(*opt) : nullptr; }
            else { r.skip(); }
        }
        r.endObject();
        return RecWrap{fld_payload, fld_nested};
    }
};

export struct RecWide {
    std::int32_t a_;
    std::string b_;
    double c_;
    std::shared_ptr<RecWide> child_;
};

export inline void write_rec_wide(specodec::SpecWriter& w, const RecWide& obj) {
    int field_count = 3;
    if (obj.child_ != nullptr) field_count++;
    w.beginObject(field_count);
    w.writeField("a"); w.writeInt32(obj.a_);;
    w.writeField("b"); w.writeString(obj.b_);;
    w.writeField("c"); w.writeFloat64(obj.c_);;
    if (obj.child_ != nullptr) { w.writeField("child"); write_rec_wide(w, *obj.child_);; }
    w.endObject();
}

export inline specodec::SpecCodec<RecWide> RecWideCodec = {
    .encode = [](specodec::SpecWriter& w, const RecWide& obj) { write_rec_wide(w, obj); },
    .decode = [](specodec::SpecReader& r) -> RecWide {
        std::int32_t fld_a = 0;
        std::string fld_b = "";
        double fld_c = 0.0;
        std::shared_ptr<RecWide> fld_child;
        r.beginObject();
        while (r.hasNextField()) {
            auto field_name = r.readFieldName();
            if (field_name == "a") { fld_a = r.readInt32(); }
            else if (field_name == "b") { fld_b = r.readString(); }
            else if (field_name == "c") { fld_c = r.readFloat64(); }
            else if (field_name == "child") { auto opt = (r.isNull() ? (r.readNull(), std::optional<RecWide>{std::nullopt}) : std::optional<RecWide>{RecWideCodec.decode(r)}); fld_child = opt ? std::make_shared<RecWide>(*opt) : nullptr; }
            else { r.skip(); }
        }
        r.endObject();
        return RecWide{fld_a, fld_b, fld_c, fld_child};
    }
};

} // namespace all_types_recursive