// Generated by @specodec/typespec-emitter-cpp. DO NOT EDIT.
export module all_types_pairs;
import std;
import specodec;
import all_types;
using namespace all_types;

namespace all_types_pairs {

export struct PairString {
    std::string a_;
    std::string b_;
};

export inline void write_pair_string(specodec::SpecWriter& w, const PairString& obj) {
    w.beginObject(2);
    w.writeField("a"); w.writeString(obj.a_);;
    w.writeField("b"); w.writeString(obj.b_);;
    w.endObject();
}

export inline specodec::SpecCodec<PairString> PairStringCodec = {
    .encode = [](specodec::SpecWriter& w, const PairString& obj) { write_pair_string(w, obj); },
    .decode = [](specodec::SpecReader& r) -> PairString {
        std::string fld_a = "";
        std::string fld_b = "";
        r.beginObject();
        while (r.hasNextField()) {
            auto field_name = r.readFieldName();
            if (field_name == "a") { fld_a = r.readString(); }
            else if (field_name == "b") { fld_b = r.readString(); }
            else { r.skip(); }
        }
        r.endObject();
        return PairString{fld_a, fld_b};
    }
};

export struct PairBoolean {
    bool a_;
    bool b_;
};

export inline void write_pair_boolean(specodec::SpecWriter& w, const PairBoolean& obj) {
    w.beginObject(2);
    w.writeField("a"); w.writeBool(obj.a_);;
    w.writeField("b"); w.writeBool(obj.b_);;
    w.endObject();
}

export inline specodec::SpecCodec<PairBoolean> PairBooleanCodec = {
    .encode = [](specodec::SpecWriter& w, const PairBoolean& obj) { write_pair_boolean(w, obj); },
    .decode = [](specodec::SpecReader& r) -> PairBoolean {
        bool fld_a = false;
        bool fld_b = false;
        r.beginObject();
        while (r.hasNextField()) {
            auto field_name = r.readFieldName();
            if (field_name == "a") { fld_a = r.readBool(); }
            else if (field_name == "b") { fld_b = r.readBool(); }
            else { r.skip(); }
        }
        r.endObject();
        return PairBoolean{fld_a, fld_b};
    }
};

export struct PairInt8 {
    std::int8_t a_;
    std::int8_t b_;
};

export inline void write_pair_int8(specodec::SpecWriter& w, const PairInt8& obj) {
    w.beginObject(2);
    w.writeField("a"); w.writeInt32(static_cast<std::int32_t>(obj.a_));;
    w.writeField("b"); w.writeInt32(static_cast<std::int32_t>(obj.b_));;
    w.endObject();
}

export inline specodec::SpecCodec<PairInt8> PairInt8Codec = {
    .encode = [](specodec::SpecWriter& w, const PairInt8& obj) { write_pair_int8(w, obj); },
    .decode = [](specodec::SpecReader& r) -> PairInt8 {
        std::int8_t fld_a = 0;
        std::int8_t fld_b = 0;
        r.beginObject();
        while (r.hasNextField()) {
            auto field_name = r.readFieldName();
            if (field_name == "a") { fld_a = static_cast<std::int8_t>(r.readInt32()); }
            else if (field_name == "b") { fld_b = static_cast<std::int8_t>(r.readInt32()); }
            else { r.skip(); }
        }
        r.endObject();
        return PairInt8{fld_a, fld_b};
    }
};

export struct PairInt16 {
    std::int16_t a_;
    std::int16_t b_;
};

export inline void write_pair_int16(specodec::SpecWriter& w, const PairInt16& obj) {
    w.beginObject(2);
    w.writeField("a"); w.writeInt32(static_cast<std::int32_t>(obj.a_));;
    w.writeField("b"); w.writeInt32(static_cast<std::int32_t>(obj.b_));;
    w.endObject();
}

export inline specodec::SpecCodec<PairInt16> PairInt16Codec = {
    .encode = [](specodec::SpecWriter& w, const PairInt16& obj) { write_pair_int16(w, obj); },
    .decode = [](specodec::SpecReader& r) -> PairInt16 {
        std::int16_t fld_a = 0;
        std::int16_t fld_b = 0;
        r.beginObject();
        while (r.hasNextField()) {
            auto field_name = r.readFieldName();
            if (field_name == "a") { fld_a = static_cast<std::int16_t>(r.readInt32()); }
            else if (field_name == "b") { fld_b = static_cast<std::int16_t>(r.readInt32()); }
            else { r.skip(); }
        }
        r.endObject();
        return PairInt16{fld_a, fld_b};
    }
};

export struct PairInt32 {
    std::int32_t a_;
    std::int32_t b_;
};

export inline void write_pair_int32(specodec::SpecWriter& w, const PairInt32& obj) {
    w.beginObject(2);
    w.writeField("a"); w.writeInt32(obj.a_);;
    w.writeField("b"); w.writeInt32(obj.b_);;
    w.endObject();
}

export inline specodec::SpecCodec<PairInt32> PairInt32Codec = {
    .encode = [](specodec::SpecWriter& w, const PairInt32& obj) { write_pair_int32(w, obj); },
    .decode = [](specodec::SpecReader& r) -> PairInt32 {
        std::int32_t fld_a = 0;
        std::int32_t fld_b = 0;
        r.beginObject();
        while (r.hasNextField()) {
            auto field_name = r.readFieldName();
            if (field_name == "a") { fld_a = r.readInt32(); }
            else if (field_name == "b") { fld_b = r.readInt32(); }
            else { r.skip(); }
        }
        r.endObject();
        return PairInt32{fld_a, fld_b};
    }
};

export struct PairInt64 {
    std::int64_t a_;
    std::int64_t b_;
};

export inline void write_pair_int64(specodec::SpecWriter& w, const PairInt64& obj) {
    w.beginObject(2);
    w.writeField("a"); w.writeInt64(obj.a_);;
    w.writeField("b"); w.writeInt64(obj.b_);;
    w.endObject();
}

export inline specodec::SpecCodec<PairInt64> PairInt64Codec = {
    .encode = [](specodec::SpecWriter& w, const PairInt64& obj) { write_pair_int64(w, obj); },
    .decode = [](specodec::SpecReader& r) -> PairInt64 {
        std::int64_t fld_a = 0LL;
        std::int64_t fld_b = 0LL;
        r.beginObject();
        while (r.hasNextField()) {
            auto field_name = r.readFieldName();
            if (field_name == "a") { fld_a = r.readInt64(); }
            else if (field_name == "b") { fld_b = r.readInt64(); }
            else { r.skip(); }
        }
        r.endObject();
        return PairInt64{fld_a, fld_b};
    }
};

export struct PairUint8 {
    std::uint8_t a_;
    std::uint8_t b_;
};

export inline void write_pair_uint8(specodec::SpecWriter& w, const PairUint8& obj) {
    w.beginObject(2);
    w.writeField("a"); w.writeUint32(static_cast<std::uint32_t>(obj.a_));;
    w.writeField("b"); w.writeUint32(static_cast<std::uint32_t>(obj.b_));;
    w.endObject();
}

export inline specodec::SpecCodec<PairUint8> PairUint8Codec = {
    .encode = [](specodec::SpecWriter& w, const PairUint8& obj) { write_pair_uint8(w, obj); },
    .decode = [](specodec::SpecReader& r) -> PairUint8 {
        std::uint8_t fld_a = 0u;
        std::uint8_t fld_b = 0u;
        r.beginObject();
        while (r.hasNextField()) {
            auto field_name = r.readFieldName();
            if (field_name == "a") { fld_a = static_cast<std::uint8_t>(r.readUint32()); }
            else if (field_name == "b") { fld_b = static_cast<std::uint8_t>(r.readUint32()); }
            else { r.skip(); }
        }
        r.endObject();
        return PairUint8{fld_a, fld_b};
    }
};

export struct PairUint16 {
    std::uint16_t a_;
    std::uint16_t b_;
};

export inline void write_pair_uint16(specodec::SpecWriter& w, const PairUint16& obj) {
    w.beginObject(2);
    w.writeField("a"); w.writeUint32(static_cast<std::uint32_t>(obj.a_));;
    w.writeField("b"); w.writeUint32(static_cast<std::uint32_t>(obj.b_));;
    w.endObject();
}

export inline specodec::SpecCodec<PairUint16> PairUint16Codec = {
    .encode = [](specodec::SpecWriter& w, const PairUint16& obj) { write_pair_uint16(w, obj); },
    .decode = [](specodec::SpecReader& r) -> PairUint16 {
        std::uint16_t fld_a = 0u;
        std::uint16_t fld_b = 0u;
        r.beginObject();
        while (r.hasNextField()) {
            auto field_name = r.readFieldName();
            if (field_name == "a") { fld_a = static_cast<std::uint16_t>(r.readUint32()); }
            else if (field_name == "b") { fld_b = static_cast<std::uint16_t>(r.readUint32()); }
            else { r.skip(); }
        }
        r.endObject();
        return PairUint16{fld_a, fld_b};
    }
};

export struct PairUint32 {
    std::uint32_t a_;
    std::uint32_t b_;
};

export inline void write_pair_uint32(specodec::SpecWriter& w, const PairUint32& obj) {
    w.beginObject(2);
    w.writeField("a"); w.writeUint32(obj.a_);;
    w.writeField("b"); w.writeUint32(obj.b_);;
    w.endObject();
}

export inline specodec::SpecCodec<PairUint32> PairUint32Codec = {
    .encode = [](specodec::SpecWriter& w, const PairUint32& obj) { write_pair_uint32(w, obj); },
    .decode = [](specodec::SpecReader& r) -> PairUint32 {
        std::uint32_t fld_a = 0u;
        std::uint32_t fld_b = 0u;
        r.beginObject();
        while (r.hasNextField()) {
            auto field_name = r.readFieldName();
            if (field_name == "a") { fld_a = r.readUint32(); }
            else if (field_name == "b") { fld_b = r.readUint32(); }
            else { r.skip(); }
        }
        r.endObject();
        return PairUint32{fld_a, fld_b};
    }
};

export struct PairUint64 {
    std::uint64_t a_;
    std::uint64_t b_;
};

export inline void write_pair_uint64(specodec::SpecWriter& w, const PairUint64& obj) {
    w.beginObject(2);
    w.writeField("a"); w.writeUint64(obj.a_);;
    w.writeField("b"); w.writeUint64(obj.b_);;
    w.endObject();
}

export inline specodec::SpecCodec<PairUint64> PairUint64Codec = {
    .encode = [](specodec::SpecWriter& w, const PairUint64& obj) { write_pair_uint64(w, obj); },
    .decode = [](specodec::SpecReader& r) -> PairUint64 {
        std::uint64_t fld_a = 0ULL;
        std::uint64_t fld_b = 0ULL;
        r.beginObject();
        while (r.hasNextField()) {
            auto field_name = r.readFieldName();
            if (field_name == "a") { fld_a = r.readUint64(); }
            else if (field_name == "b") { fld_b = r.readUint64(); }
            else { r.skip(); }
        }
        r.endObject();
        return PairUint64{fld_a, fld_b};
    }
};

export struct PairFloat32 {
    float a_;
    float b_;
};

export inline void write_pair_float32(specodec::SpecWriter& w, const PairFloat32& obj) {
    w.beginObject(2);
    w.writeField("a"); w.writeFloat32(obj.a_);;
    w.writeField("b"); w.writeFloat32(obj.b_);;
    w.endObject();
}

export inline specodec::SpecCodec<PairFloat32> PairFloat32Codec = {
    .encode = [](specodec::SpecWriter& w, const PairFloat32& obj) { write_pair_float32(w, obj); },
    .decode = [](specodec::SpecReader& r) -> PairFloat32 {
        float fld_a = 0.0f;
        float fld_b = 0.0f;
        r.beginObject();
        while (r.hasNextField()) {
            auto field_name = r.readFieldName();
            if (field_name == "a") { fld_a = r.readFloat32(); }
            else if (field_name == "b") { fld_b = r.readFloat32(); }
            else { r.skip(); }
        }
        r.endObject();
        return PairFloat32{fld_a, fld_b};
    }
};

export struct PairFloat64 {
    double a_;
    double b_;
};

export inline void write_pair_float64(specodec::SpecWriter& w, const PairFloat64& obj) {
    w.beginObject(2);
    w.writeField("a"); w.writeFloat64(obj.a_);;
    w.writeField("b"); w.writeFloat64(obj.b_);;
    w.endObject();
}

export inline specodec::SpecCodec<PairFloat64> PairFloat64Codec = {
    .encode = [](specodec::SpecWriter& w, const PairFloat64& obj) { write_pair_float64(w, obj); },
    .decode = [](specodec::SpecReader& r) -> PairFloat64 {
        double fld_a = 0.0;
        double fld_b = 0.0;
        r.beginObject();
        while (r.hasNextField()) {
            auto field_name = r.readFieldName();
            if (field_name == "a") { fld_a = r.readFloat64(); }
            else if (field_name == "b") { fld_b = r.readFloat64(); }
            else { r.skip(); }
        }
        r.endObject();
        return PairFloat64{fld_a, fld_b};
    }
};

export struct PairBytes {
    std::vector<std::uint8_t> a_;
    std::vector<std::uint8_t> b_;
};

export inline void write_pair_bytes(specodec::SpecWriter& w, const PairBytes& obj) {
    w.beginObject(2);
    w.writeField("a"); w.writeBytes(obj.a_);;
    w.writeField("b"); w.writeBytes(obj.b_);;
    w.endObject();
}

export inline specodec::SpecCodec<PairBytes> PairBytesCodec = {
    .encode = [](specodec::SpecWriter& w, const PairBytes& obj) { write_pair_bytes(w, obj); },
    .decode = [](specodec::SpecReader& r) -> PairBytes {
        std::vector<std::uint8_t> fld_a = {};
        std::vector<std::uint8_t> fld_b = {};
        r.beginObject();
        while (r.hasNextField()) {
            auto field_name = r.readFieldName();
            if (field_name == "a") { fld_a = r.readBytes(); }
            else if (field_name == "b") { fld_b = r.readBytes(); }
            else { r.skip(); }
        }
        r.endObject();
        return PairBytes{fld_a, fld_b};
    }
};

export struct DualStringInt32 {
    std::string a_;
    std::int32_t b_;
};

export inline void write_dual_string_int32(specodec::SpecWriter& w, const DualStringInt32& obj) {
    w.beginObject(2);
    w.writeField("a"); w.writeString(obj.a_);;
    w.writeField("b"); w.writeInt32(obj.b_);;
    w.endObject();
}

export inline specodec::SpecCodec<DualStringInt32> DualStringInt32Codec = {
    .encode = [](specodec::SpecWriter& w, const DualStringInt32& obj) { write_dual_string_int32(w, obj); },
    .decode = [](specodec::SpecReader& r) -> DualStringInt32 {
        std::string fld_a = "";
        std::int32_t fld_b = 0;
        r.beginObject();
        while (r.hasNextField()) {
            auto field_name = r.readFieldName();
            if (field_name == "a") { fld_a = r.readString(); }
            else if (field_name == "b") { fld_b = r.readInt32(); }
            else { r.skip(); }
        }
        r.endObject();
        return DualStringInt32{fld_a, fld_b};
    }
};

export struct DualStringBoolean {
    std::string a_;
    bool b_;
};

export inline void write_dual_string_boolean(specodec::SpecWriter& w, const DualStringBoolean& obj) {
    w.beginObject(2);
    w.writeField("a"); w.writeString(obj.a_);;
    w.writeField("b"); w.writeBool(obj.b_);;
    w.endObject();
}

export inline specodec::SpecCodec<DualStringBoolean> DualStringBooleanCodec = {
    .encode = [](specodec::SpecWriter& w, const DualStringBoolean& obj) { write_dual_string_boolean(w, obj); },
    .decode = [](specodec::SpecReader& r) -> DualStringBoolean {
        std::string fld_a = "";
        bool fld_b = false;
        r.beginObject();
        while (r.hasNextField()) {
            auto field_name = r.readFieldName();
            if (field_name == "a") { fld_a = r.readString(); }
            else if (field_name == "b") { fld_b = r.readBool(); }
            else { r.skip(); }
        }
        r.endObject();
        return DualStringBoolean{fld_a, fld_b};
    }
};

export struct DualStringFloat64 {
    std::string a_;
    double b_;
};

export inline void write_dual_string_float64(specodec::SpecWriter& w, const DualStringFloat64& obj) {
    w.beginObject(2);
    w.writeField("a"); w.writeString(obj.a_);;
    w.writeField("b"); w.writeFloat64(obj.b_);;
    w.endObject();
}

export inline specodec::SpecCodec<DualStringFloat64> DualStringFloat64Codec = {
    .encode = [](specodec::SpecWriter& w, const DualStringFloat64& obj) { write_dual_string_float64(w, obj); },
    .decode = [](specodec::SpecReader& r) -> DualStringFloat64 {
        std::string fld_a = "";
        double fld_b = 0.0;
        r.beginObject();
        while (r.hasNextField()) {
            auto field_name = r.readFieldName();
            if (field_name == "a") { fld_a = r.readString(); }
            else if (field_name == "b") { fld_b = r.readFloat64(); }
            else { r.skip(); }
        }
        r.endObject();
        return DualStringFloat64{fld_a, fld_b};
    }
};

export struct DualStringBytes {
    std::string a_;
    std::vector<std::uint8_t> b_;
};

export inline void write_dual_string_bytes(specodec::SpecWriter& w, const DualStringBytes& obj) {
    w.beginObject(2);
    w.writeField("a"); w.writeString(obj.a_);;
    w.writeField("b"); w.writeBytes(obj.b_);;
    w.endObject();
}

export inline specodec::SpecCodec<DualStringBytes> DualStringBytesCodec = {
    .encode = [](specodec::SpecWriter& w, const DualStringBytes& obj) { write_dual_string_bytes(w, obj); },
    .decode = [](specodec::SpecReader& r) -> DualStringBytes {
        std::string fld_a = "";
        std::vector<std::uint8_t> fld_b = {};
        r.beginObject();
        while (r.hasNextField()) {
            auto field_name = r.readFieldName();
            if (field_name == "a") { fld_a = r.readString(); }
            else if (field_name == "b") { fld_b = r.readBytes(); }
            else { r.skip(); }
        }
        r.endObject();
        return DualStringBytes{fld_a, fld_b};
    }
};

export struct DualInt32Boolean {
    std::int32_t a_;
    bool b_;
};

export inline void write_dual_int32_boolean(specodec::SpecWriter& w, const DualInt32Boolean& obj) {
    w.beginObject(2);
    w.writeField("a"); w.writeInt32(obj.a_);;
    w.writeField("b"); w.writeBool(obj.b_);;
    w.endObject();
}

export inline specodec::SpecCodec<DualInt32Boolean> DualInt32BooleanCodec = {
    .encode = [](specodec::SpecWriter& w, const DualInt32Boolean& obj) { write_dual_int32_boolean(w, obj); },
    .decode = [](specodec::SpecReader& r) -> DualInt32Boolean {
        std::int32_t fld_a = 0;
        bool fld_b = false;
        r.beginObject();
        while (r.hasNextField()) {
            auto field_name = r.readFieldName();
            if (field_name == "a") { fld_a = r.readInt32(); }
            else if (field_name == "b") { fld_b = r.readBool(); }
            else { r.skip(); }
        }
        r.endObject();
        return DualInt32Boolean{fld_a, fld_b};
    }
};

export struct DualInt32Float64 {
    std::int32_t a_;
    double b_;
};

export inline void write_dual_int32_float64(specodec::SpecWriter& w, const DualInt32Float64& obj) {
    w.beginObject(2);
    w.writeField("a"); w.writeInt32(obj.a_);;
    w.writeField("b"); w.writeFloat64(obj.b_);;
    w.endObject();
}

export inline specodec::SpecCodec<DualInt32Float64> DualInt32Float64Codec = {
    .encode = [](specodec::SpecWriter& w, const DualInt32Float64& obj) { write_dual_int32_float64(w, obj); },
    .decode = [](specodec::SpecReader& r) -> DualInt32Float64 {
        std::int32_t fld_a = 0;
        double fld_b = 0.0;
        r.beginObject();
        while (r.hasNextField()) {
            auto field_name = r.readFieldName();
            if (field_name == "a") { fld_a = r.readInt32(); }
            else if (field_name == "b") { fld_b = r.readFloat64(); }
            else { r.skip(); }
        }
        r.endObject();
        return DualInt32Float64{fld_a, fld_b};
    }
};

export struct DualInt32Int64 {
    std::int32_t a_;
    std::int64_t b_;
};

export inline void write_dual_int32_int64(specodec::SpecWriter& w, const DualInt32Int64& obj) {
    w.beginObject(2);
    w.writeField("a"); w.writeInt32(obj.a_);;
    w.writeField("b"); w.writeInt64(obj.b_);;
    w.endObject();
}

export inline specodec::SpecCodec<DualInt32Int64> DualInt32Int64Codec = {
    .encode = [](specodec::SpecWriter& w, const DualInt32Int64& obj) { write_dual_int32_int64(w, obj); },
    .decode = [](specodec::SpecReader& r) -> DualInt32Int64 {
        std::int32_t fld_a = 0;
        std::int64_t fld_b = 0LL;
        r.beginObject();
        while (r.hasNextField()) {
            auto field_name = r.readFieldName();
            if (field_name == "a") { fld_a = r.readInt32(); }
            else if (field_name == "b") { fld_b = r.readInt64(); }
            else { r.skip(); }
        }
        r.endObject();
        return DualInt32Int64{fld_a, fld_b};
    }
};

export struct DualInt32Uint32 {
    std::int32_t a_;
    std::uint32_t b_;
};

export inline void write_dual_int32_uint32(specodec::SpecWriter& w, const DualInt32Uint32& obj) {
    w.beginObject(2);
    w.writeField("a"); w.writeInt32(obj.a_);;
    w.writeField("b"); w.writeUint32(obj.b_);;
    w.endObject();
}

export inline specodec::SpecCodec<DualInt32Uint32> DualInt32Uint32Codec = {
    .encode = [](specodec::SpecWriter& w, const DualInt32Uint32& obj) { write_dual_int32_uint32(w, obj); },
    .decode = [](specodec::SpecReader& r) -> DualInt32Uint32 {
        std::int32_t fld_a = 0;
        std::uint32_t fld_b = 0u;
        r.beginObject();
        while (r.hasNextField()) {
            auto field_name = r.readFieldName();
            if (field_name == "a") { fld_a = r.readInt32(); }
            else if (field_name == "b") { fld_b = r.readUint32(); }
            else { r.skip(); }
        }
        r.endObject();
        return DualInt32Uint32{fld_a, fld_b};
    }
};

export struct DualInt64Uint64 {
    std::int64_t a_;
    std::uint64_t b_;
};

export inline void write_dual_int64_uint64(specodec::SpecWriter& w, const DualInt64Uint64& obj) {
    w.beginObject(2);
    w.writeField("a"); w.writeInt64(obj.a_);;
    w.writeField("b"); w.writeUint64(obj.b_);;
    w.endObject();
}

export inline specodec::SpecCodec<DualInt64Uint64> DualInt64Uint64Codec = {
    .encode = [](specodec::SpecWriter& w, const DualInt64Uint64& obj) { write_dual_int64_uint64(w, obj); },
    .decode = [](specodec::SpecReader& r) -> DualInt64Uint64 {
        std::int64_t fld_a = 0LL;
        std::uint64_t fld_b = 0ULL;
        r.beginObject();
        while (r.hasNextField()) {
            auto field_name = r.readFieldName();
            if (field_name == "a") { fld_a = r.readInt64(); }
            else if (field_name == "b") { fld_b = r.readUint64(); }
            else { r.skip(); }
        }
        r.endObject();
        return DualInt64Uint64{fld_a, fld_b};
    }
};

export struct DualFloat32Float64 {
    float a_;
    double b_;
};

export inline void write_dual_float32_float64(specodec::SpecWriter& w, const DualFloat32Float64& obj) {
    w.beginObject(2);
    w.writeField("a"); w.writeFloat32(obj.a_);;
    w.writeField("b"); w.writeFloat64(obj.b_);;
    w.endObject();
}

export inline specodec::SpecCodec<DualFloat32Float64> DualFloat32Float64Codec = {
    .encode = [](specodec::SpecWriter& w, const DualFloat32Float64& obj) { write_dual_float32_float64(w, obj); },
    .decode = [](specodec::SpecReader& r) -> DualFloat32Float64 {
        float fld_a = 0.0f;
        double fld_b = 0.0;
        r.beginObject();
        while (r.hasNextField()) {
            auto field_name = r.readFieldName();
            if (field_name == "a") { fld_a = r.readFloat32(); }
            else if (field_name == "b") { fld_b = r.readFloat64(); }
            else { r.skip(); }
        }
        r.endObject();
        return DualFloat32Float64{fld_a, fld_b};
    }
};

export struct DualFloat64Boolean {
    double a_;
    bool b_;
};

export inline void write_dual_float64_boolean(specodec::SpecWriter& w, const DualFloat64Boolean& obj) {
    w.beginObject(2);
    w.writeField("a"); w.writeFloat64(obj.a_);;
    w.writeField("b"); w.writeBool(obj.b_);;
    w.endObject();
}

export inline specodec::SpecCodec<DualFloat64Boolean> DualFloat64BooleanCodec = {
    .encode = [](specodec::SpecWriter& w, const DualFloat64Boolean& obj) { write_dual_float64_boolean(w, obj); },
    .decode = [](specodec::SpecReader& r) -> DualFloat64Boolean {
        double fld_a = 0.0;
        bool fld_b = false;
        r.beginObject();
        while (r.hasNextField()) {
            auto field_name = r.readFieldName();
            if (field_name == "a") { fld_a = r.readFloat64(); }
            else if (field_name == "b") { fld_b = r.readBool(); }
            else { r.skip(); }
        }
        r.endObject();
        return DualFloat64Boolean{fld_a, fld_b};
    }
};

export struct DualFloat64Bytes {
    double a_;
    std::vector<std::uint8_t> b_;
};

export inline void write_dual_float64_bytes(specodec::SpecWriter& w, const DualFloat64Bytes& obj) {
    w.beginObject(2);
    w.writeField("a"); w.writeFloat64(obj.a_);;
    w.writeField("b"); w.writeBytes(obj.b_);;
    w.endObject();
}

export inline specodec::SpecCodec<DualFloat64Bytes> DualFloat64BytesCodec = {
    .encode = [](specodec::SpecWriter& w, const DualFloat64Bytes& obj) { write_dual_float64_bytes(w, obj); },
    .decode = [](specodec::SpecReader& r) -> DualFloat64Bytes {
        double fld_a = 0.0;
        std::vector<std::uint8_t> fld_b = {};
        r.beginObject();
        while (r.hasNextField()) {
            auto field_name = r.readFieldName();
            if (field_name == "a") { fld_a = r.readFloat64(); }
            else if (field_name == "b") { fld_b = r.readBytes(); }
            else { r.skip(); }
        }
        r.endObject();
        return DualFloat64Bytes{fld_a, fld_b};
    }
};

export struct DualUint32Uint64 {
    std::uint32_t a_;
    std::uint64_t b_;
};

export inline void write_dual_uint32_uint64(specodec::SpecWriter& w, const DualUint32Uint64& obj) {
    w.beginObject(2);
    w.writeField("a"); w.writeUint32(obj.a_);;
    w.writeField("b"); w.writeUint64(obj.b_);;
    w.endObject();
}

export inline specodec::SpecCodec<DualUint32Uint64> DualUint32Uint64Codec = {
    .encode = [](specodec::SpecWriter& w, const DualUint32Uint64& obj) { write_dual_uint32_uint64(w, obj); },
    .decode = [](specodec::SpecReader& r) -> DualUint32Uint64 {
        std::uint32_t fld_a = 0u;
        std::uint64_t fld_b = 0ULL;
        r.beginObject();
        while (r.hasNextField()) {
            auto field_name = r.readFieldName();
            if (field_name == "a") { fld_a = r.readUint32(); }
            else if (field_name == "b") { fld_b = r.readUint64(); }
            else { r.skip(); }
        }
        r.endObject();
        return DualUint32Uint64{fld_a, fld_b};
    }
};

export struct DualBooleanBytes {
    bool a_;
    std::vector<std::uint8_t> b_;
};

export inline void write_dual_boolean_bytes(specodec::SpecWriter& w, const DualBooleanBytes& obj) {
    w.beginObject(2);
    w.writeField("a"); w.writeBool(obj.a_);;
    w.writeField("b"); w.writeBytes(obj.b_);;
    w.endObject();
}

export inline specodec::SpecCodec<DualBooleanBytes> DualBooleanBytesCodec = {
    .encode = [](specodec::SpecWriter& w, const DualBooleanBytes& obj) { write_dual_boolean_bytes(w, obj); },
    .decode = [](specodec::SpecReader& r) -> DualBooleanBytes {
        bool fld_a = false;
        std::vector<std::uint8_t> fld_b = {};
        r.beginObject();
        while (r.hasNextField()) {
            auto field_name = r.readFieldName();
            if (field_name == "a") { fld_a = r.readBool(); }
            else if (field_name == "b") { fld_b = r.readBytes(); }
            else { r.skip(); }
        }
        r.endObject();
        return DualBooleanBytes{fld_a, fld_b};
    }
};

export struct DualInt8Uint8 {
    std::int8_t a_;
    std::uint8_t b_;
};

export inline void write_dual_int8_uint8(specodec::SpecWriter& w, const DualInt8Uint8& obj) {
    w.beginObject(2);
    w.writeField("a"); w.writeInt32(static_cast<std::int32_t>(obj.a_));;
    w.writeField("b"); w.writeUint32(static_cast<std::uint32_t>(obj.b_));;
    w.endObject();
}

export inline specodec::SpecCodec<DualInt8Uint8> DualInt8Uint8Codec = {
    .encode = [](specodec::SpecWriter& w, const DualInt8Uint8& obj) { write_dual_int8_uint8(w, obj); },
    .decode = [](specodec::SpecReader& r) -> DualInt8Uint8 {
        std::int8_t fld_a = 0;
        std::uint8_t fld_b = 0u;
        r.beginObject();
        while (r.hasNextField()) {
            auto field_name = r.readFieldName();
            if (field_name == "a") { fld_a = static_cast<std::int8_t>(r.readInt32()); }
            else if (field_name == "b") { fld_b = static_cast<std::uint8_t>(r.readUint32()); }
            else { r.skip(); }
        }
        r.endObject();
        return DualInt8Uint8{fld_a, fld_b};
    }
};

export struct DualInt16Uint16 {
    std::int16_t a_;
    std::uint16_t b_;
};

export inline void write_dual_int16_uint16(specodec::SpecWriter& w, const DualInt16Uint16& obj) {
    w.beginObject(2);
    w.writeField("a"); w.writeInt32(static_cast<std::int32_t>(obj.a_));;
    w.writeField("b"); w.writeUint32(static_cast<std::uint32_t>(obj.b_));;
    w.endObject();
}

export inline specodec::SpecCodec<DualInt16Uint16> DualInt16Uint16Codec = {
    .encode = [](specodec::SpecWriter& w, const DualInt16Uint16& obj) { write_dual_int16_uint16(w, obj); },
    .decode = [](specodec::SpecReader& r) -> DualInt16Uint16 {
        std::int16_t fld_a = 0;
        std::uint16_t fld_b = 0u;
        r.beginObject();
        while (r.hasNextField()) {
            auto field_name = r.readFieldName();
            if (field_name == "a") { fld_a = static_cast<std::int16_t>(r.readInt32()); }
            else if (field_name == "b") { fld_b = static_cast<std::uint16_t>(r.readUint32()); }
            else { r.skip(); }
        }
        r.endObject();
        return DualInt16Uint16{fld_a, fld_b};
    }
};

export struct DualStringInt64 {
    std::string a_;
    std::int64_t b_;
};

export inline void write_dual_string_int64(specodec::SpecWriter& w, const DualStringInt64& obj) {
    w.beginObject(2);
    w.writeField("a"); w.writeString(obj.a_);;
    w.writeField("b"); w.writeInt64(obj.b_);;
    w.endObject();
}

export inline specodec::SpecCodec<DualStringInt64> DualStringInt64Codec = {
    .encode = [](specodec::SpecWriter& w, const DualStringInt64& obj) { write_dual_string_int64(w, obj); },
    .decode = [](specodec::SpecReader& r) -> DualStringInt64 {
        std::string fld_a = "";
        std::int64_t fld_b = 0LL;
        r.beginObject();
        while (r.hasNextField()) {
            auto field_name = r.readFieldName();
            if (field_name == "a") { fld_a = r.readString(); }
            else if (field_name == "b") { fld_b = r.readInt64(); }
            else { r.skip(); }
        }
        r.endObject();
        return DualStringInt64{fld_a, fld_b};
    }
};

export struct DualStringUint64 {
    std::string a_;
    std::uint64_t b_;
};

export inline void write_dual_string_uint64(specodec::SpecWriter& w, const DualStringUint64& obj) {
    w.beginObject(2);
    w.writeField("a"); w.writeString(obj.a_);;
    w.writeField("b"); w.writeUint64(obj.b_);;
    w.endObject();
}

export inline specodec::SpecCodec<DualStringUint64> DualStringUint64Codec = {
    .encode = [](specodec::SpecWriter& w, const DualStringUint64& obj) { write_dual_string_uint64(w, obj); },
    .decode = [](specodec::SpecReader& r) -> DualStringUint64 {
        std::string fld_a = "";
        std::uint64_t fld_b = 0ULL;
        r.beginObject();
        while (r.hasNextField()) {
            auto field_name = r.readFieldName();
            if (field_name == "a") { fld_a = r.readString(); }
            else if (field_name == "b") { fld_b = r.readUint64(); }
            else { r.skip(); }
        }
        r.endObject();
        return DualStringUint64{fld_a, fld_b};
    }
};

export struct DualInt32Bytes {
    std::int32_t a_;
    std::vector<std::uint8_t> b_;
};

export inline void write_dual_int32_bytes(specodec::SpecWriter& w, const DualInt32Bytes& obj) {
    w.beginObject(2);
    w.writeField("a"); w.writeInt32(obj.a_);;
    w.writeField("b"); w.writeBytes(obj.b_);;
    w.endObject();
}

export inline specodec::SpecCodec<DualInt32Bytes> DualInt32BytesCodec = {
    .encode = [](specodec::SpecWriter& w, const DualInt32Bytes& obj) { write_dual_int32_bytes(w, obj); },
    .decode = [](specodec::SpecReader& r) -> DualInt32Bytes {
        std::int32_t fld_a = 0;
        std::vector<std::uint8_t> fld_b = {};
        r.beginObject();
        while (r.hasNextField()) {
            auto field_name = r.readFieldName();
            if (field_name == "a") { fld_a = r.readInt32(); }
            else if (field_name == "b") { fld_b = r.readBytes(); }
            else { r.skip(); }
        }
        r.endObject();
        return DualInt32Bytes{fld_a, fld_b};
    }
};

export struct DualFloat64Int32 {
    double a_;
    std::int32_t b_;
};

export inline void write_dual_float64_int32(specodec::SpecWriter& w, const DualFloat64Int32& obj) {
    w.beginObject(2);
    w.writeField("a"); w.writeFloat64(obj.a_);;
    w.writeField("b"); w.writeInt32(obj.b_);;
    w.endObject();
}

export inline specodec::SpecCodec<DualFloat64Int32> DualFloat64Int32Codec = {
    .encode = [](specodec::SpecWriter& w, const DualFloat64Int32& obj) { write_dual_float64_int32(w, obj); },
    .decode = [](specodec::SpecReader& r) -> DualFloat64Int32 {
        double fld_a = 0.0;
        std::int32_t fld_b = 0;
        r.beginObject();
        while (r.hasNextField()) {
            auto field_name = r.readFieldName();
            if (field_name == "a") { fld_a = r.readFloat64(); }
            else if (field_name == "b") { fld_b = r.readInt32(); }
            else { r.skip(); }
        }
        r.endObject();
        return DualFloat64Int32{fld_a, fld_b};
    }
};

export struct DualBooleanInt32 {
    bool a_;
    std::int32_t b_;
};

export inline void write_dual_boolean_int32(specodec::SpecWriter& w, const DualBooleanInt32& obj) {
    w.beginObject(2);
    w.writeField("a"); w.writeBool(obj.a_);;
    w.writeField("b"); w.writeInt32(obj.b_);;
    w.endObject();
}

export inline specodec::SpecCodec<DualBooleanInt32> DualBooleanInt32Codec = {
    .encode = [](specodec::SpecWriter& w, const DualBooleanInt32& obj) { write_dual_boolean_int32(w, obj); },
    .decode = [](specodec::SpecReader& r) -> DualBooleanInt32 {
        bool fld_a = false;
        std::int32_t fld_b = 0;
        r.beginObject();
        while (r.hasNextField()) {
            auto field_name = r.readFieldName();
            if (field_name == "a") { fld_a = r.readBool(); }
            else if (field_name == "b") { fld_b = r.readInt32(); }
            else { r.skip(); }
        }
        r.endObject();
        return DualBooleanInt32{fld_a, fld_b};
    }
};

export struct DualBytesInt64 {
    std::vector<std::uint8_t> a_;
    std::int64_t b_;
};

export inline void write_dual_bytes_int64(specodec::SpecWriter& w, const DualBytesInt64& obj) {
    w.beginObject(2);
    w.writeField("a"); w.writeBytes(obj.a_);;
    w.writeField("b"); w.writeInt64(obj.b_);;
    w.endObject();
}

export inline specodec::SpecCodec<DualBytesInt64> DualBytesInt64Codec = {
    .encode = [](specodec::SpecWriter& w, const DualBytesInt64& obj) { write_dual_bytes_int64(w, obj); },
    .decode = [](specodec::SpecReader& r) -> DualBytesInt64 {
        std::vector<std::uint8_t> fld_a = {};
        std::int64_t fld_b = 0LL;
        r.beginObject();
        while (r.hasNextField()) {
            auto field_name = r.readFieldName();
            if (field_name == "a") { fld_a = r.readBytes(); }
            else if (field_name == "b") { fld_b = r.readInt64(); }
            else { r.skip(); }
        }
        r.endObject();
        return DualBytesInt64{fld_a, fld_b};
    }
};

export struct DualInt8Float32 {
    std::int8_t a_;
    float b_;
};

export inline void write_dual_int8_float32(specodec::SpecWriter& w, const DualInt8Float32& obj) {
    w.beginObject(2);
    w.writeField("a"); w.writeInt32(static_cast<std::int32_t>(obj.a_));;
    w.writeField("b"); w.writeFloat32(obj.b_);;
    w.endObject();
}

export inline specodec::SpecCodec<DualInt8Float32> DualInt8Float32Codec = {
    .encode = [](specodec::SpecWriter& w, const DualInt8Float32& obj) { write_dual_int8_float32(w, obj); },
    .decode = [](specodec::SpecReader& r) -> DualInt8Float32 {
        std::int8_t fld_a = 0;
        float fld_b = 0.0f;
        r.beginObject();
        while (r.hasNextField()) {
            auto field_name = r.readFieldName();
            if (field_name == "a") { fld_a = static_cast<std::int8_t>(r.readInt32()); }
            else if (field_name == "b") { fld_b = r.readFloat32(); }
            else { r.skip(); }
        }
        r.endObject();
        return DualInt8Float32{fld_a, fld_b};
    }
};

export struct DualUint8Int16 {
    std::uint8_t a_;
    std::int16_t b_;
};

export inline void write_dual_uint8_int16(specodec::SpecWriter& w, const DualUint8Int16& obj) {
    w.beginObject(2);
    w.writeField("a"); w.writeUint32(static_cast<std::uint32_t>(obj.a_));;
    w.writeField("b"); w.writeInt32(static_cast<std::int32_t>(obj.b_));;
    w.endObject();
}

export inline specodec::SpecCodec<DualUint8Int16> DualUint8Int16Codec = {
    .encode = [](specodec::SpecWriter& w, const DualUint8Int16& obj) { write_dual_uint8_int16(w, obj); },
    .decode = [](specodec::SpecReader& r) -> DualUint8Int16 {
        std::uint8_t fld_a = 0u;
        std::int16_t fld_b = 0;
        r.beginObject();
        while (r.hasNextField()) {
            auto field_name = r.readFieldName();
            if (field_name == "a") { fld_a = static_cast<std::uint8_t>(r.readUint32()); }
            else if (field_name == "b") { fld_b = static_cast<std::int16_t>(r.readInt32()); }
            else { r.skip(); }
        }
        r.endObject();
        return DualUint8Int16{fld_a, fld_b};
    }
};

export struct DualInt64Float64 {
    std::int64_t a_;
    double b_;
};

export inline void write_dual_int64_float64(specodec::SpecWriter& w, const DualInt64Float64& obj) {
    w.beginObject(2);
    w.writeField("a"); w.writeInt64(obj.a_);;
    w.writeField("b"); w.writeFloat64(obj.b_);;
    w.endObject();
}

export inline specodec::SpecCodec<DualInt64Float64> DualInt64Float64Codec = {
    .encode = [](specodec::SpecWriter& w, const DualInt64Float64& obj) { write_dual_int64_float64(w, obj); },
    .decode = [](specodec::SpecReader& r) -> DualInt64Float64 {
        std::int64_t fld_a = 0LL;
        double fld_b = 0.0;
        r.beginObject();
        while (r.hasNextField()) {
            auto field_name = r.readFieldName();
            if (field_name == "a") { fld_a = r.readInt64(); }
            else if (field_name == "b") { fld_b = r.readFloat64(); }
            else { r.skip(); }
        }
        r.endObject();
        return DualInt64Float64{fld_a, fld_b};
    }
};

export struct DualUint64String {
    std::uint64_t a_;
    std::string b_;
};

export inline void write_dual_uint64_string(specodec::SpecWriter& w, const DualUint64String& obj) {
    w.beginObject(2);
    w.writeField("a"); w.writeUint64(obj.a_);;
    w.writeField("b"); w.writeString(obj.b_);;
    w.endObject();
}

export inline specodec::SpecCodec<DualUint64String> DualUint64StringCodec = {
    .encode = [](specodec::SpecWriter& w, const DualUint64String& obj) { write_dual_uint64_string(w, obj); },
    .decode = [](specodec::SpecReader& r) -> DualUint64String {
        std::uint64_t fld_a = 0ULL;
        std::string fld_b = "";
        r.beginObject();
        while (r.hasNextField()) {
            auto field_name = r.readFieldName();
            if (field_name == "a") { fld_a = r.readUint64(); }
            else if (field_name == "b") { fld_b = r.readString(); }
            else { r.skip(); }
        }
        r.endObject();
        return DualUint64String{fld_a, fld_b};
    }
};

export struct Triple01 {
    std::string a_;
    std::int32_t b_;
    bool c_;
};

export inline void write_triple01(specodec::SpecWriter& w, const Triple01& obj) {
    w.beginObject(3);
    w.writeField("a"); w.writeString(obj.a_);;
    w.writeField("b"); w.writeInt32(obj.b_);;
    w.writeField("c"); w.writeBool(obj.c_);;
    w.endObject();
}

export inline specodec::SpecCodec<Triple01> Triple01Codec = {
    .encode = [](specodec::SpecWriter& w, const Triple01& obj) { write_triple01(w, obj); },
    .decode = [](specodec::SpecReader& r) -> Triple01 {
        std::string fld_a = "";
        std::int32_t fld_b = 0;
        bool fld_c = false;
        r.beginObject();
        while (r.hasNextField()) {
            auto field_name = r.readFieldName();
            if (field_name == "a") { fld_a = r.readString(); }
            else if (field_name == "b") { fld_b = r.readInt32(); }
            else if (field_name == "c") { fld_c = r.readBool(); }
            else { r.skip(); }
        }
        r.endObject();
        return Triple01{fld_a, fld_b, fld_c};
    }
};

export struct Triple02 {
    double a_;
    double b_;
    double c_;
};

export inline void write_triple02(specodec::SpecWriter& w, const Triple02& obj) {
    w.beginObject(3);
    w.writeField("a"); w.writeFloat64(obj.a_);;
    w.writeField("b"); w.writeFloat64(obj.b_);;
    w.writeField("c"); w.writeFloat64(obj.c_);;
    w.endObject();
}

export inline specodec::SpecCodec<Triple02> Triple02Codec = {
    .encode = [](specodec::SpecWriter& w, const Triple02& obj) { write_triple02(w, obj); },
    .decode = [](specodec::SpecReader& r) -> Triple02 {
        double fld_a = 0.0;
        double fld_b = 0.0;
        double fld_c = 0.0;
        r.beginObject();
        while (r.hasNextField()) {
            auto field_name = r.readFieldName();
            if (field_name == "a") { fld_a = r.readFloat64(); }
            else if (field_name == "b") { fld_b = r.readFloat64(); }
            else if (field_name == "c") { fld_c = r.readFloat64(); }
            else { r.skip(); }
        }
        r.endObject();
        return Triple02{fld_a, fld_b, fld_c};
    }
};

export struct Triple03 {
    std::int32_t a_;
    std::int32_t b_;
    std::int32_t c_;
};

export inline void write_triple03(specodec::SpecWriter& w, const Triple03& obj) {
    w.beginObject(3);
    w.writeField("a"); w.writeInt32(obj.a_);;
    w.writeField("b"); w.writeInt32(obj.b_);;
    w.writeField("c"); w.writeInt32(obj.c_);;
    w.endObject();
}

export inline specodec::SpecCodec<Triple03> Triple03Codec = {
    .encode = [](specodec::SpecWriter& w, const Triple03& obj) { write_triple03(w, obj); },
    .decode = [](specodec::SpecReader& r) -> Triple03 {
        std::int32_t fld_a = 0;
        std::int32_t fld_b = 0;
        std::int32_t fld_c = 0;
        r.beginObject();
        while (r.hasNextField()) {
            auto field_name = r.readFieldName();
            if (field_name == "a") { fld_a = r.readInt32(); }
            else if (field_name == "b") { fld_b = r.readInt32(); }
            else if (field_name == "c") { fld_c = r.readInt32(); }
            else { r.skip(); }
        }
        r.endObject();
        return Triple03{fld_a, fld_b, fld_c};
    }
};

export struct Triple04 {
    std::string a_;
    std::string b_;
    std::int32_t c_;
};

export inline void write_triple04(specodec::SpecWriter& w, const Triple04& obj) {
    w.beginObject(3);
    w.writeField("a"); w.writeString(obj.a_);;
    w.writeField("b"); w.writeString(obj.b_);;
    w.writeField("c"); w.writeInt32(obj.c_);;
    w.endObject();
}

export inline specodec::SpecCodec<Triple04> Triple04Codec = {
    .encode = [](specodec::SpecWriter& w, const Triple04& obj) { write_triple04(w, obj); },
    .decode = [](specodec::SpecReader& r) -> Triple04 {
        std::string fld_a = "";
        std::string fld_b = "";
        std::int32_t fld_c = 0;
        r.beginObject();
        while (r.hasNextField()) {
            auto field_name = r.readFieldName();
            if (field_name == "a") { fld_a = r.readString(); }
            else if (field_name == "b") { fld_b = r.readString(); }
            else if (field_name == "c") { fld_c = r.readInt32(); }
            else { r.skip(); }
        }
        r.endObject();
        return Triple04{fld_a, fld_b, fld_c};
    }
};

export struct Triple05 {
    std::int64_t a_;
    std::string b_;
    bool c_;
};

export inline void write_triple05(specodec::SpecWriter& w, const Triple05& obj) {
    w.beginObject(3);
    w.writeField("a"); w.writeInt64(obj.a_);;
    w.writeField("b"); w.writeString(obj.b_);;
    w.writeField("c"); w.writeBool(obj.c_);;
    w.endObject();
}

export inline specodec::SpecCodec<Triple05> Triple05Codec = {
    .encode = [](specodec::SpecWriter& w, const Triple05& obj) { write_triple05(w, obj); },
    .decode = [](specodec::SpecReader& r) -> Triple05 {
        std::int64_t fld_a = 0LL;
        std::string fld_b = "";
        bool fld_c = false;
        r.beginObject();
        while (r.hasNextField()) {
            auto field_name = r.readFieldName();
            if (field_name == "a") { fld_a = r.readInt64(); }
            else if (field_name == "b") { fld_b = r.readString(); }
            else if (field_name == "c") { fld_c = r.readBool(); }
            else { r.skip(); }
        }
        r.endObject();
        return Triple05{fld_a, fld_b, fld_c};
    }
};

export struct Triple06 {
    std::uint32_t a_;
    std::uint64_t b_;
    std::string c_;
};

export inline void write_triple06(specodec::SpecWriter& w, const Triple06& obj) {
    w.beginObject(3);
    w.writeField("a"); w.writeUint32(obj.a_);;
    w.writeField("b"); w.writeUint64(obj.b_);;
    w.writeField("c"); w.writeString(obj.c_);;
    w.endObject();
}

export inline specodec::SpecCodec<Triple06> Triple06Codec = {
    .encode = [](specodec::SpecWriter& w, const Triple06& obj) { write_triple06(w, obj); },
    .decode = [](specodec::SpecReader& r) -> Triple06 {
        std::uint32_t fld_a = 0u;
        std::uint64_t fld_b = 0ULL;
        std::string fld_c = "";
        r.beginObject();
        while (r.hasNextField()) {
            auto field_name = r.readFieldName();
            if (field_name == "a") { fld_a = r.readUint32(); }
            else if (field_name == "b") { fld_b = r.readUint64(); }
            else if (field_name == "c") { fld_c = r.readString(); }
            else { r.skip(); }
        }
        r.endObject();
        return Triple06{fld_a, fld_b, fld_c};
    }
};

export struct Triple07 {
    std::vector<std::uint8_t> a_;
    std::string b_;
    std::int32_t c_;
};

export inline void write_triple07(specodec::SpecWriter& w, const Triple07& obj) {
    w.beginObject(3);
    w.writeField("a"); w.writeBytes(obj.a_);;
    w.writeField("b"); w.writeString(obj.b_);;
    w.writeField("c"); w.writeInt32(obj.c_);;
    w.endObject();
}

export inline specodec::SpecCodec<Triple07> Triple07Codec = {
    .encode = [](specodec::SpecWriter& w, const Triple07& obj) { write_triple07(w, obj); },
    .decode = [](specodec::SpecReader& r) -> Triple07 {
        std::vector<std::uint8_t> fld_a = {};
        std::string fld_b = "";
        std::int32_t fld_c = 0;
        r.beginObject();
        while (r.hasNextField()) {
            auto field_name = r.readFieldName();
            if (field_name == "a") { fld_a = r.readBytes(); }
            else if (field_name == "b") { fld_b = r.readString(); }
            else if (field_name == "c") { fld_c = r.readInt32(); }
            else { r.skip(); }
        }
        r.endObject();
        return Triple07{fld_a, fld_b, fld_c};
    }
};

export struct Triple08 {
    float a_;
    std::int32_t b_;
    bool c_;
};

export inline void write_triple08(specodec::SpecWriter& w, const Triple08& obj) {
    w.beginObject(3);
    w.writeField("a"); w.writeFloat32(obj.a_);;
    w.writeField("b"); w.writeInt32(obj.b_);;
    w.writeField("c"); w.writeBool(obj.c_);;
    w.endObject();
}

export inline specodec::SpecCodec<Triple08> Triple08Codec = {
    .encode = [](specodec::SpecWriter& w, const Triple08& obj) { write_triple08(w, obj); },
    .decode = [](specodec::SpecReader& r) -> Triple08 {
        float fld_a = 0.0f;
        std::int32_t fld_b = 0;
        bool fld_c = false;
        r.beginObject();
        while (r.hasNextField()) {
            auto field_name = r.readFieldName();
            if (field_name == "a") { fld_a = r.readFloat32(); }
            else if (field_name == "b") { fld_b = r.readInt32(); }
            else if (field_name == "c") { fld_c = r.readBool(); }
            else { r.skip(); }
        }
        r.endObject();
        return Triple08{fld_a, fld_b, fld_c};
    }
};

export struct Triple09 {
    std::string a_;
    std::int64_t b_;
    double c_;
};

export inline void write_triple09(specodec::SpecWriter& w, const Triple09& obj) {
    w.beginObject(3);
    w.writeField("a"); w.writeString(obj.a_);;
    w.writeField("b"); w.writeInt64(obj.b_);;
    w.writeField("c"); w.writeFloat64(obj.c_);;
    w.endObject();
}

export inline specodec::SpecCodec<Triple09> Triple09Codec = {
    .encode = [](specodec::SpecWriter& w, const Triple09& obj) { write_triple09(w, obj); },
    .decode = [](specodec::SpecReader& r) -> Triple09 {
        std::string fld_a = "";
        std::int64_t fld_b = 0LL;
        double fld_c = 0.0;
        r.beginObject();
        while (r.hasNextField()) {
            auto field_name = r.readFieldName();
            if (field_name == "a") { fld_a = r.readString(); }
            else if (field_name == "b") { fld_b = r.readInt64(); }
            else if (field_name == "c") { fld_c = r.readFloat64(); }
            else { r.skip(); }
        }
        r.endObject();
        return Triple09{fld_a, fld_b, fld_c};
    }
};

export struct Triple10 {
    bool a_;
    bool b_;
    bool c_;
};

export inline void write_triple10(specodec::SpecWriter& w, const Triple10& obj) {
    w.beginObject(3);
    w.writeField("a"); w.writeBool(obj.a_);;
    w.writeField("b"); w.writeBool(obj.b_);;
    w.writeField("c"); w.writeBool(obj.c_);;
    w.endObject();
}

export inline specodec::SpecCodec<Triple10> Triple10Codec = {
    .encode = [](specodec::SpecWriter& w, const Triple10& obj) { write_triple10(w, obj); },
    .decode = [](specodec::SpecReader& r) -> Triple10 {
        bool fld_a = false;
        bool fld_b = false;
        bool fld_c = false;
        r.beginObject();
        while (r.hasNextField()) {
            auto field_name = r.readFieldName();
            if (field_name == "a") { fld_a = r.readBool(); }
            else if (field_name == "b") { fld_b = r.readBool(); }
            else if (field_name == "c") { fld_c = r.readBool(); }
            else { r.skip(); }
        }
        r.endObject();
        return Triple10{fld_a, fld_b, fld_c};
    }
};

export struct Triple11 {
    std::int8_t a_;
    std::int16_t b_;
    std::int32_t c_;
};

export inline void write_triple11(specodec::SpecWriter& w, const Triple11& obj) {
    w.beginObject(3);
    w.writeField("a"); w.writeInt32(static_cast<std::int32_t>(obj.a_));;
    w.writeField("b"); w.writeInt32(static_cast<std::int32_t>(obj.b_));;
    w.writeField("c"); w.writeInt32(obj.c_);;
    w.endObject();
}

export inline specodec::SpecCodec<Triple11> Triple11Codec = {
    .encode = [](specodec::SpecWriter& w, const Triple11& obj) { write_triple11(w, obj); },
    .decode = [](specodec::SpecReader& r) -> Triple11 {
        std::int8_t fld_a = 0;
        std::int16_t fld_b = 0;
        std::int32_t fld_c = 0;
        r.beginObject();
        while (r.hasNextField()) {
            auto field_name = r.readFieldName();
            if (field_name == "a") { fld_a = static_cast<std::int8_t>(r.readInt32()); }
            else if (field_name == "b") { fld_b = static_cast<std::int16_t>(r.readInt32()); }
            else if (field_name == "c") { fld_c = r.readInt32(); }
            else { r.skip(); }
        }
        r.endObject();
        return Triple11{fld_a, fld_b, fld_c};
    }
};

export struct Triple12 {
    std::uint8_t a_;
    std::uint16_t b_;
    std::uint32_t c_;
};

export inline void write_triple12(specodec::SpecWriter& w, const Triple12& obj) {
    w.beginObject(3);
    w.writeField("a"); w.writeUint32(static_cast<std::uint32_t>(obj.a_));;
    w.writeField("b"); w.writeUint32(static_cast<std::uint32_t>(obj.b_));;
    w.writeField("c"); w.writeUint32(obj.c_);;
    w.endObject();
}

export inline specodec::SpecCodec<Triple12> Triple12Codec = {
    .encode = [](specodec::SpecWriter& w, const Triple12& obj) { write_triple12(w, obj); },
    .decode = [](specodec::SpecReader& r) -> Triple12 {
        std::uint8_t fld_a = 0u;
        std::uint16_t fld_b = 0u;
        std::uint32_t fld_c = 0u;
        r.beginObject();
        while (r.hasNextField()) {
            auto field_name = r.readFieldName();
            if (field_name == "a") { fld_a = static_cast<std::uint8_t>(r.readUint32()); }
            else if (field_name == "b") { fld_b = static_cast<std::uint16_t>(r.readUint32()); }
            else if (field_name == "c") { fld_c = r.readUint32(); }
            else { r.skip(); }
        }
        r.endObject();
        return Triple12{fld_a, fld_b, fld_c};
    }
};

export struct Triple13 {
    std::string a_;
    std::vector<std::uint8_t> b_;
    double c_;
};

export inline void write_triple13(specodec::SpecWriter& w, const Triple13& obj) {
    w.beginObject(3);
    w.writeField("a"); w.writeString(obj.a_);;
    w.writeField("b"); w.writeBytes(obj.b_);;
    w.writeField("c"); w.writeFloat64(obj.c_);;
    w.endObject();
}

export inline specodec::SpecCodec<Triple13> Triple13Codec = {
    .encode = [](specodec::SpecWriter& w, const Triple13& obj) { write_triple13(w, obj); },
    .decode = [](specodec::SpecReader& r) -> Triple13 {
        std::string fld_a = "";
        std::vector<std::uint8_t> fld_b = {};
        double fld_c = 0.0;
        r.beginObject();
        while (r.hasNextField()) {
            auto field_name = r.readFieldName();
            if (field_name == "a") { fld_a = r.readString(); }
            else if (field_name == "b") { fld_b = r.readBytes(); }
            else if (field_name == "c") { fld_c = r.readFloat64(); }
            else { r.skip(); }
        }
        r.endObject();
        return Triple13{fld_a, fld_b, fld_c};
    }
};

export struct Triple14 {
    std::int64_t a_;
    std::uint64_t b_;
    bool c_;
};

export inline void write_triple14(specodec::SpecWriter& w, const Triple14& obj) {
    w.beginObject(3);
    w.writeField("a"); w.writeInt64(obj.a_);;
    w.writeField("b"); w.writeUint64(obj.b_);;
    w.writeField("c"); w.writeBool(obj.c_);;
    w.endObject();
}

export inline specodec::SpecCodec<Triple14> Triple14Codec = {
    .encode = [](specodec::SpecWriter& w, const Triple14& obj) { write_triple14(w, obj); },
    .decode = [](specodec::SpecReader& r) -> Triple14 {
        std::int64_t fld_a = 0LL;
        std::uint64_t fld_b = 0ULL;
        bool fld_c = false;
        r.beginObject();
        while (r.hasNextField()) {
            auto field_name = r.readFieldName();
            if (field_name == "a") { fld_a = r.readInt64(); }
            else if (field_name == "b") { fld_b = r.readUint64(); }
            else if (field_name == "c") { fld_c = r.readBool(); }
            else { r.skip(); }
        }
        r.endObject();
        return Triple14{fld_a, fld_b, fld_c};
    }
};

export struct Triple15 {
    double a_;
    std::string b_;
    std::vector<std::uint8_t> c_;
};

export inline void write_triple15(specodec::SpecWriter& w, const Triple15& obj) {
    w.beginObject(3);
    w.writeField("a"); w.writeFloat64(obj.a_);;
    w.writeField("b"); w.writeString(obj.b_);;
    w.writeField("c"); w.writeBytes(obj.c_);;
    w.endObject();
}

export inline specodec::SpecCodec<Triple15> Triple15Codec = {
    .encode = [](specodec::SpecWriter& w, const Triple15& obj) { write_triple15(w, obj); },
    .decode = [](specodec::SpecReader& r) -> Triple15 {
        double fld_a = 0.0;
        std::string fld_b = "";
        std::vector<std::uint8_t> fld_c = {};
        r.beginObject();
        while (r.hasNextField()) {
            auto field_name = r.readFieldName();
            if (field_name == "a") { fld_a = r.readFloat64(); }
            else if (field_name == "b") { fld_b = r.readString(); }
            else if (field_name == "c") { fld_c = r.readBytes(); }
            else { r.skip(); }
        }
        r.endObject();
        return Triple15{fld_a, fld_b, fld_c};
    }
};

} // namespace all_types_pairs