// Generated by @specodec/typespec-emitter-cpp. DO NOT EDIT.
export module all_types_opt;
import std;
import specodec;
import all_types;
using namespace all_types;

namespace all_types_opt {

export struct OptSingleString {
    std::optional<std::string> v_;
};

export inline void write_opt_single_string(specodec::SpecWriter& w, const OptSingleString& obj) {
    int field_count = 0;
    if (obj.v_.has_value()) field_count++;
    w.beginObject(field_count);
    if (obj.v_.has_value()) { w.writeField("v"); w.writeString(obj.v_.value());; }
    w.endObject();
}

export inline specodec::SpecCodec<OptSingleString> OptSingleStringCodec = {
    .encode = [](specodec::SpecWriter& w, const OptSingleString& obj) { write_opt_single_string(w, obj); },
    .decode = [](specodec::SpecReader& r) -> OptSingleString {
        std::optional<std::string> fld_v;
        r.beginObject();
        while (r.hasNextField()) {
            auto field_name = r.readFieldName();
            if (field_name == "v") { fld_v = std::optional<std::string>{r.readString()}; }
            else { r.skip(); }
        }
        r.endObject();
        return OptSingleString{fld_v};
    }
};

export struct OptSingleBoolean {
    std::optional<bool> v_;
};

export inline void write_opt_single_boolean(specodec::SpecWriter& w, const OptSingleBoolean& obj) {
    int field_count = 0;
    if (obj.v_.has_value()) field_count++;
    w.beginObject(field_count);
    if (obj.v_.has_value()) { w.writeField("v"); w.writeBool(obj.v_.value());; }
    w.endObject();
}

export inline specodec::SpecCodec<OptSingleBoolean> OptSingleBooleanCodec = {
    .encode = [](specodec::SpecWriter& w, const OptSingleBoolean& obj) { write_opt_single_boolean(w, obj); },
    .decode = [](specodec::SpecReader& r) -> OptSingleBoolean {
        std::optional<bool> fld_v;
        r.beginObject();
        while (r.hasNextField()) {
            auto field_name = r.readFieldName();
            if (field_name == "v") { fld_v = std::optional<bool>{r.readBool()}; }
            else { r.skip(); }
        }
        r.endObject();
        return OptSingleBoolean{fld_v};
    }
};

export struct OptSingleInt8 {
    std::optional<std::int8_t> v_;
};

export inline void write_opt_single_int8(specodec::SpecWriter& w, const OptSingleInt8& obj) {
    int field_count = 0;
    if (obj.v_.has_value()) field_count++;
    w.beginObject(field_count);
    if (obj.v_.has_value()) { w.writeField("v"); w.writeInt32(static_cast<std::int32_t>(obj.v_.value()));; }
    w.endObject();
}

export inline specodec::SpecCodec<OptSingleInt8> OptSingleInt8Codec = {
    .encode = [](specodec::SpecWriter& w, const OptSingleInt8& obj) { write_opt_single_int8(w, obj); },
    .decode = [](specodec::SpecReader& r) -> OptSingleInt8 {
        std::optional<std::int8_t> fld_v;
        r.beginObject();
        while (r.hasNextField()) {
            auto field_name = r.readFieldName();
            if (field_name == "v") { fld_v = std::optional<std::int8_t>{static_cast<std::int8_t>(r.readInt32())}; }
            else { r.skip(); }
        }
        r.endObject();
        return OptSingleInt8{fld_v};
    }
};

export struct OptSingleInt16 {
    std::optional<std::int16_t> v_;
};

export inline void write_opt_single_int16(specodec::SpecWriter& w, const OptSingleInt16& obj) {
    int field_count = 0;
    if (obj.v_.has_value()) field_count++;
    w.beginObject(field_count);
    if (obj.v_.has_value()) { w.writeField("v"); w.writeInt32(static_cast<std::int32_t>(obj.v_.value()));; }
    w.endObject();
}

export inline specodec::SpecCodec<OptSingleInt16> OptSingleInt16Codec = {
    .encode = [](specodec::SpecWriter& w, const OptSingleInt16& obj) { write_opt_single_int16(w, obj); },
    .decode = [](specodec::SpecReader& r) -> OptSingleInt16 {
        std::optional<std::int16_t> fld_v;
        r.beginObject();
        while (r.hasNextField()) {
            auto field_name = r.readFieldName();
            if (field_name == "v") { fld_v = std::optional<std::int16_t>{static_cast<std::int16_t>(r.readInt32())}; }
            else { r.skip(); }
        }
        r.endObject();
        return OptSingleInt16{fld_v};
    }
};

export struct OptSingleInt32 {
    std::optional<std::int32_t> v_;
};

export inline void write_opt_single_int32(specodec::SpecWriter& w, const OptSingleInt32& obj) {
    int field_count = 0;
    if (obj.v_.has_value()) field_count++;
    w.beginObject(field_count);
    if (obj.v_.has_value()) { w.writeField("v"); w.writeInt32(obj.v_.value());; }
    w.endObject();
}

export inline specodec::SpecCodec<OptSingleInt32> OptSingleInt32Codec = {
    .encode = [](specodec::SpecWriter& w, const OptSingleInt32& obj) { write_opt_single_int32(w, obj); },
    .decode = [](specodec::SpecReader& r) -> OptSingleInt32 {
        std::optional<std::int32_t> fld_v;
        r.beginObject();
        while (r.hasNextField()) {
            auto field_name = r.readFieldName();
            if (field_name == "v") { fld_v = std::optional<std::int32_t>{r.readInt32()}; }
            else { r.skip(); }
        }
        r.endObject();
        return OptSingleInt32{fld_v};
    }
};

export struct OptSingleInt64 {
    std::optional<std::int64_t> v_;
};

export inline void write_opt_single_int64(specodec::SpecWriter& w, const OptSingleInt64& obj) {
    int field_count = 0;
    if (obj.v_.has_value()) field_count++;
    w.beginObject(field_count);
    if (obj.v_.has_value()) { w.writeField("v"); w.writeInt64(obj.v_.value());; }
    w.endObject();
}

export inline specodec::SpecCodec<OptSingleInt64> OptSingleInt64Codec = {
    .encode = [](specodec::SpecWriter& w, const OptSingleInt64& obj) { write_opt_single_int64(w, obj); },
    .decode = [](specodec::SpecReader& r) -> OptSingleInt64 {
        std::optional<std::int64_t> fld_v;
        r.beginObject();
        while (r.hasNextField()) {
            auto field_name = r.readFieldName();
            if (field_name == "v") { fld_v = std::optional<std::int64_t>{r.readInt64()}; }
            else { r.skip(); }
        }
        r.endObject();
        return OptSingleInt64{fld_v};
    }
};

export struct OptSingleUint8 {
    std::optional<std::uint8_t> v_;
};

export inline void write_opt_single_uint8(specodec::SpecWriter& w, const OptSingleUint8& obj) {
    int field_count = 0;
    if (obj.v_.has_value()) field_count++;
    w.beginObject(field_count);
    if (obj.v_.has_value()) { w.writeField("v"); w.writeUint32(static_cast<std::uint32_t>(obj.v_.value()));; }
    w.endObject();
}

export inline specodec::SpecCodec<OptSingleUint8> OptSingleUint8Codec = {
    .encode = [](specodec::SpecWriter& w, const OptSingleUint8& obj) { write_opt_single_uint8(w, obj); },
    .decode = [](specodec::SpecReader& r) -> OptSingleUint8 {
        std::optional<std::uint8_t> fld_v;
        r.beginObject();
        while (r.hasNextField()) {
            auto field_name = r.readFieldName();
            if (field_name == "v") { fld_v = std::optional<std::uint8_t>{static_cast<std::uint8_t>(r.readUint32())}; }
            else { r.skip(); }
        }
        r.endObject();
        return OptSingleUint8{fld_v};
    }
};

export struct OptSingleUint16 {
    std::optional<std::uint16_t> v_;
};

export inline void write_opt_single_uint16(specodec::SpecWriter& w, const OptSingleUint16& obj) {
    int field_count = 0;
    if (obj.v_.has_value()) field_count++;
    w.beginObject(field_count);
    if (obj.v_.has_value()) { w.writeField("v"); w.writeUint32(static_cast<std::uint32_t>(obj.v_.value()));; }
    w.endObject();
}

export inline specodec::SpecCodec<OptSingleUint16> OptSingleUint16Codec = {
    .encode = [](specodec::SpecWriter& w, const OptSingleUint16& obj) { write_opt_single_uint16(w, obj); },
    .decode = [](specodec::SpecReader& r) -> OptSingleUint16 {
        std::optional<std::uint16_t> fld_v;
        r.beginObject();
        while (r.hasNextField()) {
            auto field_name = r.readFieldName();
            if (field_name == "v") { fld_v = std::optional<std::uint16_t>{static_cast<std::uint16_t>(r.readUint32())}; }
            else { r.skip(); }
        }
        r.endObject();
        return OptSingleUint16{fld_v};
    }
};

export struct OptSingleUint32 {
    std::optional<std::uint32_t> v_;
};

export inline void write_opt_single_uint32(specodec::SpecWriter& w, const OptSingleUint32& obj) {
    int field_count = 0;
    if (obj.v_.has_value()) field_count++;
    w.beginObject(field_count);
    if (obj.v_.has_value()) { w.writeField("v"); w.writeUint32(obj.v_.value());; }
    w.endObject();
}

export inline specodec::SpecCodec<OptSingleUint32> OptSingleUint32Codec = {
    .encode = [](specodec::SpecWriter& w, const OptSingleUint32& obj) { write_opt_single_uint32(w, obj); },
    .decode = [](specodec::SpecReader& r) -> OptSingleUint32 {
        std::optional<std::uint32_t> fld_v;
        r.beginObject();
        while (r.hasNextField()) {
            auto field_name = r.readFieldName();
            if (field_name == "v") { fld_v = std::optional<std::uint32_t>{r.readUint32()}; }
            else { r.skip(); }
        }
        r.endObject();
        return OptSingleUint32{fld_v};
    }
};

export struct OptSingleUint64 {
    std::optional<std::uint64_t> v_;
};

export inline void write_opt_single_uint64(specodec::SpecWriter& w, const OptSingleUint64& obj) {
    int field_count = 0;
    if (obj.v_.has_value()) field_count++;
    w.beginObject(field_count);
    if (obj.v_.has_value()) { w.writeField("v"); w.writeUint64(obj.v_.value());; }
    w.endObject();
}

export inline specodec::SpecCodec<OptSingleUint64> OptSingleUint64Codec = {
    .encode = [](specodec::SpecWriter& w, const OptSingleUint64& obj) { write_opt_single_uint64(w, obj); },
    .decode = [](specodec::SpecReader& r) -> OptSingleUint64 {
        std::optional<std::uint64_t> fld_v;
        r.beginObject();
        while (r.hasNextField()) {
            auto field_name = r.readFieldName();
            if (field_name == "v") { fld_v = std::optional<std::uint64_t>{r.readUint64()}; }
            else { r.skip(); }
        }
        r.endObject();
        return OptSingleUint64{fld_v};
    }
};

export struct OptSingleFloat32 {
    std::optional<float> v_;
};

export inline void write_opt_single_float32(specodec::SpecWriter& w, const OptSingleFloat32& obj) {
    int field_count = 0;
    if (obj.v_.has_value()) field_count++;
    w.beginObject(field_count);
    if (obj.v_.has_value()) { w.writeField("v"); w.writeFloat32(obj.v_.value());; }
    w.endObject();
}

export inline specodec::SpecCodec<OptSingleFloat32> OptSingleFloat32Codec = {
    .encode = [](specodec::SpecWriter& w, const OptSingleFloat32& obj) { write_opt_single_float32(w, obj); },
    .decode = [](specodec::SpecReader& r) -> OptSingleFloat32 {
        std::optional<float> fld_v;
        r.beginObject();
        while (r.hasNextField()) {
            auto field_name = r.readFieldName();
            if (field_name == "v") { fld_v = std::optional<float>{r.readFloat32()}; }
            else { r.skip(); }
        }
        r.endObject();
        return OptSingleFloat32{fld_v};
    }
};

export struct OptSingleFloat64 {
    std::optional<double> v_;
};

export inline void write_opt_single_float64(specodec::SpecWriter& w, const OptSingleFloat64& obj) {
    int field_count = 0;
    if (obj.v_.has_value()) field_count++;
    w.beginObject(field_count);
    if (obj.v_.has_value()) { w.writeField("v"); w.writeFloat64(obj.v_.value());; }
    w.endObject();
}

export inline specodec::SpecCodec<OptSingleFloat64> OptSingleFloat64Codec = {
    .encode = [](specodec::SpecWriter& w, const OptSingleFloat64& obj) { write_opt_single_float64(w, obj); },
    .decode = [](specodec::SpecReader& r) -> OptSingleFloat64 {
        std::optional<double> fld_v;
        r.beginObject();
        while (r.hasNextField()) {
            auto field_name = r.readFieldName();
            if (field_name == "v") { fld_v = std::optional<double>{r.readFloat64()}; }
            else { r.skip(); }
        }
        r.endObject();
        return OptSingleFloat64{fld_v};
    }
};

export struct OptSingleBytes {
    std::optional<std::vector<std::uint8_t>> v_;
};

export inline void write_opt_single_bytes(specodec::SpecWriter& w, const OptSingleBytes& obj) {
    int field_count = 0;
    if (obj.v_.has_value()) field_count++;
    w.beginObject(field_count);
    if (obj.v_.has_value()) { w.writeField("v"); w.writeBytes(obj.v_.value());; }
    w.endObject();
}

export inline specodec::SpecCodec<OptSingleBytes> OptSingleBytesCodec = {
    .encode = [](specodec::SpecWriter& w, const OptSingleBytes& obj) { write_opt_single_bytes(w, obj); },
    .decode = [](specodec::SpecReader& r) -> OptSingleBytes {
        std::optional<std::vector<std::uint8_t>> fld_v;
        r.beginObject();
        while (r.hasNextField()) {
            auto field_name = r.readFieldName();
            if (field_name == "v") { fld_v = std::optional<std::vector<std::uint8_t>>{r.readBytes()}; }
            else { r.skip(); }
        }
        r.endObject();
        return OptSingleBytes{fld_v};
    }
};

} // namespace all_types_opt