// Generated by @specodec/typespec-emitter-cpp. DO NOT EDIT.
export module mynsinnerdeep;
import std;
import specodec;

namespace mynsinnerdeep {

export struct Baz {
    double z;
};

export inline void write_baz(specodec::SpecWriter& w, const Baz& obj) {
    w.beginObject(1);
    w.writeField("z"); w.writeFloat64(obj.z);;
    w.endObject();
}

export inline specodec::SpecCodec<Baz> BazCodec = {
    .encode = [](specodec::SpecWriter& w, const Baz& obj) { write_baz(w, obj); },
    .decode = [](specodec::SpecReader& r) -> Baz {
        double fld_z = 0.0;
        r.beginObject();
        while (r.hasNextField()) {
            auto field_name = r.readFieldName();
            if (field_name == "z") { fld_z = r.readFloat64(); }
            else { r.skip(); }
        }
        r.endObject();
        return Baz{fld_z};
    }
};

} // namespace mynsinnerdeep