// Generated by @specodec/typespec-emitter-cpp. DO NOT EDIT.
export module mynsinner;
import std;
import specodec;

namespace mynsinner {

export struct Bar {
    std::string y;
};

export inline void write_bar(specodec::SpecWriter& w, const Bar& obj) {
    w.beginObject(1);
    w.writeField("y"); w.writeString(obj.y);;
    w.endObject();
}

export inline specodec::SpecCodec<Bar> BarCodec = {
    .encode = [](specodec::SpecWriter& w, const Bar& obj) { write_bar(w, obj); },
    .decode = [](specodec::SpecReader& r) -> Bar {
        std::string fld_y = "";
        r.beginObject();
        while (r.hasNextField()) {
            auto field_name = r.readFieldName();
            if (field_name == "y") { fld_y = r.readString(); }
            else { r.skip(); }
        }
        r.endObject();
        return Bar{fld_y};
    }
};

} // namespace mynsinner