// Generated by @specodec/typespec-emitter-cpp. DO NOT EDIT.
export module myns;
import std;
import specodec;

namespace myns {

export struct Foo {
    std::int32_t x;
};

export inline void write_foo(specodec::SpecWriter& w, const Foo& obj) {
    w.beginObject(1);
    w.writeField("x"); w.writeInt32(obj.x);;
    w.endObject();
}

export inline specodec::SpecCodec<Foo> FooCodec = {
    .encode = [](specodec::SpecWriter& w, const Foo& obj) { write_foo(w, obj); },
    .decode = [](specodec::SpecReader& r) -> Foo {
        std::int32_t fld_x = 0;
        r.beginObject();
        while (r.hasNextField()) {
            auto field_name = r.readFieldName();
            if (field_name == "x") { fld_x = r.readInt32(); }
            else { r.skip(); }
        }
        r.endObject();
        return Foo{fld_x};
    }
};

} // namespace myns